app/app.go
Currently dogfood keys fail to verify because we check them against the prod API.
=> Pass honeycomb API to VerifyWriteKey

collect/collect.go, collect/collect_test.go, config.toml, config/config.go, config/config_test.go, main.go, sample/deterministic.go, sample/deterministic_test.go, sample/dynamic.go, sample/sample.go
Replaces the global sampler type and sampler config with a default config, and optional per-dataset configs. Before calling GetSampleRate, check for a per-dataset sampler and use that instead.
TODO - actually run this. Also, make hot reloading of configs work.
=> Allow per-dataset sampling configs

collect/collect.go, logger/honeycomb.go, metrics/honeycomb.go
Mistakenly, it's impossible to look at memory used per server because there's no field identifying the samproxy instance that is sending in the metrics and logs. This change adds one.
(along for the ride are three small log content improvements.)
=> add hostname to metrics and logs for better tracking

sample/dynamic.go
I caught a panic accessing `span.Data[field]`. Might be a race, but at the least I'm curious to catch it with an error and hopefully get a little more insight into where it's coming from.
=> find out if it's span or span.Data that's nil and causing a panic

collect/collect.go, collect/collect_test.go, sample/dynamic.go, types/event.go
If a span were to arrive right around when a trace's timer went off, you'd get concurrent access to the list of spans when the collector tries to add a new span while the sending function is trying to iterate across those spans. This can cause the iterator to get a nil span out of the list.
In addition to protecting the span list with a lock this change removes the nil span protection that was in the dynsampler because it should no longer be necessary; there is no case where it should get a nil span. A panic there is nice to help make sure that's true.
=> fix race around span list by protecting its access with a lock

route/route.go
Even though we forward a span to a peer, we should acknowledge the event in the response to the client.
=> [route] fix batch response when event is forwarded to peer

collect/cache/cache.go, collect/collect.go, collect/collect_test.go, go.mod, go.sum, vendor/github.com/hashicorp/golang-lru/.gitignore, vendor/github.com/hashicorp/golang-lru/2q.go, vendor/github.com/hashicorp/golang-lru/LICENSE, vendor/github.com/hashicorp/golang-lru/README.md, vendor/github.com/hashicorp/golang-lru/arc.go, vendor/github.com/hashicorp/golang-lru/doc.go, vendor/github.com/hashicorp/golang-lru/go.mod, vendor/github.com/hashicorp/golang-lru/lru.go, vendor/github.com/hashicorp/golang-lru/simplelru/lru.go, vendor/github.com/hashicorp/golang-lru/simplelru/lru_interface.go, vendor/modules.txt
When we overrun the trace cache, terrible things happen.
* the trace gets orphaned so no new spans (notably the root span) can not be added to it
* the orphaned trace will always wait the full 60sec delay before sending
* we lose the record of how we chose to sample the trace so new spans coming in to the trace will make a new trace and get a different decision 
This change separates the "did I send this trace" cache from the "let me hold this trace structure to build up a tree and make a sampling decision" cache. It creates a much larger (5x) sent cache, since the only thing that needs to exist in the sent cache is a record of whether the trace was sent to Honeycomb and if so, the sample rate used. 
By separating these two caches, we can then also change the regular trace accumulating …
=> add a larger sent trace cache

logger/honeycomb.go, logger/logger_test.go
We set LogLevel before HoneycombLogger.Start is called. Currently, start creates a new HoneycombLoggerConfig object,
then fills it with values from the config file. Since the HoneycombLogger section does not include log level, we effectively
reset the loglevel value to 0 and log everything.
=> [logger] ensure HoneycombLogger does not drop loglevel setting

collect/collect.go
There are a bunch of extra things I'm curious about: how many traces (not spans) does samproxy handle? How long are the spans flowing through? Does it ever hit the sent-trace cache or are all spans that are coming in after traces are sent hitting the regular trace ring cache? These metrics should help answer those questions.
=> adding metrics to collection

route/errors.go
There is a log that spits something like `returning error {err:0xc46e2147b0 msg:unknown API key - check your credentials status:400 detailed:true friendly:true}, no X-Honeycomb-Team header found from within authing middleware` into the `msg` field, polluting the breakdown. This change puts "handler returned error" into the `msg` field and pulls the rest of that content out into their own fields.
=> missed log line with unstructured content

collect/collect.go, logger/honeycomb.go, metrics/honeycomb.go, transmit/transmit.go
Libhoney has a default send queue size of a 1000. After that, we drop things on the floor. This is might be OK when the library is being used inside an instrumented application, but since we're responsible for making sure every event we get gets handled, it is not ok for samproxy. Configuring blockOnSend in the libhoney config to true. This could lead to other issues, like OOMing if there's a large backlog of unsent traces and the goroutines trying to send them pile up. We'll have to see.
I am also adding a response queue processor in the DefaultTransmission implementation. This gives us some maybe useful logging if we get non-200 responses from the API or our peer. Also added some counters to keep track of errors.
=> Add instrumentation, enable blockOnSend in libhoney

collect/collect.go, go.mod, go.sum, main.go, route/proxy.go, route/route.go, transmit/transmit.go, vendor/github.com/honeycombio/libhoney-go/libhoney.go, vendor/github.com/honeycombio/libhoney-go/transmission/transmission.go, vendor/modules.txt
We want to separate the transmission queue for different communication channels so that one will not affect the other. This creates separate clients for upstream and peer communications. In addition, we disable gzip compression when forwarding events to peers, to hopefully cut down on CPU usage.
=> Separate peer/upstream clients, disable gzip on peer communications

logger/honeycomb.go, main.go, metrics/honeycomb.go, metrics/metrics.go, route/route.go, transmit/transmit.go, types/event.go
It'd be nice to know when the place we're sending things hands back errors, whether the things being sent be events, spans, logs, or metrics, and whether we're sending them to peers or upstream to Honeycomb itself. This change teaches samproxy to read the responses queue and do things with errors it gets back down that queue.
=> read response queues, print errored responses

collect/collect.go, collect/collect_test.go, config.toml
There are a bunch of locks involved in getting a span into the right in-memory data structure representing a trace. Previously, the client sending us a span or a batch of spans must wait for all the internal bookkeeping to finish before it gets its response. This can be slow and, especially when dealing with a peer to peer transmission, cause thundering herd backups. Separating receipt of the span with the internal bookkeeping via a buffered channel will allow the recipient to spread out the load with the channel accepting the expected ebb and flow of traffic.
=> put a buffered channel in between accepting spans and navigating the internal data structures to avoid blocking the client

collect/collect.go
adds a metric showing the size of the collector’s incoming queue so we can see if things are failing because that queue size is filling and blocking.
=> fix collector consumers, add metric

collect/cache/cache.go, collect/collect.go, collect/collect_test.go, config/config.go, types/event.go
When used with the dynamic sampler and heavy load, the previous version of samproxy exhibited a thundering herd kind of behavior where a bunch of spans would get sent and then everything would lock up for a while. I believe one cause is all the locks that were scattered through the collector, the collector's cache, and the trace object.
This change removes all those locks by single threading the collector and using channels to serialize all activity. The collector is the thing that
* inserts spans into traces
* calls out to the dynamic sampler to make a sampling decision
* hands off spans to the transmission to be sent
The timeouts (the biggest reason for concurrent access to all the trace objects) are now handled by a goroutine that waits and then submits the trace for sending by adding …
=> single thread the collector, remove all the collector's locks

app/app.go, collect/collect.go, collect/collect_test.go, config.toml, config/config.go, route/proxy.go, route/route.go, sharder/deterministic.go, transmit/mock.go
This PR implements an idea: by preferentially processing spans coming from peers over spans coming from the thing actually sending Samproxy data, we'll ensure that when confronting situations where we can't process all the spans fast enough, we don't make the problem worse while trying to work through the backlog of already-accepted traffic.
=> preferentially process peer traffic to allow upstream backpressure without interal traffic jams

route/route.go
Previously, single events coming in to samproxy got correctly sorted to the peer channel, but those coming from a batch didn't. This fixes that error.
=> use peer channel for batches from peers

.circleci/config.yml, cmd/samproxy/main.go, collect/cache/cache.go, collect/cache/cache_test.go, collect/collect.go, collect/collect_test.go, config/redimem/redimem.go, config/redis.go, logger/honeycomb.go, metrics/honeycomb.go, metrics/prometheus.go, route/route.go, sample/deterministic.go, sample/dynamic.go, sharder/deterministic.go, transmit/transmit.go
* Updating the build to correctly set the version
* adding some output indicating the service is starting always
* adding debug logging indicating each subsystem boots successfully
* adding a timeout to the redis scan to fail when trying to scan too large redis instances
* add indication that registration failed when the initial redis connection fails
=> Adding debug logging, error handling, timeouts

app/app.go, cmd/samproxy/main.go, route/route.go
It is useful to be able to probe the running binary for version info. This endpoint enables that.
=> add endpoint to allow querying the version of the binary via HTTP

sharder/deterministic.go
As part of adding redis, shard equality broke. This change fixes it.
=> Ben.fix sharding

.circleci/config.yml, cmd/samproxy/main.go
Resolves #44 
The default go http library honors settings from the environment with the built in `ProxyFromEnvironment` function.  This change configures samproxy to use the same thing.
Coming along for the ride is an update to the circle ci config to get the build to run.
=> honor proxy settings in the environment

go.mod, go.sum, route/route.go, route/route_test.go
libhoney-go uses zstd by default, so we should support it.
Drive-by cleanup of possible gzip leak. We used to read the compressed body into a buffer, and then return a gzip reader. Without exposing the Close interface, there was no way to clean up the resources created by the gzip reader. I think this would have lead to OOMs over time.
I copied the zstdReader pooling method from our internal shepherd implementation, as that seems to work well enough.
I smoke tested this with gzip (from python) and zstd (libhoney-go) events to verify everything works.
=> [router] add zstd support

collect/collect.go, types/event.go
It looks to be (theoretically, I haven't verified by testing it) possible for multiple goroutines to end up in this particular switch arm at the same time.
Use a `sync.Once` to make sure that even if that happens they can't both try to close the channel and/or send the trace.
=> close possible avenue for racing and panic'ing/sending traces multiple times

config.toml, config/fileconfig.go, config/redis.go
When using redis for peer resolution, we register the host using its hostname. This doesn't work if peers can't resolve eachother by hostname. This adds two new ways to identify the host in the peer list:
- If IdentifierInterfaceName is set, pulls the first unicast IP address from that interface. By default, we pull the IPV4 address, but UseIPV6Identifier can optionally be set to true to use the IPV6 address
- If RedisIdentifier is set, use whatever value is specified to identify the host. This is sort of a catchall in case our other options don't work.
Tested this locally. Here's the log output from each case:
```
INFO[0000] using identifier from interface               identifier="[fe80::101c:fe8c:b38e:5db8]" interface=en0
```
```
INFO[0000] using identifier from interface …
```
=> [redis] allow IP and other host identifiers

app/app.go, config.toml
This is of limited use as it relies on people checking the responses queues in the SDKs which experience shows is a limited pool of people.
https://app.asana.com/0/1179121425642969/1184414223169113/f
=> Remove API key validation

transmit/transmit.go, transmit/transmit_test.go
Add `samproxy/version` to user agent addition to show that events are being sent via samproxy.
=> add samproxy version via user agent addition

config.toml, config/config.go, config/config_test.go, config/fileconfig.go, config/mock.go
Read `time.Duration` direct from the TOML file. 
🚨 This is a breaking config change 🚨
Also removes unused config value GetSpanSeenDelay
=> Use time.duration for config

collect/collect.go
These metrics weren't being reported because they were registered with
the wrong name or not registered at all. I originally noticed that
duration and span count were always zero in our installation and then
found the others with:
$ for metric in $(rg '.*(IncrementCounter|Histogram)\("(.*)".*' -Ir '$2'); do rg -q "Register\(\"$metric\"" || echo $metric; done
collector_tosend_queue
trace_span_count
trace_duration_ms
The `metrics` package could be made more resilient or more obvious to
this happening in the future.
---
The `honeycomb` metrics implementation registers metrics if they aren't already registered. What do you think about the `prometheus` implementation doing the same and removing the explicit `Register` calls altogether?
=> collect: Fix some missing metrics

collect/collect.go
This metric wasn't being reported because it wasn't registered. On
closer inspection, it seems unnecessary because the "sent" is misleading
when the trace could have been dropped by sampling and there are more
specific metrics recorded for `trace_send_kept` and `trace_send_dropped`
=> collect: Remove unregistered trace_sent metric

.circleci/config.yml
Having build events is nice, but it also prevents us from building external contributors PRs. 
Builder external contributor PRs is more valuable than the data that build events can provide us.
=> Remove build events

sample/dynamic.go, sample/dynamic_ema.go, sample/dynamic_ema_test.go, sample/dynamic_test.go
Add the key to all spans within the trace rather than just the root.
There is no additional cost to users storing these in Honeycomb and they
will make it easier to see which keys are contributing to the total rate
by number of spans.
We need this to verify what keys are being used for a large number of
events that we suspect belong to a small number of deep traces. We can't
currently figure out how to query that from Honeycomb because only the
root spans appear when grouped by sampler key. It also can't be combined
with the server-side method for counting the number of spans within a
trace:
- https://docs.honeycomb.io/working-with-your-data/tracing/#span-count-per-trace
We've added simple tests that verify the trace/span pointers are updated
correctly. These tests could be extended to …
=> sample: Add key to all spans

cmd/samproxy/main.go
A typo meant that it overwrote the "config" with the "rules" and failed
to start in Redis mode because `PeerListenAddr` was no longer set:
panic: runtime error: index out of range [1] with length 1
goroutine 1 [running]:
github.com/honeycombio/samproxy/config.(*RedisPeerFileConfig).Start.func1()
/go/src/github.com/honeycombio/samproxy/config/redis.go:122 +0x10b2
sync.(*Once).doSlow(0xc00022a1a0, 0xc0000e7c20)
/usr/local/go/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
/usr/local/go/src/sync/once.go:57
github.com/honeycombio/samproxy/config.(*RedisPeerFileConfig).Start(0xc00022a000, 0xc00022a000, 0x1)
/go/src/github.com/honeycombio/samproxy/config/redis.go:83 +0x9a
main.main()
/go/src/github.com/honeycombio/samproxy/cmd/samproxy/main.go:66 +0x249
=> cmd: Fix config loading for Redis

.gitignore
The existing rules matched anything with `samproxy` or `test_redimem` in
the path, which meant that my editor (which reads `.gitignore`) wouldn't
allow me to find these files and that new files (however unlikely) in
these sub-directories of `cmd/` were never tracked.
Fix it by excluding the directories themselves but still preventing the
binaries from being committed to anywhere in the repo, in case they are
built to/from the wrong location.
=> gitignore: Allow the contents of cmd dirs

collect/collect.go, collect/collect_test.go
The change to accept durations from the config in 272d899 meant that the
effective values were being multiplied by 1 billion. To achieve `1s` you
had to supply `1ns`. Fix this by using the durations directly.
=> collect: Fix SendDelay/TraceTimeout durations

cmd/samproxy/main.go, go.mod, go.sum, service/debug/debug_service.go
Add `-debug` flag which when used, will run a debug service on port 6060.  The debug service allows you to use pprof to visualize and analyze profiling data.
=> add debug service and enable with debug flag

config/config_test.go, config/file_config.go
If we are listening to the same file for changes then the watch event will fire twice and cause some race issues. Resolve this by creating the individual rules files
=> Fix config race condition in tests

collect/collect_test.go, transmit/mock.go
Going through the race detector and fixing small locking issues. This will get us some of the way to running the tests in CI with the race detector on which seems like it would be highly useful.
=> Add some basic locking for transmission based tests

.circleci/config.yml, Dockerfile
As per #95, the current docker setup does not work with go modules.
This changes the following things
- use go mod to fetch dependencies
- build samproxy from source
- use scratch as the final output image
We probably need to think about how we expect people to use this image as there a few other things we could do to improve/tighten this up
=> update docker build process

.circleci/config.yml
The `Honeycomb Secrets` context does not contain the docker credentials
=> Fix docker publish

cmd/samproxy/main.go, config/config.go, config/file_config.go
A small improvement I broke out of making the redis setup easier to use. We can use viper to preferentially use the env variable.
=> Use viper to bind to the env variable redis host

metrics/prometheus.go
We saw several crashes immediately after restarts which were caused by
metrics being registered and updating the same underlying map
concurrently:
fatal error: concurrent map writes
goroutine 100 [running]:
runtime.throw(0xab0615, 0x15)
/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc00006ae20 sp=0xc00006adf0 pc=0x435412
runtime.mapassign_faststr(0x9fe6a0, 0xc000ac0270, 0xc000ab8000, 0x17, 0xc000ab8000)
/usr/local/go/src/runtime/map_faststr.go:211 +0x3f7 fp=0xc00006ae88 sp=0xc00006ae20 pc=0x414cc7
github.com/honeycombio/samproxy/metrics.(*PromMetrics).Register(0xc00009cf60, 0xc000ab8000, 0x17, 0xaa9ac3, 0x7)
/go/src/github.com/honeycombio/samproxy/metrics/prometheus.go:66 +0xa4 fp=0xc00006af18 sp=0xc00006ae88 pc=0x95b834
github.com/honeycombio/samproxy/route.(*Router).LnS(0xc00070c020, …
=> metrics: Fix race in Prometheus start

config/file_config.go
We can just provide the libhoney defaults up here and remove this extra
code.
=> Use libhoney defaults

config/config_test.go
Use the correct file here, these should be the other way around. Not causing any broken tests right now but could certainly cause confusion in the future.
=> Fix `NewConfig` test parameters

logger/honeycomb.go
We were getting queue overflow errors from HoneycombLogger when starting up the app. The libhoney-go transmission uses [muster](https://godoc.org/github.com/facebookgo/muster). If you don't specify `PendingWorkCapacity` in the transmission, which becomes the capacity of muster's work channel, then the work channel becomes blocking and attempting to add the event to the queue fails: https://github.com/honeycombio/libhoney-go/blob/53a88e9cd3b91871ac547d3af1a195737295b7f9/transmission/transmission.go#L129
=> add PendingWorkCapacity to libhoney transmission

config/mock.go, sharder/deterministic.go, sharder/deterministic_test.go
The peer list can temporarily become empty when using Redis discovery
and the Redis state is lost (e.g. restarting an in-memory instance).
This causes a divide by zero panic when attempting to chose a shard and
results in dropping spans that may have already been correctly routed by
another peer.
I experienced this while running a load test to confirm the behaviour
when Redis becomes unavailable. It continues working fine while Redis is
unavailable, but it resulted in these panics when Redis came back:
$ kc logs samproxy-96765ff85-44qg5
time="2020-06-10T14:13:34Z" level=info msg="using identifier from interface" identifier=172.17.0.7 interface=eth0
time="2020-06-10T14:15:52Z" level=error msg="redis scan encountered an error" err=EOF keys_returned=0 timeoutSec=5s …
=> sharder: Refuse to reload empty peer list

.circleci/config.yml
Changes a couple of things:
- always push builds to S3
- if no tag is specified then use the SHA for the current commit
=> Use SHA when tag is not specified

.circleci/config.yml
I noticed that we were using a very old version of the orb that was using an old deprecated version of python. Updated to the latest new shiny
=> Update to latest aws-cli orb

go.mod, go.sum, route/route.go, route/route_test.go
Adds support for msgpack encoded events/batches. 
Supports the same `Content-Type` headers that our API does.
Although there are unit tests to cover this new unmarshal method, some manual testing as part of the review would be great, as we have minimal coverage on code outside of this new test 😬
=> Add msgpack support

cmd/samproxy/main.go, config/config.go, config/config_test.go, config/file_config.go, config/mock.go, config_complete.toml, service/debug/debug_service.go
I tested this locally both by specifying the debug service address in config, and allowing it to choose it's own.
=> allow debug service address to be specified by config

route/errors.go, route/errors_test.go, route/middleware.go
Relies on #121 and resolves #62
Adds the stack to the logger if we have passed in a `ErrCaughtPanic` to the function. The method for determining this is a little jank but I think is good enough for now. We can make a ticket to improve how this works
=> Log panic stack traces

app/app.go, collect/cache/cache.go, collect/collect.go, logger/honeycomb.go, logger/logger.go, logger/logrus.go, logger/mock.go, logger/null.go, metrics/honeycomb.go, metrics/prometheus.go, route/errors.go, route/middleware.go, route/proxy.go, route/route.go, sample/deterministic.go, sample/dynamic.go, sample/dynamic_ema.go, sample/sample.go, sharder/deterministic.go, sharder/single.go, transmit/transmit.go
Uses a new Logger interface to no-op log operations on disabled log levels. It's a break from the logrus model, but I think it's worth it to avoid unexpected perf issues from a misplaced debug line.
=> avoid allocations for unused log entries

app/app.go, app/app_test.go, cmd/samproxy/main.go, collect/collect.go, collect/collect_benchmark_test.go, metrics/mock.go
This is single-node, but captures a lot of the work involved in sending traces. The code's pretty rough and ready but it gets the job done. This shows many more allocations in today's code vs the pre-ticker code, and even more before my log changes. I think that's the source of circle's regression.
Also moves the signal handler out of App.Start into main, so you can Start an app without blocking.
=> add integrated benchmark

collect/collect.go, logger/honeycomb.go, logger/logger.go, logger/logrus.go, logger/mock.go, logger/null.go
Turns out logrus doesn't do what I want when I pass a pointer to a string to WithField. Instead, add WithString() to the Logger interface, which avoids the heap allocation for skipped logs. It's a bit awkward to have both but I think that's a small price to pay for a simple way to avoid vast quantities of garbage.
For background, the problem with `WithField()` is that passing a scalar into the `interface{}` value param causes it to escape to the heap, even if it's ultimately not used. This can add up to a lot of allocations for frequent log lines, and is a huge waste when those logs are disabled. However, a typed `string` value doesn't escape here, so calling `WithString()` is essentially free for disabled log levels.
=> fix broken log line, add WithString for efficiently skipped logs

collect/cache/cache.go, collect/cache/cache_test.go, collect/collect.go, collect/collect_test.go, types/event.go
Moves some of this logic into the cache so it can be done efficiently. This should lower the memory footprint when the cache capacity is set larger than necessary, and should fix the perf regression associated with repeatedly touching already-sent traces in sendTracesInCache().
The improvement is visible using the benchmark in #131 
```
benchmark                    old ns/op     new ns/op     delta
BenchmarkTraces/batch-8      23715         16990         -28.36%
benchmark                    old allocs     new allocs     delta
BenchmarkTraces/batch-8      286            164            -42.66%
```
=> remove traces from cache after they are sent

app/app.go, app/app_test.go, collect/collect.go, collect/collect_benchmark_test.go, collect/collect_test.go, route/route.go, transmit/transmit.go
Fixes shutdown data race in InMemCollector.Stop, and fixes test races found with `go test -race`
=> fix data races

app/app_test.go, collect/collect_benchmark_test.go, collect/collect_test.go, config/config.go, config/config_test.go, config/file_config.go, config/mock.go, config/sampler_config.go, rules.toml, sample/deterministic.go, sample/deterministic_test.go, sample/dynamic.go, sample/dynamic_ema.go, sample/dynamic_ema_test.go, sample/dynamic_test.go, sample/sample.go
Change so that the default is listed above the specific dataset rules and remove the `_default` setting.
Remove SamplerConfig from each of the dataset names.
Means we don't have to test config parsing in any test that involves samplers
=> Simplify the way that the sampler rules are described

.circleci/config.yml
This should work now. I increased the timeout since race tests can be quite a bit slower.
=> enable -race in circle test

app/app_test.go, cmd/samproxy/main.go, go.mod, go.sum, route/route.go
Switch to msgpack for internal (peer to peer and upstream) communication.
Switch to jsoniter for batch event unmarshal, which is notably faster than stock json.
The perf win here is pretty clear, and this benchmark doesn't capture the gains from encoding upstream traffic with msgpack, since libhoney's Writer transmission always uses json.
```
benchmark                              old ns/op     new ns/op     delta
BenchmarkDistributedTraces/batch-8     25991         17567         -32.41%
benchmark                              old allocs     new allocs     delta
BenchmarkDistributedTraces/batch-8     296            226            -23.65%
benchmark                              old bytes     new bytes     delta
BenchmarkDistributedTraces/batch-8     23634         19938         -15.64%
```
=> use more efficient wire serialization

collect/cache/cache.go, collect/cache/cache_test.go, collect/collect.go, collect/collect_benchmark_test.go, collect/collect_test.go, config/mock.go
Also fixes an off-by-one error in the cache building loop, and adds a mutex to mock config to avoid test races.
=> send excess traces when reducing cache size

config/config_test.go, config/file_config.go
The trouble with config reloads is that it means we've got a background goroutine writing new config values - at the same time our code is occasionally reading these values. The real-world risk here is pretty low but in the spirit of cleaning up `go -race` it seems worth getting out of the way.
=> add mutex locking to fileConfig

app/app_test.go, route/route.go
Don't sent spans from peers to other peers - we'd rather collect these on the "wrong" host then bounce them around the cluster forever.
Note this doesn't fix the event endpoint, which shouldn't see any peer traffic anyway. I think that endpoint needs some remedial attention to remove copy pasta and I'll deal with that in a separate PR.
=> only re-route incoming spans

app/app_test.go, cmd/samproxy/main.go, collect/collect.go, collect/collect_benchmark_test.go, collect/collect_test.go, route/route.go, transmit/transmit.go
The collector channel adds now return an error instead of blocking, and peer libhoney has been set non-blocking. Upstream libhoney is still blocking.
Also cleaned up a bit of logging code to slightly reduce allocations.
=> don't block batch endpoint on most queues

collect/cache/cache.go, collect/collect.go, types/event.go
Adds a histogram for active cache entries, and a gauge for capacity (it won't change much, if ever). Also adds counters for traces sent with and without root spans, to help monitor later or otherwise orphaned spans, which can fill up the trace cache.
=> add cache utilization and root span metrics

config/file_config.go
Peers list is not required if file type is redis. https://github.com/honeycombio/samproxy/issues/147
=> peers list should not be required in config

app/app_test.go, go.mod, go.sum, route/route.go, route/route_test.go, transmit/transmit.go, types/event.go
Share the important bits between the batch and event handlers. Add an integration test for the event endpoint. Add testing of meta fields. Remove unused event metadata. Clean up some test code. Remove dead code.
=> consolidate event handling code

config/config_test.go, config/file_config.go, rules.toml, sample/rules.go, sample/rules_test.go, sample/sample.go
Adds new sampler type, which implements some basic rules based sampling.
=> Rules Base Sampler

.circleci/config.yml
There was a request that we always publish latest on main branch to docker hub as the latest tag
=> Always update latest docker tag on main branch

app/app_test.go, transmit/transmit.go
All the setup/teardown here takes a long time, so this makes the whole test run faster.
=> add t.Parallel to integration tests

route/route.go
The alive check for the honeycomb API uses a string value "yes" to respond to its health check.
https://api.honeycomb.io/x/alive
Update to match
=> Make response consistent with Honeycomb API

config/file_config.go, sample/rules.go, sample/rules_test.go
There was a bug where we checked the matched length inside the condition loop. This moves that check outside of the condition loop and ensures that we stop looking at spans once a condition has been matched
=> Fix rules bug

collect/collect.go, collect/collect_test.go, config/config.go, config/config_test.go, config/file_config.go, config/mock.go, rules.toml
Allows customizable dry run field name and updates the default to reference refinery and not samproxy
=> Add customisable dry run field name

sample/dynamic.go, sample/dynamic_ema.go, sample/dynamic_ema_test.go, sample/trace_key.go, sample/trace_key_test.go
Now that we support msgpack the types that might be in the data hash are more varied than they used to be. 
Adds the ability to format any type as a string in order to handle this
=> Handle all the datatypes in the EMA sampler

.circleci/config.yml
These builds don't have the required ENV variables to run this step. This can be seen in #185
=> Skip S3 publish for forked builds

config/config_test.go, config/file_config.go
We moved the redis host to be under the `PeerManagement` key but did not update the path that it puts that ENV variable in. Updated it and added a test to check that we are using it.
=> Fix reading of redis host env variable

config/config_test.go, config/file_config.go
Provide a default sampler to be used if none is specified
=> Add a default sampler if none is specified

route/route.go, route/route_test.go
Match the logic that the API server uses to detect content-type, assuming that everything is JSON unless told that it is msgpack
=> More permissive JSON detection

metrics/prometheus.go, metrics/prometheus_test.go
Handle adding prometheus metrics in the same way that honeycomb metrics class works.
Surprised that no one else has run into this!
Another thing we could do here in addition to this: we could append the dataset that the sampler is for to the metrics so that they should all be unique
=> Handle duplicate prometheus metrics registrations

rules.toml
Fixes #194.
The example config includes the property `DryRunFieldName` that has a string value. However, the value is not wrapped in quotes which makes the config fail to load.
=> Add quotes for example DryRunFieldName value

logger/honeycomb.go
`%d` prints ns, not ms. `%s` will format appropriately for all values.
=> [logger] Properly format duration

README.md, config/config.go, config/config_test.go, config/file_config.go, config/mock.go, config_complete.toml, internal/peer/redis.go
Auth configuration for redis was tested using Azure Cache.
=> Add redis password and TLS basic configuration to peer management.

route/route.go, route/route_test.go
Add a diagnostics HTTP GET endpoint that returns the debug trace information, including the assigned node address using the configured sharding algorithm.
The endpoint can be called like this:
`http://localhost:9000/debug/trace/123abc`
The response is a JSON object two two properties and looks like the following:
`{"traceID":"123abc","node":"http://localhost:12345"}`
=> Add /debug/trace/{traceID} endpoint

cmd/refinery/main.go, config/config.go, config/file_config.go, config/mock.go, config_complete.toml
We're seeing substantial data transfer between peers in our refinery
cluster, far more than we saw going to honeycomb when we were using
hosted refinery.
We're currently running 3 c5.2xlarge instances of refinery, in separate
AZs, and each one seems to be sending ~7MB/s of data to its other 2
peers. Some back of the envelope math suggests this could generate a
bill of `(7MB/s * 3600 * 24 * 30)/1000MB per GB * $0.02/GB = $362.88` for
1 node to talk to one peer. Given each node has 2 peers, and there are
three nodes, it seems plausible that the bandwidth alone could cost in
the ballpark of $2,172 - about 3 times the cost of running the cluster,
without even considering the cost of transmitting the sampled-in data to
Honeycomb.
While looking through the source code I noticed that refinery …
=> Make compression of peer forwarding configurable, rather than hard coded

route/route.go
Detect int64 / int32 sample rates. Some OTLP exporters will send them as these types - so handle appropriately.
=> detect int64 sample rate

route/route.go, route/route_test.go
Resolves #211.
Adds testing for parsing int64 sample rate values. Test cases include parsing a value that can be parsed into an int32 and a value greater than int32 max where the int32 max value is used instead.
Additionally, replace the custom max int32 value with the math package const `math.MaxInt32`.
=> Add tests for int64 sample rate values

route/route.go
**Summary:**
Many different clients support compressing OTLP requests using gzip. Currently refinery does not support any form of compression and the request will fail.
This change adds support for gzip compressed OTLP requests by importing the [google.golang.org/grpc/encoding/gzip](https://pkg.go.dev/google.golang.org/grpc/encoding/gzip) package. The compressor is automatically registered with gRPC servers during import.
**Asana Fixes:**
https://app.asana.com/0/1199604629328245/1199952740433234
**Test Plan:**
I tested by creating a test branch of the [golang-otlp](https://github.com/honeycombio/examples/blob/mike/golang-otlp-gzip/golang-otlp/main.go) example that configured and uses gzip compression. Before applying this change to a local refinery instance, I would receive the following …
=> Add support for gzip compressed OTLP requests

transmit/transmit.go
* it could be a 200 API response that got an error on parsing the body
=> Error response from libhoney does not always mean a non-20x response

sample/rules.go, sample/rules_test.go
When using YAML to specify config rules, the values can be interpreted as `int` instead of `int64`, leading to rule conditions not getting evaluated.  This fixes the compare function for RulesBasedSampler to check for the `int` type as well when doing a compare.
=> Fix YAML config issues

config/file_config.go
Adds an environment variable binding for both the `HoneycombMetrics.MetricsAPIKey` and `HoneycombLogger.LoggerAPIKey` properties.
To keep configs simple, a single environment variable called `REFINERY_HONEYCOMB_API_KEY`, is used for both of these properties. Though possible, the use case to send metrics and logs to different teams doesn't make sense, so using the same environment variable for both is ok.
By making this an environment variable, the API Key can be securely passed into refinery without being recorded in a plain text script or manifest file.
=> Add environment variables for MetricsAPIKey and LoggerAPIKey

.circleci/config.yml
We should only save artifacts to s3 when we've cut a release.
=> only publish to s3 when releasing

config/file_config.go
When loading sampler rules from file based config, it can be difficult to see what rules have been set or any validation errors.
This PR logs the sampler config in `Debug` level and also any unmarshalling / validation errors in `Warn` level.
=> Log sampler config and validation errors

app/app.go, app/app_test.go, collect/collect.go, collect/collect_test.go, route/route.go, route/route_test.go, sample/sample.go, sample/sample_test.go, transmit/transmit.go, transmit/transmit_test.go
When using dependency injection, all dependencies listed in structs must use the same name qualifier. The dependency builder does not auto inject based on property name match.
This PR sets the metrics inject qualifier for the main metrics config that is registered when executing main.go.
This was missed because tests manually create their dependencies and do not rely on dependency injection which I've now added for any struct that injects a metrics instance.
=> Add metrics qualifiers for structs that inject metrics

sample/rules.go
While reading the rules implementation and configuring our local Refinery, I noticed a couple of metrics that appeared to be misnamed. All of the other metrics are prefixed with `rulessampler`, but these two (for dropping events) are prefixed with `dynsampler`. This _seemed_ like an oversight, though I'm by no means an expert. This PR changes the "dropped" metrics to conform to the convention of the other metric names.
Note that this is a breaking change: any existing dashboards, SLOs, etc built around the rules sampler and using the old metric name may no longer work as intended after this rename. A backwards compatible approach would be to emit both metrics, and then deprecate the `dynsampler` version later one. I didn't do that here, but am happy to do so if people feel strongly about …
=> sample: change dynsampler metric names to match rulessampler convention

config/config_test.go, config/file_config.go, config/sampler_config.go
Currently, if `AddSampleRateKeyToTrace` is set to true in a sampler config, and no `AddSampleRateKeyToTraceField` is specified, refinery will attempt to send the sample rate in a field with an empty key. This will result in hard to debug 400s being returned from the Honeycomb Events API. It's probably best to just prevent this configuration scenario. This change makes refinery fail fast if `AddSampleRateKeyToTrace` is true and `AddSampleRateKeyToTraceField` is not set, or is empty.
=> Verify that sample rate trace field key is specified, if needed.

cmd/test_redimem/main.go, go.mod, go.sum, internal/peer/redis.go, internal/redimem/redimem.go
This PR moves from Garyburd Redigo to go module redigo. It also explicitly sets InsecureSkipVerify on the tls config as this was only set if tlsConfig was not set. See [redigo code](https://github.com/gomodule/redigo/blob/72af8129e040d6f962772a8c582e5e9f22085788/redis/conn.go#L246)
=> Move from garyburd Redigo to supported redigo

app/app_test.go, config/config.go, config/config_test.go, config/file_config.go, config/mock.go, config_complete.toml, transmit/transmit.go
The intention is to help determine issues with a single Refinery instance.
=> Add 'meta.refinery.local_hostname' to all spans

config/config.go, config/file_config.go, config/mock.go, config_complete.toml, internal/peer/redis.go
This is a implementation for https://github.com/honeycombio/refinery/issues/251
=> make insecure TLS settings a config option

transmit/transmit.go
* transmission metrics are already prefixed with peer/upstream
* fixes #244
=> Remove redundant peer/api suffix from response error metric

route/route.go
Implements #258 to pass through OTLP span events as regular events with `meta.annotation_type: "span_event"`. I don't see many tests for this codepath, but let me know if there's someplace I could easily add a test for this.
I can confirm that running this locally I'm able to see span events in a production dataset.
=> Propagate span events

route/middleware.go, route/route.go, route/route_test.go
When generating events for OTLP span events and links, each sub-event should also get resource attributes added.
NOTE:
- Fixed a couple of linter warnings in https://github.com/honeycombio/refinery/pull/264/commits/258cf313cc3776733fdd56efbba25ec6aba56c86
- Testing event content is challenging because if the number of dependencies required, collector, metrics, sampler. I've tested the events are created as expected but fixing testing framework is larger task
cc @bdarfler
=> Ensure span links and events generate events and get resource attrs

route/errors.go, route/otlp_trace.go, route/otlp_trace_test.go, route/route.go, route/route_test.go
Adds support for ingesting OTLP requests over HTTP with protobuf data. Changs in this PR:
- Move the existing gRPC export handler and helpers to to otlp_trace.go and tests into otlp_trace_test.go
- Add HTTP handler `postOTLP` that retrieves honeycomb headers, decodes the request body into a OTLP ExportTraceRequest and hands to internal function to process request
- Update OTLP grpc Export handler to retrieve honeycomb headers from metadata and hand request to new internal function to process
- Adds tests to verify rejection behaviour for non-protobuf based requests to postOTLP and test to pass request to postOTLP handler endpoint
=> Add support for OTLP over HTTP/protobuf

route/otlp_trace.go
Customers using OTEL are confused by the absence of `span.kind` attribute, because we map it to `type` on ingest. Adding `span.kind` in, with the plan to let customers know about `type` being deprecated and removing it in the future.
Updates https://github.com/honeycombio/telemetry-team/issues/14
=> Add span.kind when ingesting OTLP

OSSMETADATA, README.md
This came about from some feedback. The reality is that we're not doing active feature work here, but Refinery is definitely maintained and something people should feel comfortable using. It's used internally at Honeycomb at the core of our instrumentation too. So this makes the phrasing a little...nicer...and makes the color green to try and reflect this reality better.
=> Switch licecycle terminology to maintained

config/config_test.go, config/file_config.go, config/sampler_config.go, rules_complete.toml, sample/rules.go, sample/rules_test.go, sample/sample.go
The RulesBased sample is exclusive to the other samplers. This PR allows you to use Dynamic and EMADynamic samplers to determine the sample rate of a RulesBased sampler rule.
This adds a new `Downstream` option to a rule configuration. This option can be used to contain either a `DynamicSampler` or `EMADynamicSampler` option that is a complete configuration of their respective samplers.  When defined the downstream sampler will be used to determine the sample rate when all rule conditions are matched.
A popular use case is to use RulesBased sampling to keep all error and long duration traces while using a dynamic sampler for all other data, based on key fields.
Closes #283 
notes: 
- I'm not sure the word `Downstream` is the right one here. Naming things is hard.
- I would also prefer to …
=> Add dynamic sampler support to rules based samplers

.circleci/config.yml, build/build_docker.sh, go.mod
When publishing to docker, our images should be built and be runnable on multiple architectures. This PR updates our docker image build process to use [Google KO](https://github.com/google/ko) to build the image.
- Resolves #318 
- Resolves #270 
- update go.mod to use v.1.16
- replace docker orb with new `publish_docker` job
- use ko to build multi-arch docker image
- add build/build_docker.sh to manage executing ko command
=> Build and publish multi-arch docker images on tag

metrics/prometheus.go
- When we use refinery in our environment we sometimes encounter a race condition on startup.
```
refinery_1          | time="2021-09-30T13:28:00Z" level=info msg="Peer list has changed. New peer list: [http://127.0.0
.1:8081]"
refinery_1          | fatal error: concurrent map read and map write
refinery_1          |
refinery_1          | goroutine 61 [running]:
refinery_1          | runtime.throw(0xe386aa, 0x21)
refinery_1          |   /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc000047638 sp=0xc000047608 pc=0x438272
refinery_1          | runtime.mapaccess2_faststr(0xd12000, 0xc0002cbef0, 0xe2fa46, 0x18, 0xc0002e00a0, 0xc000296ba0)
refinery_1          |   /usr/local/go/src/runtime/map_faststr.go:116 +0x4a5 fp=0xc0000476a8 sp=0xc000047638 pc=0x414465
refinery_1          | …
```
=> Patch for race condition on map access

.circleci/config.yml, Makefile
- "How We Test This" only lived in the Circle CI config.
- Adds a Makefile
- Adds "test_with_race" and "test_all" make targets for the two test commands CI had been running
- Adds a "test" target to run both
- Adds targets for retrieving and running dockerize to verify Redis is available before running the test suite
- Caches the dockerize release asset
- Caches the go mod dependencies
I'll note that the caching didn't save any appreciable time on the test runs that took advantage of the caches.
=> [dev/ci] test in dev and CI the same way

.circleci/config.yml
We need to provide login credentials for publishing to DockerHub, these were accidentally removed while refactoring.
- re-add docker login command when publishing
=> Re-add missing docker login when publishing

cmd/refinery/main.go, collect/collect_test.go
Our config lets you specify which network name to use for peers; this
flag makes it easier to discover what interfaces the binary has
available.
Example, on a locally-built image:
```
± docker run  -t ko.local/refinery:e2915c3075fd17b54c155f53b04acf0cff1a027a5610cc7bf25052d0725bd7ed --interface-names
lo
eth0
```
=> Add an --interface-names flag

.ko.yaml, collect/collect_test.go
Alpine is not _that_ much bigger than google's distroless image. and
having this OS layer underneath will make it easier to debug.
(Currently: do we have a problem with the network interface name in our
config?)
=> Use alpine as base image

go.mod, go.sum
Bumps libhoney-go to the latest v1.15.6
- update libhoney-go to v1.15.6 in go.mod/sum
=> Bump libhoney-go to v1.15.6

.ko.yaml
This reverts commit 7614a6e1691933a53182f6196be4fa40512f3632.
- Fixes #350 
- As mentioned in the linked issue, running with no command line arguments produced the command line parsing error. By removing this base image, there are no issues running sans command line args.
=> Revert "Use alpine as base image (#343)"

metrics/prometheus.go
This is an attempt at a usable set of buckets for a wide range of metrics
Fixes #115
As noted in the issue, the default buckets in the go client are as follows:
```
DefBuckets = []float64{.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10}
```
… and from the docs … 
> DefBuckets are the default Histogram buckets. The default buckets are tailored to broadly measure the response time (in seconds) of a network service. Most likely, however, you will be required to define buckets customized to your use case.
Additionally from the docs … 
> Buckets defines the buckets into which observations are counted. Each element in the slice is the upper inclusive bound of a bucket. The values must be sorted in strictly increasing order. There is no need to add a highest bucket with +Inf bound, it will be …
=> Improves histogram buckets over the default set

app/app_test.go, cmd/refinery/main.go, config/config.go, config/file_config.go, config/mock.go, config_complete.toml
- MaxBatchSize is currently hardcoded to 500 with no ability to override
- Add config option for MaxBatchSize, with default of 500
=> feat: Make MaxBatchSize configurable

config/config_test.go, rules_complete.toml
rule conditions are ANDed not ORed
- rule example is confusing because it implies that conditions are ORed
- clarify with a better rule name
=> docs: update rules example

internal/peer/redis.go
The refinery process only attempts to connect to redis ones during initialization. This can be challenging when redis is started at the same time and causes refinery to error out.
This change allows refinery to keep attempting to connect to redis for up to 10 seconds, with a one second delay between attempts.
- Add timeout of 10 seconds when calling redis.dial with a 1 second delay between attempts
=> Add retries when connecting to redis during init

.gitignore, collect/collect.go, transmit/transmit.go
Ensure the hostname is set before transmitting upstream to the current hostname.
- Closes #385 
- As suggested by @puckpuck in #385, the host metadata is now added just before the trace is sent upstream
=> Properly set meta.refinery.local_hostname field

config/config_test.go, config/file_config.go
Introduce the "REFINERY_GRPC_LISTEN_ADDRESS" environment variable to allow setting Refinery's `GRPCListenAddr` configuration field, overriding any such configuration read from a file.
Fixes #383.
=> Honor environment variable to set gRPC listener address

CHANGELOG.md
Prepares the v1.9.0 release.
- Adds changelog entry
=> Prepare v1.9.0 release

metrics/honeycomb.go
=> Fixed "honeeycomb" typo in log output when reloading config

.circleci/config.yml
Missing ARM64 RPM artifact (Amazon Linux, RedHat, Rocky, etc)
Adds an ARM64 RPM to the released artifacts.
=> build: add ARM64 RPM artifact

.circleci/config.yml
Updates the AWS CLI orb used in the CircleCI workflows to deploy artefacts. This image based on a Ubuntu image that will longer be avaialble soon.
- Closes #404 
- update awscli orb version to latest (2.1.0)
=> Update aws-client orb to latest

route/route.go
- closes #407 
- Environment name will be returned in auth call in addition to slug.
- Environment slug is no longer supported in the rules file. If it becomes an issue and there is high demand for it, we can consider adding it as an option later.
- Using the environment name instead of the slug is more intuitive for end users, as they set the environment name intentionally, not the slug. This can now be used in the rules config instead of worrying about the structure of the slugified version of the environment.
=> feat: add support for env name from auth

app/app_test.go, transmit/transmit.go
- Refinery logs errors that it receives from libhoney (e.g. events are too large), but does not log any useful identifying information, making it very hard to find the source of the error
- [internal slack thread](https://houndsh.slack.com/archives/CDE86Q55X/p1648054731769209)
- aligned metadata attached to events with what we attach to error logs
- `event_type` and `target` used to be properties on libhoney events, but are now gone, so 🤷 
how errors look before this change:
```
ERRO[0149] error when sending event                      api_host= dataset= error="got unexpected HTTP status 401: Unauthorized" event_type= status_code=401 target=
```
how error look after this change
```
ERRO[0219] error when sending event                      api_host="https://api-dogfood.honeycomb.io" …
```
=> fix: error log event metadata

.circleci/config.yml
Caches Google KO binaries used to build docker images between workflow runs.
- Closes #332 
- uses the CircleCI orb to cache and restore go dependencies
Restoring google ko from cache:
=> Cache google ko deps between workflows

README.md, collect/collect.go, collect/collect_test.go, config/config.go, config/config_test.go, config/file_config.go, config/mock.go, sample/sample.go, sample/sample_test.go
Adds support for config files to contain both a dataset and environment with the same name in the same rules config. This is achieved by adding a DatasetPrefix to the config and then using that prefix when setting up rule definitions.
config.toml
```
DatasetPrefix = "dataset"
```
rules.toml
```
Sampler = "DeterministicSampler"
SampleRate = 1
[production] # environment
Sampler = "DeterministicSampler"
SampleRate = 10
[dataset.production] # dataset
Sampler = "DeterministicSampler"
SampleRate = 20
```
- Closes #408 
- Adds new config option DatasetPrefix, defaults to ""
- If a legacy is provided to the SamplerFactory, it uses the configured prefix along with the sample key to locate rules definitions
- Adds test to verify behaviour
=> Add support for environment and dataset rules with same names

README.md
Quick docs edit as Viper now does inotify-based reloads and we *don't* use a signal to trigger the reload.
=> README: remove incorrect mention of sending SIGUSR1 to trigger a configuration reload

README.md
This pull request modifies the documentation regarding the automatic configuration file reloading when running within a docker container, since you need to mount the directory in rather than the file itself in order for viper to see the configuration changes.
=> add a note about reloading the configuration when running within docker

go.mod, go.sum
Updates husky from 0.10.3 to 0.10.5 (latest). Includes updates and fixes for converting OTLP traces data into honeycomb events.
- Updates husky to 0.10.5
- Ran `go mod tidy`
=> Bump husky to 0.10.5

sharder/deterministic.go, sharder/deterministic_test.go
- Fixes a bug where the shard index can get out of range if the last 4 bytes of the hash of the trace ID is close to 0xFFFFFFFF and the number of shards doesn't divide that value evenly. The algorithm in WhichShard works correctly for divisors of 2^32-1. The prime factorization of that includes 1, 3, 5, 17 (and products of those).
- If shard would be out of range, assigns it to shard 0. This has the most minimal effect on existing behavior, especially when the number of shards changes.
- Adds a test that failed before the out of range check, but works with it in.
Fixes #454
=> Fix crash bug related to sharding

CHANGELOG.md
3558a28 Fix crash bug related to sharding (#455) | [@kentquirk](https://github.com/kentquirk)
111b40d bump husky to 0.10.5 (#450) | [@MikeGoldsmith](https://github.com/MikeGoldsmith)
744df42 Bump github.com/klauspost/compress from 1.15.2 to 1.15.4 (#451) | dependabot
c5c91d6 Bump github.com/tidwall/gjson from 1.14.0 to 1.14.1 (#444) | dependabot
3c8fb13 Bump github.com/fsnotify/fsnotify from 1.5.1 to 1.5.4 (#441) | dependabot
5e16407 add a note about reloading the configuration when running within docker (#448) | [@leviwilson](https://github.com/leviwilson)
4d1d52c README: remove incorrect mention of sending SIGUSR1 to trigger a configuration reload (#447) | [@jharley](https://github.com/jharley)
=> Prep for 1.14.1 release

README.md
Updates README to ensure the correct terminology is used (classic vs legacy).
- Updates README to use classic instead of legacy
=> Replace legacy with classic in README

.github/workflows/release.yml
Adds a github action that creates a new issue on the helm-charts repo when a new refinery release is published.
- Closes #435 
- Adds new github workflow that creates issue on refinery releases
=> Create helm-chart issue on release

sample/deterministic.go, sharder/deterministic.go
`bytesToUint32be` is exactly `binary.BigEndian.Uint32` ([go source](https://cs.opensource.google/go/go/+/refs/tags/go1.18.2:src/encoding/binary/binary.go;l=111)), and is duplicated in the two spots where we use it. might as well save a few lines of code.
=> Replace hand-rolled binary.BigEndian.Uint32 with the real deal

.github/workflows/release.yml
- Found in the kubernetes agent and fixed in https://github.com/honeycombio/honeycomb-kubernetes-agent/pull/266, `github_token` is needed in the workflow instead of `github-token`.
- use `github_token` instead of `github-token` in `release.yml` github workflow
=> maint: update action to auto-create issue for helm chart

config/config_test.go, config/sampler_config.go, rules_complete.toml, sample/rules.go, sample/rules_test.go
We'd like to be able to apply all of the conditions in a rules-based sampler rule to a single span. In other words, we'd like a rule to be considered matched only if *all* of the conditions in that rule are satisfied by a single span in the trace. This allows us to more accurately make per-service sampling decisions in a dataset written to by multiple services.
- Closes see #420
At a high level, we add a new `Scope` configuration option to the rule definition. By default (and if unspecified) it is "trace". If "span", all conditions in the rule must be satisfied together by some span in a trace. This is a subtle but important difference with the default behavior, effectively making a rule more strict than it would otherwise be.
`Scope` introduces some complexity to the rule based sampler. …
=> Add rule Scope configuration option to rules-based sampler

sample/rules_test.go
The test to validate the new span scoped rule sets in #440 only validated the keep return property for unsuccessful sets of spans. This PR updates the test to verify that the keep property is correct by updating the sample rate on the rule set to 1.
- Update sample rate in the test to 1, so we can validate the keep return property
=> Validate successful span scoped rules test

.github/workflows/release.yml
- Error in previous workflow that attempted to create an issue states "Input required and not supplied: title".
- While the title does match that of the [example](https://github.com/actions-ecosystem/action-create-issue#example) provided in the actions repo, it is based on a variable that is set in the example that we do not have set. I believe this is causing a blank title which is not allowed, as the title value is required. This PR changes the title from a variable that is unset (`{ steps.date.outputs.today }}`) to a hard-coded string (`Bump Refinery to Latest Version`).
=> maint: change title on release workflow from (unset) var to hard-coded string

.github/workflows/release.yml
- updates #476 
- GITHUB_TOKEN is a limited token with only enough permissions to modify current repo
=> maint: update GH action token

.github/workflows/release.yml
- updates #476 
- action is still 404ing with the more powerful github token
- based on the action [docs](https://github.com/actions-ecosystem/action-create-issue) mayybe this is how the repo is supposed to be configured?
=> maint: attempt to fix release action

README.md, config/config.go, config/config_test.go, config/config_test_reload_error_test.go, config/file_config.go, config/mock.go, go.mod, internal/peer/peers_test.go, route/otlp_trace_test.go, route/proxy.go, route/route.go, route/route_test.go, sample/sample.go
There have been multiple reports of people not realizing their configs were not parsing the way they were intended. This adds two endpoints:
- `/debug/allrules/$FORMAT` will retrieve the entire rules configuration
- `/debug/rules/$FORMAT/$DATASET` will retrieve the rule set that refinery will use for the specified dataset. It comes back as a map of the sampler type to its rule set.
- Add the endpoints
- Add a feature to config to return the full rule set
- Extend existing config feature to return the sampler name along with its rules struct
- Add/expand tests for it all
=> Add endpoints to help debug refinery rules

go.mod, go.sum, route/mock.go, route/route.go, route/route_test.go
Similar to the `/x/alive` endpoint for the http server, this PR
implements the gRPC handlers for the [gRPC Health Checking
Protocol](https://github.com/grpc/grpc/blob/592bfb9c0040fba382e5dc106e2ebbf0c96465fb/doc/health-checking.md).
I was able to verify that this works by running refinery with the
complete config to set `GRPCListenAddr = "0.0.0.0:9090"`:
```
⇒  go run ./cmd/refinery -c config_complete.toml -r rules_complete.toml
...
```
And then I could run the
[grpc-health-probe](https://github.com/grpc-ecosystem/grpc-health-probe)
binary:
```
⇒  grpc-health-probe -addr=localhost:9090
status: SERVING
```
Closes #414
=> Implement grpc-health-probe

config/config.go, config/config_test.go, config/file_config.go, config/mock.go, config_complete.toml, route/route.go
Which problem is this PR solving
--------------------------------
At the moment, there is no way to override the ServerParameters used in
the `keepalive` configuration of the gRPC server. As to @bdarfler's
comments in #263, issues can arise where new hosts will never be
connected to because clients will reconnect to already existing hosts
and by the time replacement hosts are available, all clients will have
reconnected to existing hosts with a
`MaxConnectionAge`/`MaxConnectionAgeGrace` of
[infinity](https://github.com/grpc/grpc-go/blob/60a3a7e969c401ca16dbcd0108ad544fb35aa61c/internal/transport/defaults.go#L36-L37).
Short description of the changes
--------------------------------
The changes made are to plumb through the configuration of the GRPC
ServerParameters from the viper …
=> Make gRPC ServerParameters configurable

collect/collect.go
- Fixes #468
- If sample rate < 1 on a late span, set it to 1 before doing any further sample rate math.
=> Fix sample rate for late spans

collect/collect.go, collect/collect_test.go
Refinery re-writing the sample rate was causing some concern. Writing down the sample rate sent to refinery prior to updating the sample rate should allow for more/better debug.
This is implementing the suggestion of @robbkidd in #490 to add annotations to the spans of their original sample rate. This will allow for better understanding of what is happening when there are multiple tiers of sampling happening in the telemetry processing.
At the places where the Span SampleRate was combined with the Trace SampleRate, the original span SampleRate is copied down into a meta.refinery annotation.
=> Add 'meta.refinery.original_sample_rate'

CHANGELOG.md, OSSMETADATA
Prep for release 1.16.
Includes update of OSS metadata badge to active.
=> Prepare v1.16.0 release

metrics/honeycomb.go
Honeycomb metrics currently utilises 3 locks, one for each map of counters, gauges and histograms and is unnecessary. In addition, the locks were only used when registering each metric and collecting metrics values - they were missing the lock to retrieve an entry for updating which risks a read / write error.
This PR updates honeycomb metrics to utilise a single lock that is used to control all three types of metrics and is also used when attempting to retrieve a metric from a map.
- Fixes #512 
- Consolidate the 3 locks into a single lock
- Use lock when attempting to retrieve an existing metric from one of the maps to prevent concurrent read / write panics
=> Consolidate honeycomb metrics to use single lock & fix concurrent read/write

cmd/refinery/main.go, config/config.go, config/file_config.go, config/mock.go, config_complete.toml
We have an issue where our ALB traffic has a `~5m` latency because of the cadence in which the CloudWatch logs are sent. Because the ALB represents our top-level traces, this means that _all_ web traffic is delayed by that same amount.
Decreasing the `TraceTimeout` value assists with this by spreading out the traffic, however this makes our rules a moot point as things we are intentionally trying to downsample do not get downsampled.
What we _really_ need is a manner to control how frequently events are sent upstream to Honeycomb so we can control how frequently we send things. https://github.com/honeycombio/libhoney-go/blob/8af08e456cfe1f786247ffdc755855999add2d76/libhoney.go#L136 indicates that `SendFrequency` can override how often batches are sent.
This PR allows for the …
=> allow BatchTimeout to be overriden on the libhoney Transmission

app/app_test.go, config/config.go, config/config_test.go, config/config_test_reload_error_test.go, config/file_config.go, config/mock.go, config_complete.toml, internal/peer/peers_test.go, logger/honeycomb.go, metrics/honeycomb.go, route/route_test.go, sample/sample_test.go, transmit/transmit.go
As noted in #513, errors that occur while Refinery is trying to send data to Honeycomb happen asynchronously. It's hard to relate any errors that show up in the logs with the spans that caused them to occur. However, there is a way provided by libhoney ([metadata](https://github.com/honeycombio/libhoney-go/blob/25068939fe8240ccc45e4c86271b6f057c5f833d/transmission/response.go#L11)) that makes it possible to attach data to the error. Before now, Refinery has attached the dataset, api host, and environment to the metadata. This helps but is not enough.
This PR attempts to leverage that technique further by adding a new configuration value called `AdditionalErrorFields`. It allows the user to specify a list of field names. In the event of a transmission error, these fields (if they exist) …
=> Allow adding extra fields to error logs

metrics/honeycomb.go, metrics/honeycomb_test.go
The tip of refinery was crashing in metrics with a nil pointer error. It was puzzling why a function that was supposed to never return nil was in fact returning nil. The problem was a subtle variable shadowing issue that I only found by writing a test script and running it in the debugger:
```go
metric, ok = metrics[name]
if !ok {
// create new metric using create function and add to map
metric := createMetric(name)
metrics[name] = metric
}
lock.Unlock()
return metric
```
The := on the createMetric created a new variable called `metric` that was scoped to the body of the if clause. The next line properly assigned it to the map and then threw it away and returned the nil pointer created on the top line.
- Removed an unneeded `:`
- Added some tests for the getOrAdd function
- Fixed a couple …
=> Fix variable shadowing bug

transmit/transmit.go
- A previous PR (#514) changed the type of the metadata object from `map[string]string` to `map[string]any`, but I must have forgotten to hit save at some point, and this part of it (4 lines) didn't get committed. This bug actually will cause that feature to omit fields it knows about.
- Change the type appropriately in processResponses
=> Properly set metadata to values that will work.

.circleci/config.yml, go.mod
- bumps minimum go version to 1.19
- bumps module to use 1.19
- bump circleci to build targeting 1.19
=> Bump go version to 1.19

config/mock.go, internal/peer/redis.go, sharder/deterministic.go
When hosting Refinery in a cloud environment, certain network assumptions are no longer true. 
Issues arise from these assumptions while hosting in our cloud environment using [Nomad](https://www.nomadproject.io/) as container orchestration.
Terms, as used in Nomad:
- Task: Single deployed container.
- Group: Group of tasks running as a scalable service (e.g. Refinery).
This assumption is not necessarily true under Nomad:
- The IP assigned to a task's `eth0` can be accessed by other tasks in the group.
Redis peering expects peers to talk to each other using their `eth0` IP.  This behavior can be overridden by specifying `RedisIdentifier` in config.  This value will be advertised as the peer's IP in the peer list.
However, on startup, peering uses its `eth0` IP to cross-reference in the …
=> Cloud support

Makefile, collect/collect.go, collect/collect_test.go, config/config.go, config/file_config.go, config/mock.go, config_complete.toml, sample/rules.go, sample/rules_test.go, types/event.go
Adds the ability to add the trace's span count to the root span of the trace, and does it in a way that allows the rules engine to query it as `meta.span_count`. This would allow rules that depend on span count -- for example, a rule that adjusts sample rate so that larger traces are kept less often.
Note that this value is not available if the root span hasn't arrived when the TraceTimeout completes; at this point, the rules will be evaluated without a `span_count` because there is no root span to put it on. 
If the root span arrives late, it will be updated with the total number of spans that have arrived at that point, so that the value stored in Honeycomb is close to correct. If more spans arrive later, they will not update the value in the root span.
Closes #524  
Closes #483
=> Track span count and optionally add it to root

collect/cache/cache.go, collect/cache/cache_test.go, collect/collect.go, collect/collect_test.go, config/config.go, config/config_test.go, config/file_config.go, config/mock.go, config_complete.toml, rules_complete.toml, types/event.go, types/event_test.go
Implements a new cache management strategy that ejects "large" items from the cache rather than resizing the cache.
Currently, when Refinery is under memory pressure and exceeds the configured memory maximum, it attempts to resize the trace cache to 90% of its previous size, and ejects the oldest traces. But as the trace cache is sized by trace count, when a very large trace arrives, it can cause the cache to shrink repeatedly, discarding the smaller traces, which doesn't help much. The result is that the cache can be resized to a tiny fraction of its original size to very little benefit.
Furthermore, it never recovers until configuration is manually reloaded. 
This PR implements a different strategy:
* The memory size of individual spans is calculated when they are placed into the cache …
=> New cache management strategy

route/route.go
The /query endpoints aren't setting Content-Type, which they should.
- Set content-type based on the type asked for.
=> Set content-type on marshalToFormat

app/app_test.go, cmd/refinery/main.go, config/config_test_reload_error_test.go, internal/peer/peers.go, internal/peer/peers_test.go, internal/peer/redis.go, internal/redimem/redimem.go, sample/rules_test.go, sharder/deterministic_test.go
- In a redis-managed pool of peers, the peer group is updated only after a timeout. This adds explicit unregistration so that in the case of a deliberately terminated instance, redis is notified immediately that the peer has dropped.
- Doesn't change the behavior of refreshing the peer list, which is still a pull-based timeout.
- Fixes #393 
- Add an Unregister method to redimem
- Add a done channel to the goroutines that keep redis updated
- Unregister when the done channel is closed
- Propagate the done channel through the app initialization
- Close the done channel on shutdown
- Update tests
- Add a new test to make sure that unregistration happens
- Also adds a new test case to rules; I wrote it to verify we didn't have a bug and thought it should probably stay in.
=> On shutdown, remove ourself from the peers list

config/config.go, config/file_config.go, config/mock.go, config_complete.toml, go.mod, go.sum, sharder/deterministic.go, sharder/deterministic_test.go
The legacy code in Refinery does a deterministic sharding calculation; for every span that comes in, we hash the traceID with SHA1, truncate to generate a 32-bit number, then divide the range by N if there are N shards. If there are 4 shards, the lowest values go to shard 0, the next block goes to shard 1, etc. 
The problem is that if the number of shards changes from 4 to 5, 1/5 of the shards that would have gone to 0 now go to 1. 2/5 of shard 1 now goes to shard 2; 3/5 of shard 2 (more than half!) goes to shard 3, and so forth. On average, half the shards move.
The practical result of this is that when a span arrives just after a change in shard count, there’s a chance that it will end up on a different shard from other spans in the same trace that arrived earlier. The two shards might …
=> feat: Implement alternative sharding using rendezvous hash to improve dynamic scalability

config/config_test_reload_error_test.go, sharder/deterministic_test.go
- There was a merge error between successive PRs that caused some new tests to fail because they didn't have the new signature for the NewPeers function.
- Add missing done channels to several tests.
=> fix: Add missing done channel to fix build

.github/workflows/add-to-project-v2.yml
This changes the workflow to use the Collections board instead of the Telemetry team.
=> chore: Change workflow to use Collections board

README.md
Refinery currently supports the user of env vars for several configuration options but does not document them
Fixes https://github.com/honeycombio/refinery/issues/579
Adds an env var section to the configuration documentation in the README.
=> docs: add environment variables

config/sampler_config.go, sample/rules_test.go
- Some of the tests for rules were dependent on random numbers. This fixes that, and also cleans up some of the datatype conversion rules to work in more cases
- Fix tests to check both the keep and rate values
- Fix logic in some tests
- Change `tryConvertToString` to just use sprintf("%v"), even for strings, for consistency
- fix string operators to use tryConvertToString everywhere
=> fix: Fix flaky tests, clean up logic on rules

app/app_test.go, cmd/refinery/main.go, collect/collect.go, collect/collect_test.go, collect/stressRelief.go, config/config.go, config/file_config.go, config/mock.go, config_complete.toml, metrics/honeycomb.go, route/route.go, route/route_test.go
The problem this is designed to address is that refinery can become unstable under heavy load, and it goes from stable to unstable very quickly. A larger refinery cluster can be very hard to bring up -- we've seen what are effectively contagious restarts, where a given node crashes, wakes up, and then another node crashes, etc. 
The general idea here is "let's make refinery be more stable by allowing it to shed load quickly under stress". This PR implements a "StressRelief" system that, when activated, deterministically samples each span based only on its trace ID, without attempting to direct traces to the appropriate shard first. The configuration determines the sample rate used.
There is configuration to set this up, and it allows the "mode" to be configured as "never" (it's not …
=> feat: Stress Relief system

route/route.go
- A customer noticed that one of our debug log includes the plaintext API key 
- removes an api key from a debug log
=> fix: Remove API key logging

collect/stressRelief.go, config/file_config.go, config_complete.toml
In testing stress relief, I found that it could turn off too easily, and it might then cause refinery to crash. 
- Don't let stress relief turn off until stress levels are below the deactivation level for 10 consecutive seconds
- Move the calculation of stress relief into the periodic stress check, rather than doing it on every span. Now each span check needs only a read lock.
- Tweak the math for sigmoid (it had a little slop that was bugging me).
=> perf: Improve performance of stress relief

route/otlp_trace.go, route/otlp_trace_test.go, route/route.go
- Updates Refinery to use the gRPC server pattern that Shepherd uses.  This will allow us to add support for metrics and logs proxying in the future.
- Adds new TraceServer that implements the `TraceServiceServer` interface.
- Unimplement `TraceServiceServer` for `Router`.
=> refactor: Change Router to use TraceServer

config/config.go, config/config_test.go, config/file_config.go, config/mock.go, config_complete.toml, internal/peer/redis.go
In a blue/green deployment model, two refinery clusters might want to share the same instance of redis. It's also possible that multiple apps want to share one redis. This permits that by:
- allowing the redis "database" (an integer from 0-15) to be specified in the configuration
- allowing the redis "prefix" (a string used in the name of the keys stored in redis) to be set as well. It already existed but was hardcoded to "refinery".
- Add RedisDatabase and RedisPrefix to the PeerManagement section of config.
- Add tests
- Add documentation
Fixes #544
=> feat: Add ability to set Redis database and prefix in config

collect/collect.go, collect/collect_test.go
Fixes #415 
This issues prevents sending the actual sample rate in dry run mode, instead adding a metric called `meta.dryrun.sample_rate` so that a user can know what their sample rate in dry run mode would have been.
=> fix: do not send sample rate in dry run

.circleci/config.yml
- We want every build of refinery to get published to Honeycomb's ECR, so that we can deploy from there to internal sources.
- Adds a new task to CircleCI and runs it on every commit.
=> chore: Publish every build to honeycomb's ecr

.circleci/config.yml
- The ECR publish should only happen on pushes to main, for two reasons:
-  not every branch (like dependabot's branches) has a right to do it
- we deploy on push to main, and that's what uses this publish
- change workflow so it only applies to the main branch
=> chore: publish should only happen on main

build-docker.sh
- Adds labels to the built images
- adds 3 new labels to the built images
- tested these additions in https://github.com/honeycombio/honeycomb-kubernetes-agent/pull/354.  I don't really want to run the same steps for Refinery since they are risky and Refinery's build is more complicated so there is more risk of publishing an incorrect image.
=> maint: Add labels to docker image

collect/stressRelief.go
- A customer saw refinery crashes due to trying to close the StressRelief.Done channel twice.
- Remove Stop() function, which was implemented to let the injection system shut down Stress Relief (symmetric to Start()). We don't need it, because the only thing it did was close the Done channel. The Done channel is closed externally by main() during shutdown and you can't close a channel more than once. This will prevent a confusing crash on shutdown.
=> fix: Remove Stop() function from stress relief

refinery.service
In testing Refinery with Amazon Linux 2023, I noticed that systemd refused to start the Refinery service, complaining about:
```
Failed to enable unit: Cannot alias refinery.service as refinery.
```
[I asked](https://github.com/amazonlinux/amazon-linux-2023/issues/314) the Amazon Linux devs what they thought about this, and they pointed out that Alias directive is being used incorrectly and helpfully suggested a better replacement.  Their comment:
> I'm a bit surprised this ever worked, actually. At best it was redundant, but it's not clear that it was ever even valid. Going back as far as AL2's systemd 219, the documentation indicates that aliases must specify the same suffix as the original unit file. An alias without a suffix at all has never been documented as being valid or …
=> fix: Replace incorrectly used Systemd Alias directive with a WantedBy

tools/convert/config.md, tools/convert/configData.yaml, tools/convert/helpers.go, tools/convert/templates/configV2.tmpl, tools/convert/templates/docgroup.tmpl, tools/convert/templates/genfield.tmpl
Several issues with config in progress. 
- A bug in Refinery v1 means that some configs will have values under `SampleCache`, and others under `SampleCacheConfig`. This gives us the ability to use both.
- There was a vertical spacing error in doc generation
- Add default values to the generated config
- Differentiate between values we always want and values where we always want to show an example.
- Regenerate the generated files with all of the above.
=> fix: Various config fixes

types/event.go
Panics on certain events due to attempt to assert []byte to string.
Handle each case separately
Original work by @RainofTerra in #686 but we need a patch to a previous release.
=> fix: Port fix from #686 to patch branch

collect/stressRelief.go, route/route.go
- #688 
When stress relief activates, it stops sending peer traffic. But the metrics that update stress relief based on peer volume only update when there's peer traffic. 
This causes any trace that refinery keeps (forwards to Honeycomb) in stress relief mode to *also* be sent as a probe to the appropriate peer (which then drops it).  This ensures that a little bit of traffic also gets to peers, which keeps the system operating normally and updating metrics.
- Make a copy of the incoming event as a probe whenever stress relief is active and would keep a span; if the probe would have been sent to a peer, send it. 
- When a probe is received from a peer, drop it without further examination.
- Log when this happens on both sides.
- Add the stress relief reason to the `meta.refinery.reason` …
=> fix: send probes to peers during stress relief

collect/stressRelief.go, route/route.go, types/event.go
- We had made some fixes on a branch for internal deployments. This pulls them over without closing that branch.
- Sends a small amount of data to peers during stress relief; Closes #688  
- Adds stress relief reason to the meta.refinery.reason when stress relief is activated
- Fixes a bug where json that got unmarshaled as []byte would panic
=> fix: import fixes from bug fix branch

config/config_test_reload_error_test.go, config/metadata/rulesMeta.yaml, config/sampler_config.go, route/route_test.go, rules_complete.toml.old, sample/windowed_throughput.go, sample/windowed_throughput_test.go, tools/convert/rules.md
Depends on #708 
- Adds the other new sampler from the latest dynsampler-go.
- Add the sampler and its config info
- Update the docs
- Add a basic test (dynsampler has all the sampler testing)
=> feat: Add WindowedThroughput sampler

config/config_test_reload_error_test.go, sample/dynamic.go, sample/dynamic_ema.go, sample/ema_throughput.go, sample/totalthroughput.go, sample/windowed_throughput.go, tools/convert/rules.md
Depends on #709 
- The MaxKeys value is supported in most samplers, but it wasn't always included in the config
- It defaulted to 0 which means "no max" -- Honeycomb CAs agree this is not a useful setting.
- Support MaxKeys in all dynamic samplers
- 0 now means 500
=> feat: MaxKeys fixes

collect/stressRelief.go
https://github.com/honeycombio/refinery/issues/702
Refinery doesn't log when starting stress relief mode on boot for `MinimumStartupDuration`
Logs the reason for starting up in stress relief (reason is set to the name of the config in the code, `MinimumStartupDuration`)
=> fix: Log reason for MinimumStartupDuration

app/app_test.go, config/config.go, config/file_config.go, config/mock.go, route/middleware.go, route/otlp_trace.go, route/otlp_trace_test.go
- The new config changed the way that the list of authorized API keys is managed. This carries that through the internal logic and makes it faster as well.
- Change GetAPIKeys() to IsAPIKeyValid
- Use the boolean flag as an early-out
- Store the list of keys in a set for O(1) access
- Fix tests that used it
Fixes #673.
=> fix: API key logic

config.md, rules.md, tools/convert/helpers.go, tools/convert/templates/cfg_docfield.tmpl, tools/convert/templates/cfg_docfile.tmpl, tools/convert/templates/cfg_docgroup.tmpl, tools/convert/templates/rules_docfield.tmpl, tools/convert/templates/rules_docfile.tmpl, tools/convert/templates/rules_docgroup.tmpl
This tweaks the docs generation code to create documents that are closer to the needs of the docs team.
- Helper function to generate one line per sentence in generated docs
- Use the helper function
- Reformat the preamble of the rules file
- Regenerate the docs (most of the changed lines are in the .md files)
=> maint: Generate docs better suited to docs team prefs

cmd/refinery/main.go
- Fixes #691 by pre-registering metrics generated by libhoney.
- Pre-register two instances of metrics, once for peers and once for upstream.
=> feat: preregister libhoney metrics

sample/dynamic.go, sample/dynamic_ema.go, sample/ema_throughput.go, sample/totalthroughput.go, sample/windowed_throughput.go
- As it says in #636, throughput and dynamic sampler calculations have been based on the wrong numbers for some time. They've been counting traces, not spans, and yet everything about Honeycomb is based on span count. Most people think it works by counting spans and are then surprised when sample rates seem incorrect for their volume, and in fact, our documentation says that it works this way.
- This changes Refinery's dynamic and throughput sampler requests to use the span count, not the trace count, when calculating numbers for the dynamic samplers and throughput samplers. 
This will need to be reflected in updated documentation.
Closes #636.
=> fix: Update dynamic samplers to use GetSampleRateMulti

collect/collect.go, collect/collect_test.go, config/config.go, config/config_test.go, config/file_config.go, config/mock.go
- Config rework had left some accessor functions for fields no longer in the config. This removes them.
=> maint: remove remaining references to obsolete fields

config/sampler_config.go, tools/convert/ruleconvert.go
- Since we adjusted sampler behavior to count spans, not traces, users may need to tweak sample rates and throughput values. This change has the converter issue a warning in those cases.
- Resolves a concern @TylerHelmuth expressed in #717 
- Add test for which samplers might need to be fixed
- Check it on rule conversion
The warning looks like this for the demo rules file:
```
WARNING: Version 2 of Refinery has changed the way that sample rates are calculated for
the dynamic and throughput samplers. Refinery v1.x was documented as counting the number
of spans, but in fact it was counting traces. Version 2 samplers correctly count the
number of spans when doing these calculations.
This means that you may need to adjust the target throughput or sample rates to get the
same behavior as …
```
=> feat: Warn about samplers that might need adjustment

collect/cache/cache.go, collect/cache/cache_test.go
- Refinery's trace cache is implemented as a circular buffer. Until this PR, when the buffer wrapped around and tried to re-use a slot that was still in the cache, it would immediately eject it and replace it with the new trace. This PR changes that logic to try the next 5 slots, which means that the occasional long-lived trace won't be ejected just because it's next in line.
I benchmarked this and it's actually slightly faster than the old method, because it ejects traces less often.
For sites where only occasional traces live a long time, this should greatly decrease the number of times that a `collect_cache_buffer_overrun` occurs.
- Modify the Set() method to try several slots before giving up
=> fix: Try a few slots when there's a buffer collision.

config.md, config/config_test.go, config/file_config.go, config/metadata/configMeta.yaml, tools/convert/Makefile, tools/convert/templates/configV2.tmpl
- Closes https://github.com/honeycombio/refinery/issues/726
- Adds the ability to disable config polling by setting `ConfigReloadInterval` to `0s`.
- Adds new test that confirms the feature is disabled.
- Generates new configs with updated description
=> feat: Allow disabling reload monitoring

.circleci/config.yml
- Closes https://github.com/honeycombio/refinery/issues/729
Based on the README I went with `convert` but I'm not committed to that name.
Example of binaries being built and moved to the correct directory: https://app.circleci.com/pipelines/github/honeycombio/refinery/1968/workflows/19a82e24-d0df-4605-92ac-77d86e86c628/jobs/5498
- Adds new build command for building the `convert` tool.
- Updates `build_binaries` to build the `convert` tool for all supported architectures and add the binaries to the artifacts directory.
=> ci: Update build_binaries to build convert

tools/convert/helpers.go, tools/convert/main.go, tools/convert/ruleconvert.go
- This gives the convert tool the ability to read config and rules out of a helm chart, convert them, and write them back to a helm chart. All comments are stripped. If that's not cool for you, you'll have to do it manually.
- Add helm command
- Load the helm chart as a map with YAML
- Extract config and run it through the config converter, then read that back into a map
- Extract rules and convert them
- Put both back into the map
- Write out the YAML again
=> feat: add ability to convert a helm chart

config/metadata/configMeta.yaml
This PR hopes to make the generated `config.yaml` file and associated documentation the best that it can be.
=> docs: Refinery Config copyediting

go.mod, go.sum
- The dynsampler-go library was updated to fix a bug in the EMAThroughput sampler. This bumps the dependency to pick up the fix.
- Update go.mod & run `go mod tidy`
Fixes #745
=> maint: Update dynsampler-go to latest to fix bug

go.mod, go.sum, service/debug/debug_service.go
- On long-lived services like Refinery with large process uptimes, the number of distinct stacks and code addresses grows in the profile as time goes on; this causes high numbers of bytes to be scraped when collecting profiles for timeseries that aren't increasing in value very often but have been seen at least once in process lifetime.
- Opts into https://github.com/grafana/godeltaprof for delta profiles which do not have the weakness above.
=> feat: enable pyroscope deltaprof

README.md
First in a ...series?... of rounds of PRs to get the README to be more accurate w.r.t. Refinery 2.0, modern use cases, and what it gives you.
=> maint: README updates -- round 1

tools/convert/README.md, tools/convert/main.go
- Convert readme was out of date and some tab/space conflicts were in the help text. This fixes that.
=> docs: Fix convert help and docs

README.md, config.md, config/cmdenv.go, config/config_test.go, config/metadata.go, config/metadata/configMeta.yaml, refinery_config.md, rules.md, tools/convert/templates/cfg_docrepo.tmpl, tools/convert/templates/cfg_docsite.tmpl, tools/convert/templates/configV2.tmpl
- Cleans up the documentation and code around environment variables and command line.
- Fix and add info about envvars and cmdlines in metadata
- Add the info to templates so they show up in the docs
- Regenerate all the things
Closes #727
=> docs: Fix up docs, especially envvar and cmdline

config/metadata/configMeta.yaml
This PR originally started as a result of customer feedback, which suggested updating the `APIKeys` description specifically to include the word "allowlist". Upon investigation, I realized `APIKeys` is no longer in use, but `ReceiveKeys` still is. I updated the config here, but please feel free to make further related changes.
- This PR updates two outdated `APIKeys` references in Refinery's config documentation to `ReceiveKeys`.
=> docs: Update APIKeys reference in config

config.md, refinery_config.md, tools/convert/templates/configV2.tmpl
- Recent PRs updated metadata; this regenerates the docs from that metadata.
=> docs: Regenerate docs from recent changes

config.md, config/metadata/configMeta.yaml, config/metadata/rulesMeta.yaml, refinery_config.md, refinery_rules.md, rules.md, tools/convert/templates/cfg_docsite.tmpl, tools/convert/templates/configV2.tmpl, tools/convert/templates/rules_docsite.tmpl
**Please do not merge until @kentquirk is able to advise and re-generate the Refinery docs. Thank you!**
This PR fixes noticed issues and adds improvements to the generated Refinery docs.
Improvements include:
- refer to double `LegacyMetrics` example: https://github.com/honeycombio/refinery/blob/main/refinery_config.md#legacy-metrics 
- refer to example in:  https://github.com/honeycombio/refinery/blob/main/refinery_rules.md#name-deterministicsampler
=> docs: Generated Refinery docs for docs site improvements

route/middleware.go, route/middleware_test.go
- The QueryAuthToken auth middleware had a bug where it would return an error and ALSO return the requested result even when auth failed.
- Add a missing return statement.
- Write several tests that would have caught the missing return statement and a bunch of other possible issues.
=> fix: Query auth bug fix; add tests

go.mod, go.sum, transmit/transmit.go
Fixes #749 by using https://github.com/honeycombio/libhoney-go/pull/228 new method
=> perf: preallocate outbound libhoney attribute map

config/level.go
- closes https://github.com/honeycombio/refinery/pull/769
- Moves `Unknown` log level to the 0 position. This is necessary to ensure that https://github.com/honeycombio/refinery/blob/5c30fbf2e2d3a2cd673fd9414f09c7537fe2a505/config/configLoadHelpers.go#L175 doesn't view `Debug` log level as a zero value and overwrite it with `warn`.
=> fix: Move Unknown log level to zero position

config.md, config/config_test.go, config/file_config.go, config/metadata/configMeta.yaml, refinery_config.md, rules.md, tools/convert/templates/configV2.tmpl
- https://github.com/honeycombio/refinery/issues/773
- Updates `MemorySize.UnmarshalText` to be able to handle k8s memory format.
- Add unit tests
=> fix: Add ability to handle k8s unit format

cmd/refinery/main.go, metrics/metrics.go, metrics/multi_metrics.go, metrics/multi_metrics_test.go
- We had missing metrics because the metrics objects that were loaded from config were not being Start()ed.
- Rework MultiMetrics to inject all the internal implementations even if they're not being used.
- On Start(), copy the enabled ones to the children list so that the rest of metrics works right.
- Remove the previous attempt to avoid doing this.
- Also inject All The Things into a test that needs injection.
Fixes #776.
=> fix: Inject all metrics and config later

RELEASING.md, config.md, config/metadata/configMeta.yaml, refinery_config.md, tools/convert/templates/configV2.tmpl
- Peer management default was documented as `redis` but it can't be, because then a single-node cluster won't work right.
- Change default in metadata
- Regenerate the appropriate files
=> fix: The peer management default value was wrong.

collect/stressRelief.go
- Stress relief activation notices were using Info, but they're more important than that and should be rare.
- Promote them to Warn.
Fixes #777.
=> fix: Promote stress relief activation and deactivation logs to warn

config.md, config/metadata/configMeta.yaml, refinery_config.md, tools/convert/templates/configV2.tmpl
- Docs had the right description in the wrong place, and the wrong description in the right place.
- Convert two wrongs to a right.
- Regenerate the wrongness.
=> docs: Update docs to fix memory description

config/metadata/configMeta.yaml
- API key validation was not allowing envvars to be properly validated, so we're removing it.
- Rip it out.
=> fix: Remove excess validation for api keys

config.md, config/metadata/configMeta.yaml, refinery_config.md, tools/convert/templates/cfg_docrepo.tmpl, tools/convert/templates/cfg_docsite.tmpl
This PR includes some improvements for generated documentation for Honeycomb docs site to match style guide standards. For example, "etc." is an abbreviation of a Latin expression - and the Honeycomb docs use American English only - but at the very least should have a period included when used.
This PR should also include a comma between generated options, but I will need @kentquirk's help with wrangling that.
For example, the options for https://docs.honeycomb.io/manage-data-volume/refinery/configuration/#type should have commas between them to improve clarity.
- Refer to above
=> docs: General Improvements

.circleci/config.yml, build-docker.sh
#790 
-
- For internal dev builds, the version will be the build # from circle. They will also be tagged with this build number
- The tags for dev builds will include `branch-branchname` such as `branch-terra.myawesomebranch`
- For internal dev builds for `main` will be tagged with latest
- For releases, we will tag with `major`, `major.minor`, and `semver` in addition to `latest` (for compatibility) such as `2`, `2.1`, and `2.1.5`
- All dev builds will now be available in our ECR repo, I will separately add a lifecycle policy to it so it only keeps so many days of non-release builds (90 maybe?)
=> maint: Docker tagging updates

cmd/refinery/main.go
- Fixes #792 
- Instead of injecting metrics objects that aren't used, inject null objects for anything that's not enabled.
=> fix: Don't inject real metrics if they're not enabled.

build-docker.sh
- the build-docker.sh script has started including the branch name as a tag, but that breaks CI if the branch name includes a slash (`/`), which are not allowed in tags
- Unable to run CI against external PRs
- Updated the script to replace `/` with `-` in branch names.
=> maint: replace slash with dash in branch name

.circleci/config.yml
- external PRs try to publish to ecr but fail because they dont have the secret
- updated ecr publishing to exclude external PRs
=> maint: Dont try to publish external PRs to ECR

internal/redimem/redimem.go
This week, we've bumped up our number of refinery pods from 250 to 300. After that change, we've noticed a lot more timeouts from redis.
```
time="2023-07-13T17:49:28Z" level=error msg="redis scan encountered an error" err="redis scan timeout" keys_returned=92 timeoutSec=5s
time="2023-07-13T18:39:41Z" level=error msg="get members failed during watch" error="context deadline exceeded" name="http://host:8081/" oldPeers="[list_of_the_300_hosts:8081]" timeout=5s
```
After digging into some of the code, we've noticed that peers are stored in redis and are retrieved in batches of 10. Because there are 300 nodes, each node is making 30 requests to redis to get all the peers, and doing it twice, so 60 total. This is done every 5 seconds. So our redis instance is handling 18000 requests every 5 …
=> fix: Redis scan batch size increase

collect/stressRelief.go
- Currently we don't emit the values we used to determine if stress relief should be activated unless you enable debug logging, but I think the numbers at the time of activation are valuable enough to be present at `WARN`
- adds a `stress_formula` field to the activation message, and adds `formula` to the `StressRelief` struct
=> feat: add a field with the formula used to decide to activate stress relief

config.md, config/metadata/configMeta.yaml, config/validate.go, config/validate_test.go
Fixes https://github.com/honeycombio/refinery/issues/803 by ensuring that only both `AvailableMemory` and `MaxAlloc` cannot be set at the same. `MaxMemoryPercentage` may still be set regardless as it has a default value defined. 
While making this changes I noticed that when only `AvailableMemory` was defined I ran into a validation `requireWith` error. The validation only fails on the first pass before defaults are loaded in from the config struct. If the failure is intentional then we probably should remove the default -- only breaking change I could see is if someone was running with validations turned off explicitly. 
```bash
$ docker-compose up
[+] Running 1/0
✔ Container refinery-refinery-1  Recreated                                                                   0.0s
Attaching …
```
=> feat: Validate Collection memory config through adding `conflictsWith` validation

config.md, config/metadata/configMeta.yaml, refinery_config.md
- This is fixing the source for the [Docs PR here](https://github.com/honeycombio/docs/pull/1852) which correctly documents the proper value for the environment variable. 
- Change the source
- Regenerate docs
This does NOT require updating the docs site -- the site already has these changes.
=> fix: Update metadata for bad envvar and regenerate

collect/collect.go, metrics/otel_metrics.go
- Fixes #801. OTelMetrics was missing some fields that were present in LegacyMetrics. This adds them.
- Adds new sample rate metrics
- Add mechanism that adds the dynamic fields to otel.
- Add some histograms for aggregate sample rate and kept sample rate.
=> fix: add missing metrics fields

config/sampler_config.go, config/sampler_config_test.go, sample/rules.go, sample/rules_test.go
- This was intended to be purely a refactoring to pull out constant values
- But it uncovered a bug -- we had a switch where we weren't checking the ">=" case!
- Constantize all the things
- Add the missing switch case
- Write some tests (not exhaustive but try to prove all the major spots work)
- Fix the boolean bug that was also uncovered by the tests
=> maint: convert hardcoded operators to constants

.circleci/config.yml, config/config_test.go, config/metadata/rulesMeta.yaml, config/sampler_config.go, rules_complete.yaml, sample/rules.go, sample/rules_test.go
Dependent on #813; that should be merged before this one.
- Fixes #610 
- Adds a new rule operator, `has-root-span`, that evaluates to a boolean based on whether the root span for the trace has arrived when the rules are evaluated. 
- Add tests for it
- Update metadata (but does not regenerate the docs yet; that will come before the release)
=> feat: Add `has-root-span` operator to rules

config.md, config/metadata/rulesMeta.yaml, refinery_config.md, refinery_rules.md, rules.md, tools/convert/templates/configV2.tmpl, tools/convert/templates/rules_docrepo.tmpl, tools/convert/templates/rules_docsite.tmpl
- Documentation updates
- This PR just adds a link to the `rules_complete.yaml` file since that file can be helpful in understanding what a full rules yaml file might look like, and adds the list of valid values for `Datatype`'
Fixes #804
=> docs: refinery_rules.md

config.md, config/file_config.go, config/metadata/configMeta.yaml, refinery_config.md, refinery_rules.md, rules.md, tools/convert/templates/configV2.tmpl
- The default config reload interval was too long, and the documentation for it was wrong.
- Change default for config reload to 15s from 5m. The original intent (see #725) was to have a fleet of refineries gossiping news of new configs, but that's tricky to get right and probably not needed, especially since for now at least, almost all installations will be using a config file, not a config url. 
- Add a random jitter to avoid thundering herds. 
- Update metadata to explain what it's really doing
- Regenerate documentation.
=> fix: Change default ConfigReloadInterval, add jitter, fix docs

collect/collect.go, config.md, config/metadata/configMeta.yaml, refinery_config.md, tools/convert/templates/configV2.tmpl
- #281 is a longstanding issue; this fixes it.
- Record the name of the metric we increment on trace decisions in a meta field, only when `AddRuleReasonToTrace` is specified.
- Update docs
- Regen docs
=> feat: Record why a trace was sent

.circleci/config.yml
- Add darwin-arm to the list of built binaries for convert and for refinery. Fixes #824.
- Adjust circle build script
=> feat: Add darwin-arm64 to the list of binaries.

.circleci/config.yml, go.mod
- Go 1.20 was released in February; we've been using it for development with no problems. There's no reason not to upgrade.
- Bump builds and go.mod to 1.20.
=> maint: use Go v1.20

README.md
Some edits to clean up the readme which hadn't been touched in a while. 
There's still more that could be done, but I think this is quite a bit better.
Closes #560.
=> docs: Touch up readme.

.circleci/config.yml
- While the Dockerfile builds with CGO_ENABLED=0, the .circleci/config.yml file left it unspecified, causing builds made for the same GOOS & GOARCH as the builder (linux/amd64 by default) to use CGO by accident since [a matching C toolchain is present](https://pkg.go.dev/cmd/cgo#:~:text=any%20other%20version.-,The%20cgo%20tool%20is,0%20to%20disable%20it.,-The%20go%20tool) in the cimg/go convenience image.
```
root@182da09223e8:/# file /r2/refinery-linux-amd64
/r2/refinery-linux-amd64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=Hw78705HCrBK7Q8pUdVk/sdhqsE46-B48P0Cvx0qG/X_WRhP-ApFipSmIba6pM/l4KJK8EedZWWVdz6GgZq, with debug_info, not stripped
root@182da09223e8:/# file /r2/refinery-linux-arm64 …
```
=> fix: [build] disable cgo for binary-only deploys

config/cmdenv.go, config/config_test.go, config/file_config.go
- #857 
- Change AvailableMemory in cmdenv to be type MemorySize
- Implement flags.Unmarshaler so the flags system uses it
- Add a test to make sure it works
Fixes #857
=> fix: Fix AvailableMemory parsing on the cmd line

config.md, config/config.go, config/config_test.go, config/file_config.go, config/metadata/configMeta.yaml, config/mock.go, config_complete.yaml, logger/logrus.go, refinery_config.md, rules.md, tools/convert/templates/configV2.tmpl
#842
Currently, the structured logging is not working as expected when using stdout logger. 
This PR makes sure the `StdoutLogger.Structured` is applied to the logger implementation. If it's set to true, the logger will use JSON formatter. Otherwise, it's default to using plain text.
=> fix: [config]: fix structured logging

logger/honeycomb.go
Previously, Honeycomb logger uses the entire log message as the sampling key. If a log message contains high-cardinality fields, the throttle mechanism will no longer work.
This PR changes the key used for sampling from the entire log message to only use the format string
=> fix: change sample key to not include args in honeycomb logger

config.md, config/config_test.go, config/file_config.go, config/metadata/configMeta.yaml, logger/logrus.go, refinery_config.md, rules.md, tools/convert/templates/configV2.tmpl
#705 
This PR implements the same sampling logic from HoneycombLogger in the StdoutLogger.
=> feat: enable sampling for stdout logger

logger/honeycomb.go, metrics/legacy.go
- #847
This PR adds `refinery_version` to both legacy metrics and honeycomb logger.
Example of the newly added field:
=> fix: add refinery version to refinery metric and log

refinery.service
- #873
This PR removes the old config and rules argument from the service file for systemd. This should make sure that the default config and rules files are correctly loaded
=> fix: load default config and rules file in service file

cmd/refinery/main.go, go.mod, go.sum
- golang.org/x/exp updated with breaking changes; this adapts to those
- Update dep
- Fix sorting in main()
=> maint: update dependency for x/exp

RELEASING.md
This just adds some text to the RELEASING file so we don't forget these tasks.
=> chore: Add some detail about release tasks

.circleci/config.yml
- We're pulling Refinery images from dockerhub and our Twistlock infrastructure has identified the image as vulnerable since it builds with go 1.19. This updates the build target from go 1.19 to go 1.20, to resolve the positive scans.
- Update `build_docker` and `publish_docker_to_dockerhub` stages to `go:1.20` to match the other build stages.
=> maint: update circleci config to build docker images with go 1.20

config.md, config/config.go, config/config_test.go, config/file_config.go, config/metadata/configMeta.yaml, config/mock.go, config/validate.go, refinery_config.md, route/route.go, tools/convert/templates/configV2.tmpl
- #825 
This PR adds a new config option `HTTPIdleTimeout` for users to control refinery's http server's idle timeout setting.
I also found and fixed an issue in the `minOrZero` validation logic that prevents users to actually set a field as 0
fix #825
=> feat(config): expose IdleTimeout for http.Server

config/metadata/configMeta.yaml
- #841 
This PR fixes the description in the config's metadata to correctly reference `MaxMemoryPercentage`.
I didn't run doc-gen since we will run it all at once before a release. This should make the PR review process much easier
=> fix(config/metadata): fix reference in description for MaxMemoryPercentage

CONTRIBUTING.md, RELEASING.md, tools/convert/Makefile, tools/convert/README.md
- #883 
This PR adds more details on the release process and config/rules convert tool workflow.
It also fixes a mistake in the `CONTRIBUTING.md` doc regarding the config/rules doc update process
=> maint: update doc for release process and config/rules doc generation process

.circleci/config.yml, .gitignore, Makefile
Currently, test results in Circle CI is displayed in raw text format like below.
When there're failed tests, it's hard to tell which tests failed without scrolling through the giant test output in circle ci.
This PR utilizes the [`store_test_results`](https://circleci.com/docs/collect-test-data/#introduction ) feature in Circle CI to  have a better UI for finding failed test cases.
Circle CI accepts test results in junit xml file format and has `gotestsum` support builtin in it's image. This PR changes the `Makefile` to run go test using `gotestsum` when `gotestsum` is available.
Here's an example of the new test result output in Circle CI https://app.circleci.com/pipelines/github/honeycombio/refinery/2431/workflows/e8f89378-18f0-454a-bfe5-600d67a85d56/jobs/7065/steps
=> maint: upload test result to circle ci 

Makefile
While `which` is commonly present on systems, `which` is usually a standalone executable. `command` is built-in to POSIX shells.
- `command` is even more likely to be present than the very-likely `which`
- `command` avoids spawning a subprocess to check for the presence of a command
=> maint: use command to check for other commands

config/metadata/rulesMeta.yaml, config/sampler_config.go, sample/rules.go, sample/rules_test.go
- Adds a regular expression `matches` operator to rules which should make some rules easier to write, especially when dealing with URLs or complex string fields.
- Add `matches` operator
- Remove some unused switch cases from `conditionMatchesOperator` (to avoid implementing another one)
- Add tests for it
This is part of #822.
This one will need further documentation, but that will be addressed in a separate PR.
=> feat: Add `matches` operator to rules

app/app_test.go
Since sending a trace is an asynchronous operation, there's a race condition between the writes from libhoney to the transmission buffer and the reads issued from our tests into the buffer. 
This PR changes tests to use `transmission.MockSender` instead. The mock sender uses a slice instead of an io.Writer as the buffer. This allows us to avoid race condition between reads and writes.
I also added a wait after sending the roundtrip request to make sure Refinery has a chance to flush its in-memory trace cache before we try to validate the sent trace.
=> maint: attempt to fix flaky integration tests

config/config_test.go, config/metadata/rulesMeta.yaml, config/sampler_config.go, config_complete.yaml, rules.md, rules_complete.yaml, sample/rules.go, sample/rules_test.go, tools/convert/Makefile
This adds a new option for Rules -- instead of specifying `Field` which is a single field name, it's now possible to specify `Fields`, which takes an array of field names. The evaluator iterates over each field in turn and returns the first field that exists in the incoming span. 
This will allow users to write rules that account for field name changes like the upcoming http semantic convention changes.
- Add new Fields element to rules data structure
- Validate that both Field and Fields do not exist, both in the loading code as well as the validator
- Modify Init() so that it copies Field to Fields so that the evaluation code is clean
- Modify evaluation code
- Write some tests
- Fix some old tests that didn't call Init()
- Document this in metadata
- Add examples to rules_complete
- …
=> feat: Add Fields option for rules

config/sampler_config.go, sample/rules.go, sample/rules_test.go
Metadata about a trace is added only to root spans. However, it's useful to make sampling decisions before root span arrives. In this PR, I addressed a specific use case described in [this issue](#646 )
This PR adds a new concept called `ComputedField` in rule based sampler. A `ComputedField` is a virtual field that's generated during rule evaluation for a trace. The virtual field isn't actually defined on a span. 
After some discussion with Kent, we decided to use `?.` as the prefix for computed field so that it shouldn't collide with any regular field names.
This PR doesn't include documentation. I will address it in [this PR for all rules related documentation](https://github.com/honeycombio/refinery/pull/951/files).
=> feat: use a computed field for current descendant count in rules

config/metadata/configMeta.yaml, refinery_rules.md
- Updates metadata to specify `firstversion` tags for config parameters introduced in 2.2. 
- Add firstversion tags for 2.2 items
- Regenerate rules doc
Closes #918.
=> chore: Update `firstversion` for 2.2 

config/config_test.go, config/file_config.go, config/sampler_config.go
To reduce the amount of across AZ zone data within a Refinery cluster, we came up with an idea to only store information needed for making a sampling decision in a central store. In order to extract those information from a span, we need to have a list of fields used in sampler configs.
This PR adds the code to generate the list mentioned above both during Refinery startup and config reload by adding the generating code in the `newFileConfig` function.
***Attention***
This PR is not merging into the current `main` branch. We are using a feature branch for the dynamic scaling work
=> feat: Extract unique field names from sampler configs

config/config_test.go, config/file_config.go, logger/honeycomb.go, logger/logger_test.go, rules.json
- #954 
- add a failing test to reproduce the problem
- updated config struct fields that are bools defaulting to true to be bool pointers so that nil represents the unset state
- updated getter functions to handle the pointers
=> fix: allow config bools to default to true

config/file_config.go, config/sampler_config.go
NOTE -- this is against the `feat_dynamic_scaling` branch.
- Finishes using `generic.Set` everywhere we can
- Convert to Set in sampler_config.go
- Rename SetUniqueSamplingFields to ExtractUniqueSamplingFields because Set implies that it takes a parameter.
=> maint: finish conversion to generics.Set

Makefile
[go-licenses v1.1.0 dropped support for packages that aren't Go modules](https://github.com/google/go-licenses/releases/tag/v1.1.0). That or any later version run against our current repo state will result in many dozens of this error:
> Package •thingie• does not have module info. Non go modules projects are no longer supported. For feedback, refer to https://github.com/google/go-licenses/issues/128.
Pinning our install to v1.0.0 seems to produce the LICENSES output consistent with what the project has been tracking so far.
=> chore: fix license tracking

Makefile
This reverts commit 52c5f084bb7e961de431c410ae2a1686ea023a79.
The go-licenses@v1.0.0 pin breaks when run in CI. Needs further investigation.
=> chore: Revert "chore: fix license tracking (#989)"

collect/collect_test.go
- [a flaky test](https://app.circleci.com/pipelines/github/honeycombio/refinery/2623/workflows/95075937-b4b3-472e-8d34-a9e2a7e9ba31/jobs/7681/tests#failed-test-0)
- drop the assumption that only 2 spans are sent to transmission: don't inspect the second event on the transmission queue, inspect the last event
=> fix: flaky TestOriginalSampleRateIsNotedInMetaField

config/metadata/rulesMeta.yaml, refinery_rules.md, rules.md
Updates refinery rules metadata to include the default intervals for each of the sampler types. `rulesmeta.md` was updated manually and the other files were re-generated using the conver tool.
- Closes #992 
- Update each sampler to include the default interval
- [DynamicSampler](https://github.com/honeycombio/dynsampler-go/blob/main/avgsamplerate.go#L30) & [TotalThroughputSampler](https://github.com/honeycombio/dynsampler-go/blob/main/totalthroughput.go#L31) -> 30s
- [EMADynamicSampler](https://github.com/honeycombio/dynsampler-go/blob/main/emasamplerate.go#L41) & [EMAThroughputSampler](https://github.com/honeycombio/dynsampler-go/blob/main/emathroughput.go#L38) -> 15s
- [WindowedThroughputSampler](https://github.com/honeycombio/dynsampler-go/blob/main/windowedthroughput.go#L34) -> 1s
=> docs: Add sampler default intervals to docs

config.md, config/metadata/rulesMeta.yaml, config_complete.yaml, refinery_config.md, refinery_rules.md, rules.md, sample/rules.go, sample/rules_test.go, tools/convert/configDataNames.txt, tools/convert/minimal_config.yaml, tools/convert/templates/configV2.tmpl
- Handle case where `root.` prefix is used but a root span is not present for the trace at the time a sampling decision is being made, for example: a late-arriving root span.
- Check for root span when trying to use `root.` prefix; document current behavior when root span is not present on trace
=> fix: handle root prefix when no root span on trace

sample/rules.go
Small typo in the sample wording when reviewing #1006 (but it had already been merged).
Moves one word into the correct place.
=> fix: Fix a typo from PR #1006

CHANGELOG.md, RELEASE_NOTES.md, RELEASING.md, config.md, config/metadata/rulesMeta.yaml, config_complete.yaml, refinery_rules.md, rules.md, tools/convert/configDataNames.txt, tools/convert/minimal_config.yaml, tools/convert/templates/configV2.tmpl
- Releasing 2.4.1 into the wild!
- generate doc updates
- update changelog and release notes
- update RELEASING: add release sub-categories (Features, Fixes, etc) at H3 because release version section header is at H2
=> rel: prepare v2.4.1

centralstore/redis_store.go, centralstore/redis_store_test.go, centralstore/smartwrapper_test.go, cmd/test_stores/main.go, internal/redis/redis.go
- Keep state
- this PR makes sure that the keep decision is stored as part of the state transition for a given trace
- It also adds logic to remove spans information for a given trace when a decision is made
- Timestamp
- we nee record the current time whenever a state change happens.
- the precision used before is not sufficient to determine the order of state change events
- this PR changes the timestamp precision from second to nanosecond
- Modified `KeepTrace`
- return traceIDs that has successfully changed their states from `toNextState` function
- added more tests
=> feat: properly handle keep state and timestamp for state transition

app/app_test.go, route/errors.go, route/middleware.go, route/otlp_trace.go, route/otlp_trace_test.go, route/route.go
Refinery was not returning the correct OTLP payload and not always using the correct `Content-Type` in the response.
- closes https://github.com/honeycombio/refinery/issues/1008
This PR attempts to fix the OTLP response while leaving other protocols unaffected.
- Creates a new error handler method for the OTLP endpoint
- Ensures a `ExportTraceServiceResponse` object is returned for success and a grpc `Status` object is used for failure.
- Changes the "bad API key" response code from 400 to 401.
=> fix: Fix OTLP http responses

cmd/test_stores/fake_refinery.go, cmd/test_stores/main.go, cmd/test_stores/otel_tracing.go
This PR enables the simulator to be able to run with a redis backend 
- added opts.HnyEndpoint to enable sending traces to other honeycomb environments
- redis returns the status field as `float64`. Handle that scenario in the decider logic.
=> feat: run simulator with redis backend

go.mod, go.sum, route/errors.go, route/otlp_trace.go, route/otlp_trace_test.go
Updates Husky to v0.25.1 which includes fixes handling invalid content types for OTLP requests.
See the following PR for changes:
- https://github.com/honeycombio/husky/pull/243
**NOTE**: This PR is based on an unreleased version of husky. We'll wait for husky to be released before merging this fix.
- Updating Husky to 0.25.1
- Updating the error handler to use husky to write a text/plain response for invalid content type errors
- Move validation of API keys from config after request headers check
=> maint: Update Husky to handle invalid content type errors

.circleci/config.yml, centralstore/centralstore.go, centralstore/localremotestore.go, centralstore/redis_store.go, centralstore/redis_store_test.go, centralstore/smartwrapper_test.go, internal/redis/redis.go
Before this PR, decisions made for traces were not stored in redis. It also wasn't part of the state machine when transition a trace from awaiting for decision to either decision keep or drop.
- Introduced DecisionDrop and DecisionKeep into the state machine
- check against in-memory cache before fetching from Redis for trace status
- run smartwrapper tests against redis in the ci
- removed some unnecessary code
=> fix: make sure decision keep and drop is persisted in redis

.github/dependabot.yml
Reduce the number of dependabot PRs by grouping them.
- groups minor and patch updates into a single PR
=> maint: group minor/patch dep updates

centralstore/redis_store.go, centralstore/redis_store_test.go, internal/redis/redis.go
Perviously, each trace state change needs to make a redis call. When client can't take advantage of parallelism since each call is serialized in redis store anyway. This PR makes it possible to process multiple traces in one redis call for state change.
**Before**
**After**
- Processing state transitions in a batch instead of one trace per redis call
=> feat: process state transitions in batches

go.mod, go.sum, types/event.go
We've now released Ingest Keys, but in order for them to work with Classic environments properly we need to update the key detection logic.
- upgrades husky to 0.26.0
- updates `types.IsLegacyAPIKey` to use `(husky.otlp).IsClassicApiKey`
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206669928018696
=> feat: support Classic Ingest Keys

config.md, tools/convert/templates/cfg_docrepo.tmpl
- #1009 
- Add a condition to the generator for the config docs.
=> fix: `defaulttrue` now shows up in docs as `bool`

config.md, config/metadata/configMeta.yaml, config/validate_test.go, config_complete.yaml, refinery_config.md, tools/convert/minimal_config.yaml, tools/convert/templates/configV2.tmpl
we are using `url.Parse` for peer address list.  `host:port` is not a valid url.
- Change validation type for `PeerManagement.Peers` to `url` instead of `hostport`
- After this change, the convert tool will always convert `host:port` to `http://host:port`
fix: #1044
=> fix: change validation type for PeerManagement.Peers to be url

sample/rules.go
- When a user puts a Drop rule in a rules file, there's no separate metric that distinguishes that from a drop because of other sampling. See #974 for details.
- Adds a new metric, `num_dropped_by_drop_rule`, which tracks this value.
Fixes #974
=> feat: new metric for drops caused by rules

metrics/legacy.go, metrics/multi_metrics.go, metrics/otel_metrics.go, metrics/prometheus.go
- During startup, refinery sometimes panics. One of them was tracked down to concurrent read/write of a map in otel metrics, but the problem was a bit bigger -- some assumptions about how startup worked that weren't true, and required extra locking.
- Add locks to several metrics-related functions in different types of metrics
- Remove now-unneeded rlock inside one of the new locks.
=> fix: deal with locking issues at startup

cmd/refinery/main.go, cmd/test_stores/main.go, config.md, config/cmdenv.go, config/config.go, config/configLoadHelpers.go, config/file_config.go, config/metadata/configMeta.yaml, config/mock.go, config_complete.yaml, internal/otelutil/otel_tracing.go, refinery_config.md, rules.md, tools/convert/configDataNames.txt, tools/convert/minimal_config.yaml, tools/convert/templates/configV2.tmpl
To properly inject tracing, we needed the config, so this moves the tracing config to the config area, sets up the metadata for it, generates all the docs, and uses it. It also sets up injection of the centralStore and the basicStore, making it possible to use them in Refinery.
=> maint: Move Tracing config to config and do all the things

centralstore/centralstore.go, centralstore/localremotestore.go, centralstore/redis_store.go, centralstore/redis_store_test.go, centralstore/smartwrapper.go, centralstore/smartwrapper_test.go, internal/redis/redis.go, internal/redis/redis_test.go, internal/redis/test_harness.go, metrics/mock.go
Providing metrics for measuring contention on redis operations
- Return connection pool stats from redis store
- use prefix for different metrics group
=> feat: add redis connection pool stats in GetMetrics

config.md, config/metadata/configMeta.yaml, config_complete.yaml, refinery_config.md, tools/convert/configDataNames.txt, tools/convert/minimal_config.yaml, tools/convert/templates/configV2.tmpl
Allow getting span ids from each event sent to refinery
Add a new config option for specifying span ID field name
=> feat: add SpanNames config for getting SpanNames

collect/cache/cuckoo_test.go, collect/cache/span_cache.go, collect/cache/span_cache_basic.go, collect/cache/span_cache_complex.go, collect/cache/span_cache_test.go
This contains two implementations of a span cache; `basic` is basically just a map of traceID to trace. The second, `complex`, trades off complexity and slightly slower performance for an implementation that tries to avoid allocating memory most of the time. This may prove valuable in a very high-throughput environment, but today I can't prove it -- in all the benchmarks I've written, the *only* advantage is low-allocation. So we have both implementations and we can play with them in a working refinery.
One thing that I tried was to avoid the big sort in GetOldest; I implemented an attempt to use a tdigest to find the threshold so that I could avoid the sort, but the tdigest was more expensive than sorting, even with 1 million items in the list, so I've abandoned that approach. Sorting a …
=> feat: implement span cache

centralstore/redis_metrics_recorder.go, metrics/multi_metrics.go
This is the Refinery side of recording metrics to a central place in Redis so that we can make it available for autoscaling.
This will be followed up with the central metrics reporting app.
- We want to record metrics centrally so we can scale with them.
- Add GetAll to the MultiMetrics object so that we can fetch and send them all at once
- Send them to Redis with an expiration time so that they'll clean themselves up
- Use the hostname if it exists, otherwise the time, as a differentiator
=> feat: RedisMetricsRecorder

collect/cache/span_cache_basic.go, collect/cache/span_cache_complex.go, collect/central_collector.go, collect/collect.go, config/config.go, config/config_test.go, config/file_config.go, config/metadata/configMeta.yaml, config/mock.go, internal/peer/file.go, internal/peer/peers.go, internal/peer/redis.go, internal/redis/redis.go, logger/honeycomb.go, logger/logger.go, logger/logrus.go, route/otlp_trace.go, route/proxy.go, route/route.go, service/debug/debug_service.go, sharder/deterministic.go, transmit/transmit.go
- Since we introduced validation of configs, it's not really possible for there to be errors returned from the config getter functions. Most of them returned nil, or did pointless validation checks in the new regime.
- Remove error from most return signatures for config getters
- Fix up all the normal getters
- Fix the mocks (and remove all the useless error mock values that weren't being checked anyway!)
- Fix all the places things were used
=> maint: Remove error return from (almost) all the get functions in config

app/app_test.go, centralstore/smartwrapper_record_metrics_test.go, centralstore/smartwrapper_test.go, collect/central_collector.go, collect/central_collector_test.go, collect/cycler.go, collect/panic_handler.go, test1.log
Since processor and decider run concurrently, it's hard to manage the timing in tests. 
#1082 
- implement a Cycle object to manage the goroutine so we can pause or restart it
- modify tests to use the new Cycle management interface
=> fix: make central collector tests more reliable

app/app_test.go, centralstore/centralstore.go, centralstore/localremotestore.go, centralstore/redis_store.go, centralstore/redis_store_test.go, centralstore/smartwrapper.go, cmd/test_stores/tracegen.go, collect/cache/cuckooSentCache.go, collect/central_collector.go, collect/central_collector_test.go, collect/cycler.go, config/file_config.go, types/event.go, types/event_test.go
Drain in-flight spans during refinery shutdown
#1041
- Run `process()` to monitor trace decisions for in-flight traces
- Stop accepting new spans immediately after receive shutdown signal
- Send remaining spans without a decision to central store
- consolidate `SpanType` constant
=> feat: implement graceful shutdown for central store

collect/central_collector.go, collect/central_collector_test.go
We shouldn't exit on the first error returned from processor or decider since that can happen when redis is upgrading or in the process of leader election if redis is in cluster mode.
- added a `isTest` flag to make sure we can still catch the error in tests
=> fix: do not exit from the processor and decider loop on first error

app/app_test.go, centralstore/centralstore.go, centralstore/smartwrapper.go, centralstore/smartwrapper_test.go, collect/cache/span_cache_basic.go, collect/cache/span_cache_complex.go, collect/central_collector.go, collect/central_collector_test.go, collect/stressRelief.go, config/file_config.go, route/route.go
Record central store metrics on an interval so we have metrics ready for stress level calculation
- added metrics for smart wrapper, central collectors
- added metrics cycle to run `RecordMetrics` in an interval
- add span counts to all spans' metadata instead of only on root span
- removed unnecessary code
- inject StressRelief to central collector
=> feat: record metrics on an interval in central store

internal/gossip/gossip.go, internal/gossip/gossip_redis.go, internal/gossip/gossip_redis_test.go, redis/redis.go, redis/test_harness.go
When using Refinery with Redis, we need to let each Refinery in a cluster know about each other's stress level and config changes. This PR implements the communication protocol for such use case
- Define a `Gossiper` interface
- Implement the `Gossiper` interface using Redis pub/sub
=> feat: implement Gossiper interface

collect/central_collector.go
If a trace is kept, we want to persist the reason in `KeepReason` field
- set keep reason during making decision
- retrieve reason from `KeepReason` before sending a trace
=> fix: persist keep reason to central store

centralstore/centralstore.go, centralstore/local_store.go, centralstore/redis_store.go, centralstore/redis_store_test.go, centralstore/smartwrapper.go, centralstore/smartwrapper_record_metrics_test.go, centralstore/smartwrapper_test.go, cmd/test_stores/fake_refinery.go, collect/central_collector.go, collect/central_collector_test.go, config/file_config.go
- Addresses some performance issues with talking to Redis. Before these changes, some calls to GetStatusForTraces were taking 800ms when called with 5000 traceIDs. With this, 13000 traceIDs takes a little more than 100ms. I'm also seeing Refinery lasting quite a bit longer under heavy loads, although it still has problems; I have more ideas but I'd like to see this, plus #1108 and #1109 land first.
- This doesn't solve all performance issues, but it definitely helps. See me for links to HC queries that show it.
- GetStatusForTraces now takes a list of the statuses it cares about, and only returns traces that have those values. This signature change needed to be made in all the CentralStore interfaces, and implemented in both redis and local stores.
- getTraceStatuses (which is called by …
=> feat: performance tweaks

app/app_test.go, centralstore/redis_store.go, centralstore/redis_store_test.go, centralstore/smartwrapper.go, centralstore/smartwrapper_test.go, collect/cache/span_cache_basic.go, collect/cache/span_cache_test.go, collect/central_collector.go, collect/central_collector_test.go, config/file_config.go, config/metadata/configMeta.yaml, metrics/legacy.go, metrics/metrics.go, metrics/otel_metrics.go, metrics/prometheus.go
Along the route to tuning performance, this:
- Renames Pause->Cycle in a couple config values, as Pause was inaccurate
- Updates the Count function in metrics to work with updowns as well as counters, so that we can count up/down by more than 1
- Adds some metrics to the spanstore as well as to the redis store
- Uses config to define the number of goroutines used to talk to redis in a chatty subroutine
=> feat: Performance tuning, more telemetry

collect/cache/cuckoo.go, collect/cache/cuckooSentCache.go
In order to record metrics about dropped traces in cuckoo cache, we need to access the cuckoofilter object periodically in a goroutine. Since cuckoofilter itself is not concurrent safe, we need to add locks around accessing it.
Add mutex when accessing cuckoofilter for current count and load factor
=> fix: prevent data race when retrieve information about cuckoo cache

centralstore/redis_store.go, centralstore/redis_store_test.go, generics/fanout.go, generics/fanout_test.go
I had written a fanout/fanin system to improve the speed of talking to redis. It was pretty complex. I realized I could genericize it and
- make it easier to understand by separating the technique from the details of the work
- probably reuse it elsewhere if it stood alone
- Create Fanout, FanoutToMap, EasyFanout, and EasyFanoutToMap functions
- Write some tests
- Use FanoutToMap in getTraceStatuses
=> feat: generic fanout function, used in place of existing fanout mess

collect/central_collector.go
- Record how fast the decider and the sender are actually operating
- for each invocation of the decider and sender, record histograms of the number of traces actually considered (and for the decider, actually handled)
=> feat: record decision and send rates

collect/central_collector.go, collect/stressRelief/stress_relief_redis.go, config/metadata/configMeta.yaml
Logs that includes trace ids in its message body is noisy.
We are also missing stress activation metric
- move trace/span IDs to log fields
- add stress_relief_activated metric
=> fix: clean up metrics and logs

route/route.go
once we find a valid parent id field, we should stop and recognize the span is a root span
- break the loop once `isRoot` is true
=> fix: break once we find parent ID field on a span

route/route.go
- Traces were making weird decisions because we were marking root spans backwards.
- Invert the test so we're marking the root span properly.
=> fix: Root span test was inverted!

centralstore/redis_store.go, centralstore/redis_store_test.go, collect/central_collector.go, config/config.go, config/file_config.go, config/metadata/configMeta.yaml, config/mock.go
Through testing, we realized that getting metrics from redis causes network usage to go up. Adding a config value to allow different interval for retrieving redis metrics as we currently are not calculating stress level using any of these metrics.
- add MetricsCycleRate option in config
=> feat: add MetricsCycleRate config option for redis

centralstore/redis_store.go, collect/central_collector.go, collect/central_collector_test.go
`span.Metadata` is a `map[string]interface{}` type. We were checking the return value against an empty string, which is not always correct. That means if the `meta.refinery.send_reason` does not exist in the metadata map, we will never set the send_reason.
- Properly check empty value returned from metadata map and set `send_reason`
=> fix: make sure send_reason is attached to span metadata

app/app_test.go, centralstore/local_store.go, collect/central_collector.go
- Our app_tests were only testing the redis store; this fixes them to test all the stores (currently redis and local)
- Create a list of store types
- Add iteration over that list to test code
=> maint: let app_tests use all store types

app/app_test.go, config/config.go, config/file_config.go, config/mock.go, route/route.go
- We had "SpanIDFieldNames" to mimic the parentID one, but we don't need it and don't want it.
- Always generate a unique ID for spans when we receive them
- Delete the search for a spanID and all its configuration code
=> maint: Remove SpanIDFieldNames; we don't need it.

collect/central_collector.go, collect/stressRelief/stress_relief_redis.go, internal/health/health.go, internal/health/health_test.go, metrics/metrics.go, metrics/metrics_test.go, route/route.go
- Refinery has endpoints for liveness and readiness, but wasn't putting those in metrics so we can see it in telemetry.
- Add metrics for `is_alive` and `is_ready`
- Update those metrics both on hitting the endpoint and whenever we update the health
- Change `ConvertNumeric` function to accept bools, and add tests for it
- Adjust timing of health system internal ticker -- it needs to run more often than health check updates
- Add some logging to health system when things change, or when configuration errors occur
=> feat: add metrics for alive and ready

centralstore/centralstore.go, centralstore/local_store.go, centralstore/redis_store.go, centralstore/redis_store_test.go, centralstore/smartwrapper.go, centralstore/smartwrapper_test.go, collect/central_collector_test.go, config/file_config.go, config/metadata/configMeta.yaml, config/mock.go, redis/redis.go
Currently, each refinery will retrieve all traces within a state to process them through the state machine in an interval. This approach creates a lot of duplicated work since multiple refineries can end up competing with each other on completing the task for the same trace ID.
- Randomize the trace IDs handed to each refinery
- Process 20% of the total incoming traces on each state ticker
- make `GetTracesNeedingDecision` atomic through lua script
=> feat: distribute workload for trace state management more efficiently

centralstore/redis_store.go, centralstore/redis_store_test.go, collect/central_collector.go
When a late span comes in after stress relief made a decision for the trace it belongs to, we should still be able to make the same decision for that late span. 
This will only works if there's no restart between the stress relief decision is made and the late span arrival. 
- Retrieve trace decision from decision cache in `GetStatusForTraces`
- Correctly record trace decision during stress relief
- add tests
=> fix: make sure we can retrieve trace decisions made during stress relief

config/file_config.go, config/metadata/configMeta.yaml, internal/otelutil/otel_tracing.go
- Refinery now has tracing, but it's a multiplier; we need to be able to specify head sampling to keep it under control.
- Set up sampling in config, use it in setting up OTelTracing
=> feat: Allow sample rate to be configured for Refinery's sampling

collect/central_collector.go, collect/central_collector_test.go, config/file_config.go, config/metadata/configMeta.yaml, config/mock.go
- The memory checker is running runtime.GC() very frequently (many times per second). We think this may be causing problems.
- Create a new configuration to split off the memory checker's cycle time to a new config value
- Set it to 10s by default
- Document the setting
- Make sure it's nonzero
=> feat: Add new ticker for memory check cycle

centralstore/redis_store.go, centralstore/redis_store_test.go, config/file_config.go, config/metadata/configMeta.yaml
Redis memory usage was growing faster than the rate of cleanup from refinery.
- Set the expiration time for a key to be minimum 15 minutes or 10 times of user defined TraceTimeout
=> feat: expire keys in redis based on TraceTimeout

centralstore/centralstore.go, centralstore/local_store.go, collect/central_collector.go, config/metadata/configMeta.yaml, internal/health/health.go
This is fixing several issues that would be in separate PRs if we weren't pushing to get this out but we really just need to fix them all.
- Localstore wasn't giving the correct results because it wasn't handling the sampler selector correctly.
- There was an overly-chatty healthcheck
- Timing on the receiver healthcheck was wrong
- Bug in metadata over config validation
- Add some tracing to the receiver
- Fix status construction code
- Turn off the manual GC call because it seems like it's no longer needed with modern Go GC
=> fix: several bugs

collect/central_collector.go
Memory usage increased when we removed manual GC. Putting it back to see if it will help with refinery's memory usage
- put back runtime.GC call
=> feat: turn manual GC back on

centralstore/redis_store.go, centralstore/smartwrapper.go, collect/central_collector.go
When refinery has issue communicating with Redis, we need to record the error message to help with debugging issues.
- record errors in span
- change log level to error for `WriteSpans`
=> fix: make sure we record critical errors

route/route.go
- #1144 
- Within the `get` method of an `environmentCache`, a read lock is added around read access to the `items` map within the environment cache. It is possible for one routine to hold a write lock within this function while another routine enters the function and attempts to read from the map while the other routine is writing to it.
=> fix: Update cache lookup to use read lock

route/route.go
- #1144 
- Within the `get` method of an `environmentCache`, a read lock is added around read access to the `items` map within the environment cache. It is possible for one routine to hold a write lock within this function while another routine enters the function and attempts to read from the map while the other routine is writing to it.
*NOTE*: Copying commit into 2.x release branch
=> fix: Update cache lookup to use read lock (#1145)

centralstore/redis_store.go, centralstore/redis_store_test.go, config/file_config.go, config/metadata/configMeta.yaml, redis/redis.go
Turns out transmitting trace IDs back and forth between redis and refinery is very expensive.
- Use `ZCOUNT` to get the amount of traces in a given state list instead of `ZRANGE` so that we are only returning a integer value from redis
- Use lua script for deleting expired traces in state lists to avoid returning trace IDs from redis to refinery during cleanup
=> fix: decrease network traffic from redis

config/metadata/configMeta.yaml
- the configMeta type for ReaperBatchSize was wrong
-
=> fix: ReaperBatchSize should be a int type

.tool-versions, centralstore/redis_store.go
A trace state is stored in two data structures in redis currently, one in a hash table with the rest of the `CentralTraceStatus` information, another one in a sorted set. The sorted set is used for `GetTracesForState` so that Refinery can quickly get all trace IDs within a state. Refinery never retrieves a list of trace IDs that has their sampling decisions already made. Therefore, we actually don't need to store than in a sorted set form anymore
This should further reduce our Redis memory usage.
- don't store trace IDs in a state if it's decision is already made
=> fix: no need to store decisions in a list in redis

collect/stressRelief/stress_relief_redis.go, internal/gossip/gossip.go, internal/gossip/gossip_inmem.go, internal/gossip/gossip_redis.go, internal/gossip/gossip_redis_test.go
- Gossip uses callbacks. A callback approach adds extra code we don't need if we use channels. This is a refactoring to change it to channels. Each commit is standalone.
My desire is to merge this before #1158 and then fix that one (which does a bit more gossiping) to use channels.
=> fix: gossip into channels instead of callbacks

internal/gossip/gossip_redis.go
the health check should happen before the pubsub goroutine
=> fix: register gossip-redis health before start pubsub

rules_conditions.md
- Fixes errors like `- rules.Samplers.__default__.RulesBasedSampler.Rules.0.Conditions: Invalid type. Expected: array, given: object` when copy-pasting from the README
- Update README to show Conditions as a list rather than object
=> fix: Fix docs formatting around list type

internal/gossip/gossip_redis.go
The healthcheck ping and pong message on the redis pubsub channel are sent on an interval. That interval is delaying the  start time for refinery. Mark gossiper to be ready when we receive a message on the pubsub channel as well so we are not only relying on the redis health check message 
- mark gossip-redis to be ready whenever refinery receives a message from redis pubsub channel.
- reduce the timeout on the healthcheck since we should be able to get a ready check more often.
=> fix: set health check to ready when receiving a message on the channel

centralstore/centralstore.go, centralstore/local_store.go, centralstore/redis_store.go, centralstore/redis_store_test.go, centralstore/smartwrapper.go, centralstore/smartwrapper_test.go, collect/central_collector.go
During stress relief, more trace decisions are made through the deterministic sampler and their decisions are stored only in memory. It's wasteful to asking redis for those decisions that redis has no idea of. Refinery should check with the in-memory decision cache first before asking redis for a trace status
- move the logic to check with the decision cache to the top of the `GetStatusForTraces` call
- make `RecordTraceDecision` signature to be more clear
=> fix: get trace decision from cache before asking redis

collect/central_collector.go, collect/stressRelief/stress_relief_redis.go, collect/stressRelief/stress_relief_test.go, go.mod, go.sum, internal/gossip/gossip.go, internal/gossip/gossip_inmem.go, internal/gossip/gossip_redis.go, internal/gossip/gossip_redis_test.go
- Gossip channels are arbitrary strings and don't really need to be; we have only a few of them. Instead, you can use your string name to create a numeric channel and put that on the messages. Because we need different instances to use the same channel IDs, we still use constants for the string IDs. We can build IDs on the fly (and do when we're standalone) but in Redis we expect the constants to be used. 
- Define Channel type
- Adjust how messages are built and used
- Fix the places they were used
- Use constants
- Debug tests
=> fix: Gossip channels are now bytes, no dropped messages

centralstore/centralstore.go, centralstore/redis_store.go, centralstore/redis_store_test.go, collect/cache/cuckooSentCache.go, collect/cache/traceSentCache.go, collect/central_collector.go, collect/central_collector_test.go
This PR fixes multiple issues when dealing with late spans.
- updating late span counts in decision cache
- make sure late span data in redis gets cleaned up
- make sure key span list in redis is cleaned up if the trace decision is made through stress relief
-  make sure expired traces in span cache is cleaned up regardless their state
- create `SpanRecorder` interface so that both `types.Span` and `centralstore.Span` can be recorded in cuckoo cache
- add expiration time for `addStatus`, `storeSpans`, and `incrementSpanCount` queries
- make sure `cleanupTraces` retrieves state for a trace in spancache regardless which state the trace is in
-
=> fix: make sure we clean up data in redis for late spans

internal/gossip/gossip_inmem.go, internal/gossip/gossip_redis.go
Test are flaky when using in-memory gossiper due to race condition on shutdown.  
- If the `g.gossipCh` is closed, Refinery should return instead of keep processing the value
=> fix: return when gossip channel is closed

internal/otelutil/otel_tracing.go
Refinery's traces wasn't getting send to honeycomb classic environment
- add dataset header to otel tracing config
=> fix: allow sending otel tracing to honeycomb classic environment

collect/central_collector.go, collect/central_collector_test.go
When traces don't have a decision from the collector gossip channel, use the same encoding format to send it back into the channel buffer
Only publish trace decisions through gossip after decisions have been recorded in redis
- use a simpler encoding method for keep/drop gossip messages
- persist trace decisions to redis before publishing them through gossip channel
=> fix: improve collector gossip

collect/central_collector.go, config/file_config.go, config/metadata/configMeta.yaml
We have discovered that the decider can take much longer than 500ms to complete an iteration. In order to avoid health check being flappy, we need more control over the timeout value.
- introduce a new config value for decider health check
=> feat: add config for decider health check

centralstore/redis_metrics_recorder.go, centralstore/redis_store.go, centralstore/redis_store_test.go, redis/redis.go, redis/redis_test.go
We have converted a lot of code to use pipelining pattern for communication with Redis. This PR is to allow the caller of the redis package to have an easier time to use the pattern
- return a command object from each redis call so that the caller has control whether to buffer or send a query to redis
- remove unused code
=> maint: clean up redis interface

go.mod, go.sum
Updates libhoney-go to latest version, which includes a fix for correctly formatting URLs.
- update libhoney-go to 1.23.1 and run go mod tidy
=> maint: Bump libhoney-go to v1.23.1

go.mod, go.sum
Updates libhoney-go to latest version. Includes URL encoding dataset name for /event and /batch endpoints.
**Note**: This is an update for the 3.x release channel. It was added to the 2.x branch in the following PR:
- #1192
- Update libhoney-go to 1.23.0 and run go mod tidy
=> maint: bump libhoney-go to v1.23.0

collect/collect.go, collect/collect_test.go
Log events should never be considered root spans even though they do not contain a `trace.parent_id`. A log event that is part of a trace would mark the trace complete as if it's considered a root span.
This change updates the check for whether a span is considered a root span to also check for the meta field `meta.signal_type`. If the field exists and is set to "log", we return false.
- Update `InMemoryCollector.isRootSpan` to check if `meta.signal_type` and has a value of "log"
- Add unit tests for InMemoryCollector to verify expected behaviour for isRootSpan
=> fix: Don’t consider log events as root spans

CHANGELOG.md, RELEASE_NOTES.md
Prepares the next release of Refinery for publishing.
- Add change log entry
=> rel: Prepare v2.6.1 release

app/app.go, cmd/refinery/main.go, collect/collect.go, config/config.go, config/configLoadHelpers.go, config/configLoadHelpers_test.go, config/config_test.go, config/file_config.go, config/mock.go, logger/honeycomb.go, metrics/legacy.go, transmit/transmit.go
To provide better visibility of current configuration used in Refinery, this PR introduce two metrics, `config_hash` and `rule_config_hash`, for keeping track of configuration.
- change config change log from `info` level to `warn`
- include full config hash value in config change log
- store the decimal number of the last 4 digit of config hash value as metrics
#967
=> feat: track config hash on config reload

app/app_test.go, collect/collect.go, collect/collect_test.go, internal/otelutil/otel_tracing.go, route/route_test.go
`OtelTracing.APIKey` is specifically for setting a honeycomb api key and header when setting up a tracer. When it's not set and `OtelTracing.Enabled` is set true, Refinery should still set up a tracer that can be used to send Refinery traces to non-honeycomb backend.
- Only set APIKey headers when APIKey is not empty
- add some basic instrumentation
=> fix: allow sending otel tracing to non honeycomb backend

cmd/refinery/main.go, internal/peer/pubsub_redis.go
- Add jitter to peer traffic so we don't get thundering herds
- Inject the right things for proper startup
=> maint: Add jitter to peer traffic, fix startup

Dockerfile
This dockerfile is used only for local development. Now most of us who are actively working on this project are on ARM machines. Let's make it easier to test refinery locally
- Change targeted architecture to ARM
=> maint: change targeted arch to arm for local development Dockerfile

app/app_test.go, cmd/refinery/main.go, collect/stressRelief.go, internal/health/health.go, internal/health/health_test.go, internal/peer/pubsub_redis.go, route/route.go, route/route_test.go
- Refinery needs a proper health monitoring system that can watch multiple subsystems and deliver both "alive" and "ready" responses to health check endpoints, both for grpc and http endpoints. This is that system, imported from R3 and improved a bit.
- Import health and tests from R3 and clean up its documentation and some of the internal names
- Hook it up to the router including the grpc health endpoints
- Tie it in to stress relief so that it's monitoring something (otherwise it will never be ready)
- Inject it into the app
=> feat: Health/Ready system imported from R3

internal/peer/peers_test.go, internal/peer/pubsub_redis.go, pubsub/pubsub.go, pubsub/pubsub_goredis.go, pubsub/pubsub_local.go, pubsub/pubsub_test.go
Add instrumentation for GoRedisPubSub to gain more insight on how the redis pubsub system works
- add tracer to `GoRedisPubSub`
- fix tests
- define a type for the pubsub subscription callback function
=> maint: add instrumentation for GoRedisPubSub

collect/stressRelief.go, collect/stress_relief_test.go
Make sure subscriber and publisher uses the same channel for stress relief
- define a constant for stress relief pub/sub topic
- use the constant in test and stress relief code
=> fix: make sure stress relief pub/sub topic is consistent

internal/configwatcher/watcher.go
Config and PubSub needs injection tags for the injection framework
- add injection tag
=> fix: add injection tags for configwatcher

collect/stressRelief.go
We don't need to publish stress level if it hasn't changed. This will help reduce the amount of pub/sub messages being transmitted in the cluster
- made `stressReliefMessage` struct more memory efficient
- add a counter for tracking how long it has been since last stress level publish
=> fix: reduce pub/sub messages from stress relief

app/app_test.go, collect/stressRelief.go, internal/peer/file.go, internal/peer/file_test.go, internal/peer/mock.go, internal/peer/pubsub_redis.go, sharder/deterministic.go, sharder/deterministic_test.go
`DeterministicSharder` wasn't updated to use the new peer identification system to determine which peer a given trace belongs to. This resulted Refinery couldn't identify itself in the peer list within the sharding system. 
- Consolidate and unify code for retrieving peer identity
- replace `:` with `|` as the delimiter in stress relief message 
- make sure `filepeer` returns `PeerListenAddr` as its public address
=> fix: sharder should use peer identity from Peers package

sharder/deterministic.go
Accidentally left a print line from the previous PR
remove `fmt.Println`
=> fix: clean up a print line

app/app.go
- The config hashes were not being recorded at startup so they show up as 0 in the metrics.
- Record the hashes both at startup and on changes.
=> fix: Record hashes at startup in metrics

cmd/refinery/main.go, config/metadata/configMeta.yaml
- If someone specified FilePeers, then we are assuming they don't want to run Redis.
- Simplify logic; if FilePeers, no redis and only local pubsub.
- Update some of the documentation.
=> fix: FilePeers implies no Redis

collect/stressRelief.go, collect/stress_relief_test.go
Without resolving trace locality issue, a single peer can receive a large trace that significantly raise its stress level than the rest of the cluster. To address this issue, we can allow individual refineries to go into stress relief mode if their own stress is too high, even if the cluster's isn't.
- use the max of the individual stress level and the cluster stress level as the overall stress level when calculating stress relief activation and deactivation
- record the stress level that determined stress relief activation as `stress_level` metric
- add tests
=> fix: allow a single node to activate stress relief mode during significant load increase

app/app_test.go, cmd/refinery/main.go, collect/collect.go, collect/collect_test.go, config/config.go, config/config_test.go, config/config_test_reload_error_test.go, config/file_config.go, config/metadata/configMeta.yaml, config/mock.go, internal/peer/file.go, internal/peer/peers_test.go, internal/peer/pubsub_redis.go, logger/honeycomb.go, logger/logger.go, logger/logrus.go, pubsub/pubsub_goredis.go, route/otlp_trace_test.go, route/proxy.go, route/route.go, sample/sample.go, service/debug/debug_service.go, test/config.yaml, transmit/transmit.go
- Since the introduction of validation of config, the config functions can't fail, and the error returns are useless. 
- Remove error returns from all the config getters
- Fix all the places we used (or didn't use them)
- Fix a couple of tests that assumed things that are no longer true
=> refactor: Remove error returns from config functions, fix tests.

cmd/refinery/main.go, collect/collect_test.go, collect/stressRelief.go, collect/stress_relief_test.go, internal/peer/file.go, internal/peer/mock.go, internal/peer/peers.go, internal/peer/pubsub_redis.go, sharder/deterministic_test.go
In order to recalculate new destination for traces during shutdown as soon as possible, we need to announce peer unregistration first thing.
- use the `done` channel from catching the termination signal in main.go in peer management
=> feat: unregister peer asap on shutdown

app/app_test.go, cmd/refinery/main.go, collect/collect.go, collect/collect_test.go, config/config.go, config/config_test.go, config/file_config.go, config/metadata/configMeta.yaml, config/mock.go, route/otlp_trace_test.go
#1257 -- helps to keep Refinery from exploding when a giant trace arrives.
- Adds a SpanLimit that kicks off trace evaluation as soon as the number of spans in a trace exceeds that value
- Moves some config stuff around (reducing the size of Config) and fixes the tests that touch it
- Fixes #1257
=> feat: Add SpanLimit (includes some config changes)

collect/collect.go, collect/collect_test.go, config/metadata/configMeta.yaml
- Fixes #1270 
- Adds a test for preserving sample rate for late spans
=> fix: SpanLimit shouldn't add SendDelay

collect/collect.go, collect/collect_test.go
Sample rate is not recorded in trace decision cache during stress relief. This could cause weird sample rate data for spans arrived after refinery has exited stress relief mode
fix: #1271 
- record sample rate in decision cache
- add tests
- make sure collector uses clockwork.Clock in all places
=> fix: record sample rate in decision cache during stress relief

route/route.go, test/config.yaml
- If the compressed input to an HTTP request is too big, it can cause Refinery to have difficulties. 
- Set a request max for the HTTP inputs /1/batch and /1/events
- Remove bogus syntax from test config
I don't have a good way to test this in CI, but it was extensively tested locally.
=> fix: don't read more than max bytes from a request

collect/collect.go, collect/collect_test.go
When in peer mode, there could be a situation that the load is low enough for just one refinery instance. We should allow a scale down event to happen even if there's only one refinery left
- change the condition to run redistribution logic to as long as there's 1 peer in the peer list
- add `trace_redistribution_count` metric to track how often a redistribution event has been triggered.
=> fix: allow draining traces even if only 1 peer left

route/route.go
This is a cherry-pick of the commit from #1276 to the 2.8 (main) branch.
=> fix: don't read more than max bytes from a request (#1276)

internal/peer/pubsub_redis.go, pubsub/pubsub_goredis.go
Currently, we are not setting the tls config for go-redis even through we do have `UseTLS` configuration option.
- log the pubsub publish error
- configure redis client tls
=> fix: support TLS connections to Redis

config/config_test.go, sample/dynamic.go, sample/dynamic_ema.go, sample/ema_throughput.go, sample/totalthroughput.go, sample/windowed_throughput.go
- Fixes #1279 
- Update the previous values 
- Fix a test that was sensitive to existing standard envvar
=> fix: record previous value of sampler counter metrics so they report correctly

config/config_test.go, config/file_config.go, config/metadata/configMeta.yaml
- Fixes #1131 
- The default receive message size is smaller than Honeycomb accepts, which can be confusing. Change it, and the default send size, for better efficiency.
- Change the defaults from 5MB to 15MB
- This is *technically* a breaking change but only by the most pedantic definition -- there's no realistic situation in which this actually matters, so we're not going to stress over it.
=> maint: change default for MaxSendMsgSize and MaxRcvMsgSize.

collect/collect.go, collect/collect_test.go
We should not set send reason to span limit if users didn't specify the span limit config
- only set send reason to span limit if span limit config is non-zero
=> fix: only set send reason to span limit if it's configured

go.mod, go.sum
The cuckoofilter library has been updated with similar changes to the ones we made in [our fork of it](https://github.com/honeycombio/cuckoofilter) (faster hash, instanced RNG for better parallel performance).
Benchmarks now show it is slightly faster than our implementation, so we're switching back.
- Remove `replace` directive in our go.mod, use latest version of cuckoofilter.
=> maint: use non-forked cuckoofilter again

internal/peer/pubsub_redis.go, pubsub/pubsub_goredis.go
Currently, we are not setting the tls config for go-redis even through we do have `UseTLS` configuration option.
- config tls with go-redis when it's enabled
=> fix: set up tls for redis when it's enabled

collect/cache/cuckoo.go, collect/cache/cuckooSentCache.go, collect/cache/cuckoo_test.go, generics/setttl.go, generics/setttl_test.go
We have a customer who has so much traffic sometimes, that the cuckoo drop cache can't record the dropped IDs as fast as they're dropping them, so it's overrunning its input queue.
This is a frustrating single point of failure because there is a single goroutine responsible for filling this cache which means adding CPUs won't help, and because of trace locality, adding more nodes won't help when a burst of spans comes from a single giant trace. Making the queue larger just means that it will take a little longer to fill up.
The contention is that we write to the cache when we drop a trace, but we read from it for every span that arrives. So if you have a single huge trace, you might fairly quickly decide to drop it, but still have to query the cache tens of thousands of times for new …
=> feat: Add a cache to the cache

collect/collect.go, collect/collect_test.go
Refinery converts SpanEvent and SpanLink to individual events just like regular spans. We should use DescendantCount to check against the SpanLimit instead of only spans.
- use DescendantCount to check against SpanLimit
- modify test to explicitly check for span limit trace send reason
=> fix: use trace.DescendantCount for span limit

route/route.go
- The debug endpoint doesn't sanitize the user input before using it in the response.
- use `html.EscapeString` to escape the user's input string for use in refinery and the response.
=> fix: escape use input in debug route

config/config_test.go, config/metadata/rulesMeta.yaml, config/sampler_config.go, config/sampler_config_test.go, config/validate.go, rules_complete.yaml, rules_conditions.md
- Fixes #1074 
- Adds `In` and `NotIn` operators to Refinery rules, and allows the Value field to become a list of values.
- Change validation so that we can specify multiple Values
- Implement In and NotIn operators
- Write tests
- Document
=> feat: add IN operator

metrics/otel_metrics.go
- When we first introduced OTel metrics to Refinery, we only had int histograms to work with. But now float ones are available and the int one can yield very surprising results when your values are close to 0.
- Replace Int64Histogram with Float64Histogram
- That's it.
We think that since we've never heard about this one before, it's probably the case that most people using histograms are using them for larger values, and so there won't be any real-life impact from this change.
=> fix: use float histogram for otel metrics

cmd/refinery/main.go, internal/peer/file.go, internal/peer/mock.go, internal/peer/peers.go, internal/peer/pubsub_redis.go
Currently, Refinery announces its presence to peers immediately upon startup. This causes the sharding algorithm to direct other peers to forward traces to the newly added Refinery instance, even though it might not be ready to process them. As a result, any spans forwarded before the Refinery is fully operational are lost. This fix ensures that Refinery only announces itself to peers once it is fully ready to accept and process traffic, preventing any loss of spans during startup.​
Alternatives:
I have tried to use the `health` module as a signal to indicate when the `router` is ready for the `peers` module. However, due to the way the `injection` library works, the `router` starts after the `peers` module. As a result, when `peers` checks in with the health system, the `router` may not …
=> fix: join peer list only after refinery is ready to accept traffic

cmd/refinery/main.go
Reverts honeycombio/refinery#1310 since it wasn't the issue.
=> fix: revert the revert -- that wasn't the problem

collect/cache/cuckooSentCache.go, generics/setttl.go
The recent_dropped_traces cache wasn't getting cleaned up
- update documentation on the `SetWithTTL`
- make sure the cache is cleaned up periodically
=> fix: periodically clean up recent_dropped_traces cache

config.md, config/metadata/configMeta.yaml, config_complete.yaml, refinery_config.md, tools/convert/templates/configV2.tmpl
This PR syncs the Refinery docs content between the Honeycomb docs site and the Refinery docs source file for v. 2.8.
This PR includes minor formatting and other changes for clarity in the docs.
=> docs: Sync Refinery docs content for 2.8

sharder/deterministic.go
Since we changed the peer to only announce itself after refinery has started up, we need to make sure sharder populates its peer list manually on startup
- call `loadPeerList` in sharder once in `Start`
=> fix: load peer list in sharder once manually on startup

config/cmdenv.go, config/config_test.go, config/file_config.go
Adds support for setting the send key (API key) used to send data to Honeycomb via both command line and env var.
- closes #1317
- Add support for setting AccessKeys.SendKey via command line arg `--send-key` or env  var `REFINERY_SEND_KEY`.
- Add unit tests to verify behaviour
=> feat: Allow SendKey to be set via command line and env var

sample/rules.go, sample/sample.go
- ClusterSize was not properly set for samplers that supports `UseClusterSize`
- implement `ClusterSizer` for rules sampler
- convert a `Sampler` to `ClusterSizer` by going through `any`
=> fix: assertion for ClusterSizer

cmd/refinery/main.go, collect/collect.go, collect/stressRelief.go, metrics/otel_metrics.go, sharder/deterministic.go
Improve some log messages to be more accurate about what's actually happening.
- closes #1321
- Improve log messages
- Prefer using WithField / WithString to include parameters instead of inline formatting
- Update memory overrun messages from error -> warn - they do not constitute data lost so error feels heavy handed
=> feat: Improve log messages to be more informative

sample/rules.go, sample/sample.go
- in #1329 , we introduced the assertion to `any` as the intermediate step to check whether a Sampler is a ClusterSizer. 
- It turns out that this intermediate step is unnecessary.
- remove assertion to `any` in `SetClusterSize`
=> fix: remove unnecessary assertion to any

logger/honeycomb.go
Updates the Honeycomb logger to use the [EMAThroughput](https://github.com/honeycombio/dynsampler-go/blob/main/emathroughput.go#L77) sampler. This sampler has built-in support for burst protection that the [PerKeyThroughput](https://github.com/honeycombio/dynsampler-go/blob/main/perkeythroughput.go#L17) sampler does not.
Burst protection would be useful when a cluster node does down unexpectedly because the other nodes in the cluster will fail to make peer requests until it is removed from the cluster. This can result in a very high number of "failed to send" log messages in a very small window, faster than what the PerKeyThroughput sampler can adjust the sample rate which results in all log messages being sent. The burst protection from the EMAThroughput sampler would help here as it …
=> feat: Update Honeycomb logger to use EMAThroughput sampler

collect/collect.go
related to #1348 
Currently, the collector's timeout for healthcheck is set to 3 seconds. During a shutdown, there could be a large number of traces or spans that need to be forwarded to peers. If this is taking longer than 3 seconds, it will definitely timeout the liveness check. 
Since we are shutting down anyway, just let the ShutdownDelay to do the work and not worry about the liveness.
- Unregister `collector` from Refinery's liveness check
=> fix: remove InMemoryCollector from liveness check on shutdown

cmd/refinery/main.go, metrics/otel_metrics.go, transmit/mock.go, transmit/transmit.go
Honeycomb’s board template requires that columns be created before any queries can be added. However, in OpenTelemetry (OTel), metrics are not sent until they have a value, which caused an issue where customers missed queries on their Refinery boards during the initial setup of their instances.
This PR addresses the issue by setting a default value of 0 for all OTel metrics during the Register call. This ensures that OTel sends these metrics to Honeycomb immediately upon Refinery startup, preventing gaps in the board’s initial queries.
- Set 0 for each OTel metrics during registration
=> fix: set 0 for otel metrics during registration

collect/collect.go, config/metadata/configMeta.yaml, metrics.md, tools/convert/main.go, tools/convert/metrics.go, tools/convert/metricsMeta.yaml, tools/convert/templates/metrics.tmpl
The current metrics metadata generator does not resolve dynamically assigned prefixes during metrics registration. As a result, metrics with dynamic prefixes are not displayed with their full names. To improve clarity, these metrics should be shown in a separate table.
- Identified that certain packages in Refinery—specifically those used for peer and incoming nodes, as well as the sampling package—assign dynamic prefixes to their metrics.
- Added logic to the generator to detect metrics from these packages and categorize them separately.
- Updated the metrics.tmpl template to display metrics with dynamic prefixes in a distinct table, ensuring clear differentiation between metrics with and without full names.
=> feat(doc): separate table for metrics contains prefix

sample/dynamic.go, sample/dynamic_ema.go, sample/ema_throughput.go, sample/totalthroughput.go, sample/trace_key.go, sample/trace_key_test.go, sample/windowed_throughput.go
- If someone sends a big trace where one of the sampler keys is a high-cardinality field, Refinery could generate a huge sampler key value. This causes problems both for refinery but also the downstream telemetry. Let's not do that.
- Put a limit of 100 unique values to make up any one sampler key. Even that is big and probably useless but it should avoid any real use cases. 
- Add a test to show it works.
Fixes #1363
=> fix: Put a limit on the size of sampler keys

collect/collect.go, config/file_config.go, config/metadata/configMeta.yaml
When there's a big volume of traffic, collector can take longer to respond to the health check
- add a new config option `HealthCheckTimeout` in `Collection`
=> feat: make collector health check timeout configurable

CHANGELOG.md, RELEASE_NOTES.md
Prepares the v2.8.3 release.
- Add change log entry
=> rel: Prepare 2.8.3 release (updated)

collect/collect.go
- Recording the value as a guage meant that a lot of values were missed as the older values got overwritten by newer values. This meant the largest value in the interval may not get exported.
- Switch `collector_collect_loop_duration_ms` from gauge to histogram to make sure max values are captured.
=> fix: Switch `collector_collect_loop_duration_ms` metric to be a histogram 

CHANGELOG.md, RELEASE_NOTES.md, config.md, config_complete.yaml, refinery_config.md, rules.md, tools/convert/configDataNames.txt, tools/convert/minimal_config.yaml, tools/convert/templates/configV2.tmpl
- prep 2.8.4 release
- run `make all` (we forgot to do this on the 2.8.3-release branch).
- update changelog
- update release notes
=> rel: prepare v2.8.4 release

CHANGELOG.md, RELEASE_NOTES.md, collect/collect.go, config.md, config_complete.yaml, metrics.md, refinery_config.md, rules.md, tools/convert/configDataNames.txt, tools/convert/metricsMeta.yaml, tools/convert/minimal_config.yaml, tools/convert/templates/configV2.tmpl
- gets the changes from 2.8.4 into main
- update `collector_collect_loop_duration_ms` type
- run `make all`
- get 2.8.4 changelog and release notes.
=> maint: cherry pick v2.8.4 commits into main.

transmit/transmit.go
Updates the response handler to log the response body when sending events to Honeycomb. This can be a useful tool to identify when there there is a problem sending events.
- Closes #1048
- If the response has a body, add it to the logged fields
=> feat: Log response bodies when sending events to Honeycomb

internal/peer/pubsub_redis.go
- #1369 
Since `GetPeers()` in redis peer implementation returns `127.0.0.1:8080` when no peer is present, it causes trace forwarding to fail if all peers have unregistered itself from the system.
- use current node address as the default peer list
=> fix: use current node address as default peer list

config/metadata/rulesMeta.yaml, refinery_rules.md, rules.md, rules_complete.yaml
- This PR documents the feature from #1275, showing our users how to specify the `root.` prefix in FieldLists everywhere
- It also sprinkles the use of this feature around the `rules_complete.yaml` example
=> docs: Document the ability to use  prefix in dynamic sampler FieldList

config/file_config.go, config/metadata/configMeta.yaml, internal/otelutil/otel_tracing.go
- Closes https://github.com/honeycombio/refinery/issues/1392
- Adds new `OTelTracing.Insecure` config option to allow exporting internal traces via http.
- Update otelutil's `SetupTracing` to switch between insecure and tls based on `OTelTracing.Insecure`.
- Remove the hard-coded `:443` when parsing the configured `OTelTracing.APIHost`
=> fix: Allow insecure otlp traces

collect/collect.go, collect/collect_test.go, route/otlp_logs_test.go, route/otlp_trace_test.go, transmit/mock.go
Refinery's test suit has been flaky in the CI due to the fact that the CI has way less CPU than our dev machines.
In the past, we have tried to use `Eventually` from the test framework to stabilize our collector tests. Due to CPU constraint in the CI environment and the amount of lock and unlock operations, tests have been failing depends on when a goroutine is picked up by go scheduler.
This PR changes the event buffer in MockTransmission from a mutex protected slice to a channel. This separates the `Enqueue` operation from the `Get` operation so that a writer will not be blocked by a reader
- implement event buffer using a go channel
- update all existing tests to use the new semantic
- check whether we are in shutdown before enqueue a event from the collector to libhoney
=> maint: use a queue for events buffer in MockTransmission

collect/collect.go, collect/collect_test.go, config/file_config.go, config/metadata/configMeta.yaml, pubsub/pubsub_local.go
To reduce network traffic from nodes communicating about trace decisions, drop decisions will be sent in batches. The batching logic is based on either a maximum batch size or a timer. Refinery will send a batch when the batch size limit is reached or when the timer expires, whichever comes first.
- add `sendDropDecisions` goroutine
- add two new config options for the batch size and the ticker interval. This is mostly for easier testing. We may not include these two configs in the final release.
=> feat: send drop decisions in batch

collect/cache/cache.go, collect/collect.go, collect/collect_test.go
If for some reason, a trace that doesn't belong to a peer in the trace cache missed its trace decision from its decider, it will stay in the cache forever.
This PR introduce a clean up mechanism for the scenario above. 
- When a trace has expired more than 2 times of the TraceTimeout, we will forward a proxy span to its decider so that the decider will publish the trace decision again.
- When a trace has expired more than 4 times of the TraceTimeout, we will just make a decision for that partial trace from the current host.
- modify the `filter` function in `sendExpiredTraces` to also return traces that have expired for too long
- remove return value from trace cache interface since its no longer used
- fix trace_cache histogram metrics to pass in the duration as float64
- add test for …
=> fix: deal with orphan traces in trace cache

collect/cache/cache.go
in Go, numeric constants are untyped. We need to explicitly assign float64 to the result in order to get floating-point result
- assign the duration metrics to float64
=> fix: explictly assign float64 type for trace cache metrics

config/configLoadHelpers.go
To fetch a configuration from Honeycomb, we're going to need a way to specify a header for the team key. This allows the key to be specified in an environment variable called `HONEYCOMB_CONFIG_KEY`. This is deliberately different from the telemetry key because the key will have to have special permissions.
If the key is not blank, then the header `x-honeycomb-team` will be set and used for the config requests. The header will not be used if the key is blank.
We are deliberately not adding this to public documentation because this feature is still experimental and we may well change it. 
- Fetch `HONEYCOMB_CONFIG_KEY` from the environment
- Set `x-honeycomb-team` header if the key is non-blank.
=> feat: Add a way to specify the team key for config fetches (experimental)

collect/collect.go, collect/collect_test.go, collect/trace_decision.go, collect/trace_decision_test.go, config/file_config.go, config/metadata/configMeta.yaml
The throughput of Redis pub/sub is impacted by the number of messages sent per time unit. To improve performance and ensure a higher throughput of kept messages, we need to reduce the number of kept messages sent. 
This PR implements a batching strategy similar to the one used for dropped messages, reducing the frequency of sending individual kept messages.
- Introduced a batching strategy for kept messages, similar to the existing strategy for dropped messages.
- Refactor kept and dropped decision processing to reduce duplicated code
=> feat: batch kept decisions

config/metadata/configMeta.yaml
Updates docs for using DryRun and EnableTraceLocality together.
- Closes #1361
- Update config documentation
NOTE: Generated docs will be done as part of release process.
=> docs: update config docs for compatability of using DryRun and EnableTraceLocality together

config/file_config.go, config/metadata/configMeta.yaml
Allow more efficient batching for publishing kept decisions
- increase default config value to 1s
=> feat: increase KeptDecisionSendInterval default value to 1s

cmd/refinery/main.go, generics/mapttl.go, generics/mapttl_test.go, internal/peer/peers_test.go, internal/peer/pubsub_redis.go, internal/peer/pubsub_test.go
This is an alternative implementation of #1417, with 2 key differences:
- Added a new generic type, `MapWithTTL` to store the ID and address and used it instead of SetWithTTL. It's about 15% slower than SetWithTTL for equivalent operations, but it solves the problem we have here.
- I constrained the unique ID to 8 characters, hashed from a UUID. 
- I also cleaned up an unneeded typename in main.go that my editor was complaining about.
Closes #1417.
=> feat: publish instanceID during peer comms

collect/collect.go, collect/trace_decision.go, collect/trace_decision_test.go
Since we have delayed trace decision publication and sending a trace, `processTraceDecisions` may be processing the same trace as `sendTraces` which causes concurrent access to the `span.Data` map.
This PR changes the `processTraceDecisions` to get trace decision information only from the `TraceDecision` object and only record a trace decision if it doesn't exist in the decision cache
- implement `cache.KeptTrace` interface for `TraceDecision`
- only record a trace decision if it doesn't exist in the decision cache
=> fix: do not use trace object during processTraceDecisions

collect/collect.go
There's a log entry when making a decision that is a warn level, which is too high. Lowering to debug.
- Upate log level for making a decision from warn to debug
=> maint: Update log level for making a trace decision to debug

build-docker.sh
- Image builds in Circle were still using the job ID as the version.
- Reliably set the version regardless of where the image build is being run.
- Moves the image tagging logic to below the version-determination logic. Now the dev-build tagging can reuse the determined dev version instead of using the CircleCI build ID.
- Sets some defaults for environment variables to appease the `nounset` shell rule when this script is run outside of CI.
```
❯ ./build-docker.sh
++ git describe --tags '--match=v[0-9]*' --always
+ VERSION=2.8.2-58-g264d4af
… 
+ GOFLAGS=-ldflags=-X=main.BuildID=2.8.2-58-g264d4af
… 
+ ./ko publish --tags 2.8.2-55-gcc8c2a2 …
… 
2024/11/12 13:58:26 Adding tag 2.8.2-55-gcc8c2a2
… 
```
```
#!/bin/bash -eo pipefail
./build-docker.sh
…
+ …
```
=> fix: more reliable dev version tagging

.github/dependabot.yml, go.mod, go.sum
- Version 0.31.0 of husky was bad
- Bump husky to v0.32.0
- Fix team name in dependabot script
=> maint: build fixes

collect/collect.go, collect/collect_test.go, collect/stressRelief.go, collect/trace_decision.go, collect/trace_decision_test.go
collect loop iteration is precious to make sure Refinery is able to process incoming data as soon as possible. Trace decision pubsub messages are broadcasted to all peers including the publisher itself. There's no need for the publisher to process those messages since it already knows about those trace decisions.
- prefix each decision messages with the peer ID. I didn't include it into the compression logic. That way we can skip the whole decompression process for a message if we know it's produced by its publisher
- ignore decision messages in the pubsub callback before we ask the collect loop to process them
=> feat: ignore trace decision messages produced by the publishers

collect/collect_test.go, collect/trace_decision.go, collect/trace_decision_test.go
Previously, the logic to ignore messages were wrong. We should only ignore messages that produced by the same sender as the current node
- fix the sender id checking code
- add more tests
=> fix: only ignore messages that are coming from the node itself

collect/collect.go
We're seeing that incoming and peer queues can sometimes build up and it takes a long time to recover. A theory is that this is because the collect loop has so many options, we should allow multiple messages to be read from the incoming and peer queues whenever that it's selected to be worked on.
- Add a new utility func that can read messages from a given span channel for up to 100 milliseconds, exiting early if the channel is empty
- Update incoming and peer channels to use new func
=> feat: Try to drain incoming and peer queues for an amount of time

collect/collect.go
The timer may never fire due to Go scheduler starving the timer goroutine.
To prevent the timer being starved, this PR adds a limit to the number of spans being processed during one iteration of the collect loop
- add a limit to the draining logic
=> feat: add a limit to queue draining logic

collect/collect.go
The result from this change did not work as intended
- revert draining code for incoming and peer queue
=> fix: revert draining logic for incoming and peer queue

app/app_test.go, collect/collect.go, collect/collect_test.go, collect/stressRelief.go, collect/stress_relief_test.go, config/file_config.go, config/metadata/configMeta.yaml, route/route.go
To allow users to opt-in safely for disabling trace locality, we're renaming the option to disable trace locality.
- Rename `EnableTraceLocality` to `DisableTraceLocality`
=> feat: Rename EnableTraceLocality to DisableTraceLocality

sample/sample.go
- We already have a signal for cluster size change. We don't need to log this in sampler as well.
- remove the log for cluster size change
- change the interface assertion log to debug
=> maint: clean up sampler log entry

config.md, config/metadata.go, config/metadata/configMeta.yaml, config_complete.yaml, metrics.md, refinery_config.md, tools/convert/configDataNames.txt, tools/convert/metricsMeta.yaml, tools/convert/minimal_config.yaml, tools/convert/templates/cfg_docrepo.tmpl, tools/convert/templates/cfg_docsite.tmpl, tools/convert/templates/configV2.tmpl, tools/convert/templates/gengroup.tmpl, tools/convert/templates/rules_docrepo.tmpl, tools/convert/templates/rules_docsite.tmpl, tools/convert/templates/sample.tmpl
- We have some config options that we'd like to avoid publishing, because we don't know for sure we'll need them, but we want to give ourselves the ability to mess with them while tuning a configuration. By adding the ability to flag a config item as unpublished, it won't go in the main documentation and we can modify it later without breaking changes.
- Add unpublished flag to metadata struct
- Add it to a couple of fields
- Regenerate docs
=> feat: Add 'unpublished' flag to configs 

collect/cache/cache.go
we are not using these metrics.
By removing them, we should also gain some CPU time back. Though, this is not the driver for this change.
- removing histogram metrics from trace cache
=> maint: remove trace cache metrics

config.md, config/metadata/configMeta.yaml, refinery_config.md
- Customer reported a doc error; they were right.
- Fix the name of an environment variable
- Regenerate necessary docs
=> fix: documentation bug

app/app_test.go, collect/collect.go, collect/collect_test.go, collect/stressRelief.go, collect/stress_relief_test.go, config.md, config/file_config.go, config/metadata/configMeta.yaml, config_complete.yaml, refinery_config.md, route/route.go, tools/convert/configDataNames.txt, tools/convert/minimal_config.yaml, tools/convert/templates/configV2.tmpl
To improve readability of the config option for our users, this PR changes the binary trace locality feature flag to a mode structure.
- Rename `DisableTraceLocality` to `TraceCache` that comes with two modes, `concentrated` and `distributed`
=> feat: rename DisableTraceLocality to TraceCache

collect/cache/cache.go, collect/collect.go, metrics.md, tools/convert/metrics.go, tools/convert/metricsMeta.yaml
- With the new priority queue based trace cache implementation, we no longer need to monitor cache capacity and buffer overrun 
- remove `collect_cache_capacity` ad `collect_cache_buffer_overrun`
=> maint: remove unused collect_cache metrics

CHANGELOG.md, RELEASE_NOTES.md
The cache metrics were an important signal for users to monitor their refinery health. We removed it in 2.9 with the new cache implementation.
We should call out this change in the release note.
- update release note
- add missing changelog entry
=> maint: call out cache changes and add missing changelog entry

metrics/otel_metrics.go, route/route.go
When using OTELMetrics, Refinery previously only emits metrics if they have been registered. This is different from how `LegacyMetrics` works. `LegacyMetrics` will emit data regardless registration during startup. 
This PR changes OTELMetrics to match its behavior with LegacyMetrics so that we don't accidentally create different behaviors when using these two different type of metrics
- fixes #1455 
- create a `init` function for each metrics type
- call init in both `Register` and actual metrics calls
- call register for missing `router` metrics data
=> fix: register OTEL metrics if it's missing

go.mod, go.sum
[libhoney 1.25.0 
](https://github.com/honeycombio/libhoney-go/releases/tag/v1.25.0) contains the feature to increase the maximum event size to 1_000_000. 
This should allow Refinery to send bigger events to honeycomb
- bump libhoney-go version to 1.25.0
=> feat: update libhoney to 1.25.0

internal/otelutil/otel_tracing.go
In profiling data, the `Attributes()` is called even though otel tracing isn't enabled. This is a waste of CPU resource. We should only compute it when tracing is enabled
- check whether tracing is enabled in `otelutil`
=> fix: only record attributes when otel tracing is enabled

collect/collect.go
Attempts to address issue honeycombio/refinery#1477 
In `collect.go`, it changes values passed to logger so as to avoid an error in logrus lib (see issue for repro steps). Begins passing a string value to `logFields` map where currently a function ref is being passed. From looking at [logrus source at this line](https://github.com/sirupsen/logrus/blob/master/entry.go#L135), it seems the library treats passing functions or function pointers as an error.
The code was passing `td.KeptReason` function pointer to logger, but I've made the assumption that the intended value was actually the `td.Reason` string. This assumption is based on the logFields map using key of `"reason"` (rather than it using `"keptReason"`) and also that it is `td.Reason` being subsequently passed to …
=> fix: error from logrus when sending a trace

collect/collect.go, metrics.md, tools/convert/metricsMeta.yaml
- The "dropped_from_stress" metric says it's counting traces but counts spans.
- Fix the description
=> fix: dropped_from_stress description

cmd/refinery/main.go
When a non-string type value is passed in to the `AddTelemetryAttributeFunc` when `OTELTracing` is enabled, Refinery currently panics
- don't assume the attribute type
=> fix: don't assume attribute type in oteltracing

collect/collect.go
register `kept_from_stress` metric
- register `kept_from_stress` metric
=> fix: register kept_from_stress metric

CHANGELOG.md, LICENSES/github.com/felixge/httpsnoop/LICENSE.txt, LICENSES/github.com/golang/snappy/LICENSE, LICENSES/github.com/rdleal/go-priorityq/kpq/LICENSE, LICENSES/go.opentelemetry.io/auto/sdk/LICENSE, LICENSES/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/LICENSE, LICENSES/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/LICENSE, LICENSES/golang.org/x/sync/errgroup/LICENSE, Makefile, RELEASE_NOTES.md, RELEASING.md, config.md, config_complete.yaml, metrics.md, rules.md, tools/convert/configDataNames.txt, tools/convert/metricsMeta.yaml, tools/convert/minimal_config.yaml, tools/convert/templates/configV2.tmpl
- new release with bug fixes
- update licenses
- add note for go-licenses requiring 1.21.1
- tools/convert make all (generate docs)
- update changelog
- update release notes
- update releasing doc with extra detail ([see branch here for rendered doc](https://github.com/honeycombio/refinery/blob/jamie.prepv293/RELEASING.md#release-process))
=> rel: prep release v2.9.3

config/config_test.go, metrics/multi_metrics.go, metrics/multi_metrics_test.go, route/route.go
- Add a new `bytes_received_*` metric for both trace and log signal so that we can retrieve it later in our opamp agent
- Record `bytes_received` only for `incoming` data before the logic to route peer traffic. This is to prevent double counting peer traffic.
- Store counter values in `multi_metrics` so that metrics value can be retrieved later
=> feat: record bytes_received metrics for traces and logs signal

agent/agent.go, agent/agent_test.go, agent/usage_report.go, agent/usage_report_test.go
To reduce the payload size for usage reporting, this PR changes the usage reporting calculation to only report one datapoint per signal during one reporting interval
- storing only one cumulative datapoint per signal type
- modify tests
=> feat: only send one datapoint per signal in usage report

README.md, config/configLoadHelpers.go, config/configLoadHelpers_test.go
- It's useful to have certain strings in the config file be explicit environment variable references. This implements that (the syntax is `${ENV_VAR}`) and works in any string-valued config item.
- Write an envvar substitution system that works on both plain maps and config structs (with reflection).
- Hook it in so it's the last thing that happens before the config is made available.
- Write some tests for it.
- Test it manually.
This turned out to be a little more complex than I would have liked. But we probably need it.
=> feat: Support arbitrary envvar replacement in config strings

collect/collect_test.go, route/route.go, types/event.go, types/event_test.go
- This fixes a bug identified when span data processed by refinery includes a `trace_id` attribute. This change updates the field to `meta.trace_id` which should avoid collisions with existing instrumentation that sets `trace_id`.
- Update `trace_id` field for internal decisions to `meta.trace_id`
- Update the tests
=> fix: update trace_id field to meta.trace_id

sample/dynamic.go, sample/dynamic_ema.go, sample/ema_throughput.go, sample/sample.go, sample/totalthroughput.go, sample/windowed_throughput.go
- closes #1365 
- add a new metric, `<sampler-type>_trace_key_length`, for dynamic samplers to record the number of unique value in a trace key
=> maint: record sampler key cardinality as metric

collect/collect.go, collect/collect_test.go, route/route.go, types/event.go
When a trace is redistributed, we should pass along its original `SendBy` value so that we don't wait for another `TraceTimeout` value
- redistributing a span should also forward the original `SendBy` time
=> fix: maintain original TraceTimeout value on redistribution

collect/collect.go, collect/collect_test.go
When a trace only contains decision spans, it should be remove from the cache after a redistribution.
```
│ panic: runtime error: index out of range [0] with length 0                                                                                                                         │
│                                                                                                                                                                                    │
│ goroutine 141 [running]:                                                                                                                                                           │
│ github.com/honeycombio/refinery/collect.(*InMemCollector).sendExpiredTracesInCache(0x400036cc00, {0x10ad278?, 0x401e5725a0?}, {0x0?, …
```
=> fix: panic caused by empty traces after redistribution

agent/agent.go, config/config_serializer.go
Refinery only reports the config not the rules, and only reports effective config on first connection.
- Closes https://github.com/honeycombio/pipeline-team/issues/292
- update refinery to report effective config after successfully applying a new remote config
- update effective config report to include refinery rules.
=> fix: update refinery to report effective config on update

collect/collect.go, collect/collect_test.go
the mutex for collector is accessed by both the shutdown process and the collect goroutine. If the timing aligns just right, they can contend for the same lock, causing the Gosched span to appear as if it’s taking 60 seconds.
- only execute `Gosched` in tests
=> fix: only execute Gosched in tests

internal/peer/file.go, internal/peer/file_test.go, internal/peer/peers.go, internal/peer/peers_test.go, internal/peer/pubsub_redis.go, internal/peer/pubsub_test.go, sharder/deterministic_test.go
- fix: #1506 
- Resolve node's public address based on configured identifier in `file` peer mode
=> fix: use configured identifier for host address resolution in file peer

config/metadata/rulesMeta.yaml, refinery_rules.md, rules.md
Updates the rule's datatype parameter to set it's `valuetype` to `choice`. This ensure the valid choices are rendered when generating documentation.
- Add `valuetype: choice` to rule datatype parameter
- Run `make docrules` to regenerate rules markdown files
=> fix: Add valuetype to rules datatype

config.md, metrics.md, refinery_config.md, refinery_rules.md, rules.md, tools/convert/templates/cfg_docrepo.tmpl, tools/convert/templates/cfg_docsite.tmpl, tools/convert/templates/metrics.tmpl, tools/convert/templates/rules_docrepo.tmpl, tools/convert/templates/rules_docsite.tmpl
Updates the generated config and rules files to include a markdown comment at the top of the file to indicate they are generated and should not be edited manually.
I confirmed our docs website can handle these markdown comments.
- Update config and rules templates to add an auto generated message
- Regenerate config and rules files to get updated content
=> maint: Add autogenerated comment to config templates

metrics.md, route/route.go, tools/convert/metricsMeta.yaml
- copy-paste error on docs for `_router_otlp` metrics.
- update description in code
- update `metricsMeta.yaml` directly
- run `make all` from `tools/convert` directory and commit only change for this metric (other changes get updated when releasing)
=> docs: update _router_otlp description

collect/collect.go, config.md, config/config.go, config/config_test.go, config/file_config.go, config/metadata/configMeta.yaml, config/mock.go, config_complete.yaml, internal/health/health.go, metrics.md, refinery_config.md, sharder/deterministic_test.go, tools/convert/configDataNames.txt, tools/convert/metricsMeta.yaml, tools/convert/minimal_config.yaml, tools/convert/templates/configV2.tmpl
The current default configuration in Refinery sets:
* HealthCheckTimeout = 3s
* MaxExpiredTraces = 5000
During load testing, we observed that processing a single expired trace through the sampler and flushing logic takes about 5ms. If Refinery were to actually process the full batch of 5000 traces in one sendExpiredTraces iteration, it would take about 25s. This processing time far exceeds the 3s default for HealthCheckTimeout
- Decrease the default value for `MaxExpiredTraces` to 3000
- Adjust `HealthCheckTimeout` value based on `MaxExpiredTraces`
- Increase default `HealthCheckTimeout` to 15s
=> fix: use sensible default value for HealthCheckTimeout and MaxExpiredTraces

config/mock.go
We don't need to set HealthCheckTimeout config separately in mock config
- use HealthCheckTimeout set in GetCollectionConfigVal as the return value for `GetHealthCheckTimeout()`
=> fix: use value from GetCollectionConfigVal for HealthCheckTimeout in mock config

app/app_test.go, route/middleware.go, route/route_test.go
We need benchmarks which roughly approximate production bottlenecks in order to evaluate the effectiveness of optimizations.
Improves the pre-existing integration benchmarks to be more internally efficient, and use msgpack+zstd which is more typical today. Note these still output json which isn't typical in production so that still needs to be fixed.
Also adds a new test and benchmark for Router.batch() which is the primary consumer of both CPU and memory, at least in our internal cluster.
=> test: improve existing integration benchmark, add new test and benchmark for Router.batch()

agent/agent.go, agent/agent_test.go, go.mod, go.sum
- use [hpsf](https://github.com/honeycombio/hpsf/blob/9b072f9dbd61d72f6647ee95193419f270b19661/pkg/config/component.go#L10-L14) for string definitions instead of hard coded strings
- update `refinery_rules` and `refinery_config` to use HPSF config types instead.
=> maint: use hpsf for strings

collect/collect_test.go, go.mod, sample/trace_key.go, sample/trace_key_test.go
The trace key generation process was creating unnecessary memory allocations and putting pressure on garbage collection due to excessive string creation. This was particularly problematic for large traces with many spans that contains the same value for key fields.
- Replaced string concatenation and `fmt.Sprintf` operations with a reusable byte buffer to minimize allocations
-  use uint64 values as map keys instead of strings
- add unit test
This is the benchmark result from running the `collect` loop which exercises this function
```
goos: darwin
goarch: arm64
pkg: github.com/honeycombio/refinery/collect
cpu: Apple M2 Max
│   old.txt    │          new-trace-key.txt          │
│    sec/op    │   sec/op     vs base                │
CollectorWithSamplers/deterministic/small_traces-12 …
```
=> perf: optimize trace key generation with hash-based deduplication

route/batched_event.go, route/batched_event_test.go, route/route.go, route/route_test.go, types/msgp_payload_map.go, types/msgp_payload_map_test.go, types/payload.go, types/payload_test.go
Waste in the existing unmarshal() implementation remaining from the following PR:
- #1586
Skips the expensive Reader-based vmihailenco/msgpack.Decoder implementation for the common case of messagepack batches. Also de-pointerifies Payload's internal MsgpPayloadMap which was another heap allocation for no good reason. This is in no way comprehensive; there is other fat to trim in the batch ingest path.
```
benchmark                   old ns/op     new ns/op     delta
BenchmarkRouterBatch-12     5857          3724          -36.42%
benchmark                   old allocs     new allocs     delta
BenchmarkRouterBatch-12     69             44             -36.23%
benchmark                   old bytes     new bytes     delta
BenchmarkRouterBatch-12     5535          3550          -35.86%
```
=> perf: cleanup superfluous allocations during event unmarshal

collect/cache/cuckoo.go, collect/cache/cuckooSentCache.go, collect/collect.go, internal/health/health.go, sample/deterministic.go, sample/dynamic.go, sample/dynamic_ema.go, sample/ema_throughput.go, sample/rules.go, sample/sample.go, sample/totalthroughput.go, sample/windowed_throughput.go
While this issue may not affect deployed instances of Refinery, it impacts the developer experience when running tests. Previously, some goroutines were not properly shut down after calling the shutdown function. This resulted in noisy and cluttered profiles during test runs, making it difficult to analyze performance or debug issues effectively.
- wait for goroutines created by various components to finish before return from `Stop()`
=> fix: wait for goroutines to finish before shutting down

collect/collect_test.go
`EMADynamic` sampler can't maintain at SampleRate 1 due to probability. To ensure the consistency of the test result, enabling dyrun will allow all traces to be sent regardless of its sampling decision. 
- enable `DryRun` in collect loop benchmark test
=> test: enable DryRun in collect loop benchmark test

collect/collect_test.go
The TestStableMaxAlloc is flaky due to when the GC occurred and when new allocation happened in the test process.
This PR decreases the amount of trace the test needs to evict so that Refinery can detect the memory allocation change sooner rather than later.
- Change the MacAlloc config before calling reloadConfigs
- change the configured MaxAlloc in test so that we don't need to evict as much traces
=> fix: make TestStableMaxAlloc less flaky

collect/collect_test.go, go.mod, sample/trace_key.go
We already have a hashing algorithm for hashing. We don't need another one
- remove metro hash in trace_key.go and use existing wyhash instead
=> maint: remove metro hash and use wyhash instead

transmit/direct_transmit.go, transmit/direct_transmit_test.go
I need to evaluate relative performance of the transmission system, in addition to correctness.
Adds a new benchmark for transmission, direct (new) vs default (libhoney). There's a lot of boilerplate here, but note I've set a pretty low maximum connection count in the http client (just for this benchmark, for now) - without this both implementations managed to overwhelm Mac OS, resulting in http dial errors.
Despite our concerns about the naive DirectTransmission implementation, the results are stark:
```
BenchmarkTransmissionComparison/high_card/direct-8  	 5000000	       833.2 ns/op	    4680 B/op	       3 allocs/op
BenchmarkTransmissionComparison/high_card/default-8 	 5000000	     10300 ns/op	   43035 B/op	     213 allocs/op
BenchmarkTransmissionComparison/low_card/direct-8   	 5000000 …
```
=> test: add benchmark for transmission

types/payload.go
We're encoding messagepack map keys as type bin, which works but causes small garbage allocations on every read. Found this when experimenting with DirectTransmission.
This just changes the method used to encode map keys.
=> perf: fix encoded type of map keys

logger/mock.go, transmit/direct_transmit.go, transmit/direct_transmit_test.go
DirectTransmission needs to honor the same API limitations that libhoney does.
Reviewers: lots of whitespace change in this one, you'll want to ignore whitespace.
Adds a maximum payload size, and a maximum serialized event size, to DirectTransmission, with the same behavior as libhoney's Honeycomb transmission.
Also slightly cleans up and improves testing.
=> feat: add message size limits to DirectTransmission

transmit/direct_transmit.go, transmit/direct_transmit_test.go
In the original implementation, goroutine and timer proliferation were a concern.
Note: based on #1604
This replaces a whole bunch of channel and goroutine contention with a whole bunch of lock contention. I think that's going to be ok because the stuff we do while holding the lock is very cheap, and ultimately less than what libhoney was doing. It bechmarks well - the remaining allocation here is mostly in the http transport (including the test server itself) and there's not much to be done about that.
```
benchmark                                               old ns/op     new ns/op     delta
BenchmarkTransmissionComparison/high_card/direct-12     1101          702           -36.23%
BenchmarkTransmissionComparison/low_card/direct-12      894           640           -28.39%
benchmark …
```
=> perf: more scalable DirectTransmission batching

app/app_test.go, cmd/refinery/main.go, transmit/direct_transmit.go, transmit/direct_transmit_test.go
I think it's time to try it out.
Note: based on #1605 - last of the series.
Adds support for zstd compression and enables DirectTransmission in refinery proper. Also contains a bit of miscellaneous cleanup.
=> feat: switch to DirectTransmission in refinery main

route/route_test.go, types/payload.go, types/payload_test.go
All our metadata warmup code wasn't 100% baked when landed.
Restructures the big `metadataFields` table to make it much more compact.
Makes `metadataFields` a map for (hopefully) faster lookups when checking a single field by key, which seems important now that this is a longer list of fields.
More consistently ignores metadata field values which are in the `memoizedFields` map, and prevents them being added via `Set`. This means you can no longer manually set a meta field in the payload to a value of the wrong type, nor will we blindly copy these values from input to output during serialization. Probably won't come up in this codebase but we'll be better off with a single source of truth on these values.
Fixes broken BenchmarkRouterBatch
Cleans up some redundant test code and adds …
=> maint: clean up payload code and testing, fix broken benchmark

route/route_test.go
We need a benchmark for OTLP trace ingestion
Adds a sub-benchmark. We've got some work to do:
```
BenchmarkRouterBatch/msgpack    121971     9660 ns/op    19699 B/op     50 allocs/op
BenchmarkRouterBatch/otlp         7180   163270 ns/op   256411 B/op   1852 allocs/op
```
=> test: add BenchmarkRouterBatch/otlp

app/app.go, collect/collect.go, collect/collect_test.go, metrics/metrics.go, route/otlp_logs_test.go, route/proxy.go, route/route.go, route/route_test.go, sample/deterministic.go, sample/rules.go, sample/sample.go, sample/sample_test.go, types/router_types.go
When a string is dynamically created, it's allocated on the heap. This creates pressure on the GC which is biggest performance issue Refinery is currently battling with
- Only compute necessary metric names once during startup
- store the computed result as struct fields for quicker access
```
**OLD**
goos: darwin
goarch: arm64
pkg: github.com/honeycombio/refinery/route
cpu: Apple M2 Max
BenchmarkRouterBatch-12    	5418073	     8647 ns/op	  17322 B/op	     41 allocs/op
PASS
ok  	github.com/honeycombio/refinery/route	47.190s
**NEW**
goos: darwin
goarch: arm64
pkg: github.com/honeycombio/refinery/route
cpu: Apple M2 Max
BenchmarkRouterBatch-12    	5644776	     8416 ns/op	  17092 B/op	     33 allocs/op
PASS
ok  	github.com/honeycombio/refinery/route	47.861s
```
=> perf: remove dynamic string creation for metric names

config/cmdenv.go, config/config_test.go, config/file_config.go, config/metadata/configMeta.yaml, logger/honeycomb.go
- Allows the honeycomb logger to support adding attributes from the `OTEL_RESOURCE_ATTRIBUTES` env var to all exported logs.
- add logic for extracting attributes from the `OTEL_RESOURCE_ATTRIBUTES` env var
=> feat: add support for REFINERY_HONEYCOMB_LOGGER_ADDITIONAL_FIELDS to honeycomb logger

cmd/refinery/main.go, logger/honeycomb.go, metrics/legacy.go, metrics/legacy_test.go, metrics/metrics.go, metrics/multi_metrics.go, metrics/multi_metrics_test.go, metrics/otel_metrics.go, metrics/prometheus.go
Refinery supports three metrics backends: libhoney (Honeycomb), OpenTelemetry (OTel), and Prometheus. Users can enable one or more of these backends simultaneously through the MultiMetrics wrapper.
Currently, each metrics implementation—including MultiMetrics—maintains its own internal locks and in-memory copies of metrics. This leads to unnecessary duplication, especially for metrics critical to the Stress Relief system, where we only need a single shared in-memory representation.
Additionally:
- OTel and Prometheus implementations are already thread-safe and do not require extra synchronization.
- The libhoney implementation previously relied on a mutex for concurrency control. This PR updates it to use atomic operations instead, reducing lock contention and improving performance under …
=> perf: reduce lock contention for internal metrics

collect/collect_test.go
The eventually assertion in TestAddSpanCount would flake in CI[1] and occasionally in local dev when put under duress. 
Extend the deadline to reduce flakiness (and some code formatting for readability).
[1: example CI failure](https://app.circleci.com/pipelines/github/honeycombio/refinery/5191/workflows/c8021ab7-9a98-4cb2-bf48-bdf68a08b9d3/jobs/17051/steps?invite=true#step-107-52566_42)
=> ci: extend deadline for a wait in a flaky test

metrics/prometheus.go
We missed a spot in the prometheus metrics when switching from write lock to read lock.
- use read lock in Down when retrieving a gauge by name
=> perf: use read lock in Prometheus metrics Down operation

go.mod, go.sum
We would like to take advantage of the https://github.com/honeycombio/dynsampler-go/pull/81 from the 0.6.3 release
- upgrade dynsampler-go version
=> maint: upgrade dynsampler-go to 0.6.3

collect/collect.go
Spans arriving via the `i.fromPeer` channel could get counted in metrics as _incoming_ instead of _peer_ router spans.
Correct the mismatch introduced when we changed the source/router-type from a string (`"peer"`) to a Go type (`types.RouterTypePeer`).
=> fix: correct type for processing a span from a peer

route/route.go, types/payload.go, types/payload_test.go
Husky already returns a newly allocated message payload to Refinery after translating the OTLP request. We don't need to make another copy in `UnmarshalPayload`
- Create `UnmarshalPayloadComplete` to allow unmarshal a single message without copying
```
goos: darwin
goarch: arm64
pkg: github.com/honeycombio/refinery/route
cpu: Apple M2 Max
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
RouterBatch/msgpack-12   7.904µ ± 5%   7.624µ ± 7%  -3.54% (p=0.011 n=10)
RouterBatch/otlp-12      32.46µ ± 1%   31.14µ ± 1%  -4.06% (p=0.000 n=10)
geomean                  16.02µ        15.41µ       -3.80%
│   old.txt    │               new.txt                │
│     B/op     │     B/op      vs base                │
RouterBatch/msgpack-12   16.90Ki …
```
=> perf: avoid an extra copy for otlp protobuf payload during unmarshaling

transmit/direct_transmit.go, transmit/direct_transmit_test.go, types/payload_test.go
When we first replaced `transmit` + `libhoney` with `directTransmit`, we didn't implement the existing libhoney internal metrics. One of the internal libhoney metrics is required by Stress Relief. 
This PR does _not_ implement the `libhoney_*_send_retries` metric since we currently don't have retry logic yet. That will be added in a follow up PR when retry logic is added.
- Implement below metrics
- libhoney_upstream/peer_queue_length
- libhoney_upstream/peer_batches_sent
- libhoney_upstream/peer_messages_sent
- libhoney_upstream/peer_response_decode_errors
=> fix: implement missing libhoney metrics in DirectTransmit

config.md, config/metadata/configMeta.yaml, config_complete.yaml, internal/peer/file.go, internal/peer/pubsub_redis.go, refinery_config.md, tools/convert/templates/configV2.tmpl
- In #1521, @wjordan proposed allowing file peers to be hot-reloaded. This is a good idea, but they stopped responding. This PR effectively replicates that one and fixes the documentation.
- Add callbacks to FilePeers.
- Regenerate documentation.
Closes #1521.
=> feat: allow file peers to be hot-reloaded

app/app_test.go, go.mod, go.sum, route/otlp_trace.go, route/otlp_trace_test.go, route/route.go
GRPC wants to do all unmarshaling itself based on stock generated code, which doesn't play nicely with our custom, optimized data path.
Replaces the stock generated OTLP trace server with a new one which conforms to GRPC's, shall we say, idiosyncratic interface, but which uses husky's optimized translation instead of unmarshaling. This is a little awkward since (in some cases) we depend on the request info to extract the dataset, so request validation is now happening during Unmarshal, before any grpc interceptors get a look at the request. Fortunately we're not using any interceptors at the moment. The advantage of doing it this early is that we never need to make a copy of the input buffer.
Also moves some testing to work with the full GRPC stack, to remove dependencies on the details …
=> feat: use husky's optimized direct translation for GRPC calls

route/batched_event.go, route/route.go, route/route_test.go, types/json_to_msgp.go, types/json_to_msgp_test.go
JSON is still a thing, so we need to handle it efficiently.
Short-circuits the batch JSON parsing pathway to directly pick out the fields we want using optimized code, and then turn the data blob directly into messagepack. That makes this slower than messagepack, but faster than OTLP, which isn't bad.
```
benchmark                              old ns/op     new ns/op     delta
BenchmarkRouterBatch/batch_json-12     346258        26287         -92.41%
benchmark                              old allocs     new allocs     delta
BenchmarkRouterBatch/batch_json-12     1935           30             -98.45%
benchmark                              old bytes     new bytes     delta
BenchmarkRouterBatch/batch_json-12     113436        17539         -84.54%
```
=> perf: optimized JSON batch handling

config/metadata/configMeta.yaml
- updates the CacheCapacity docs to be more explicit about the deprecation.
Related to https://github.com/honeycombio/refinery/issues/1642
=> fix: update CacheCapacity description

transmit/direct_transmit.go, transmit/direct_transmit_test.go
We would like to preserve all existing `libhoney` metric names so that users can compare the performance between version upgrades easily.
- add `libhoney_` prefix to all transmit metrics
=> fix: make sure all transmit metrics have correct libhoney prefix

transmit/direct_transmit.go, transmit/direct_transmit_test.go
We're seeing longer than expected queue times for peer events, and my leading theory is that the single-tracked loop which dispatches stale events is getting bogged down. This should help figure out what's going on.
Adds a timer to each iteration of the loop which dispatches all stale batches.
=> maint: add stale batch dispatch timer to direct transmission

app/app_test.go, collect/cache/cache.go, collect/cache/cache_test.go, collect/collect.go, collect/collect_test.go, config/config_test.go, config/file_config.go, route/otlp_trace_test.go
CacheCapacity is no longer in use. This PR is to remove it from automatically setting PeerQueueSize and IncomingQueueSize
- Remove CacheCapacity from setting other configs
=> maint: (BREAKING) remove CacheCapacity functionality

config.md, config/metadata.go, config/metadata/configMeta.yaml, config_complete.yaml, refinery_config.md, tools/convert/configDataNames.txt, tools/convert/helpers.go, tools/convert/helpers_test.go, tools/convert/main.go, tools/convert/minimal_config.yaml, tools/convert/templates/configV2.tmpl, tools/convert/templates/genremoved.tmpl
This PR adds a new feature to the `convert` tool so that users can easily updating their existing config when there's deprecated fields in them.
A new `--remove-deprecated` flag is added to support removing/replacing deprecated fields. Deprecated fields are marked with`lastversion` in configMeta.yaml. Each deprecated field can define `replacements` with `formula` to calculate new values. The `convert` tool uses this metadata to know what to remove and what to replace it with. 
```
General:
ConfigurationVersion: 2
Collection:
CacheCapacity: 5000       # Deprecated
PeerQueueSize: 25000      # Not deprecated
MaxAlloc: 2147483648      # Not deprecated
#
Collection:
IncomingQueueSize: 15000
MaxAlloc: 2147483648
PeerQueueSize: 25000
General:
ConfigurationVersion: 2
```
=> feat(convert): support updating deprecated field using convert tool

transmit/direct_transmit.go, transmit/direct_transmit_test.go
Customer has reported that their `service.name` with a space in the value is showing up as `foo%20bar`
Turns out there was a [fix](https://github.com/honeycombio/libhoney-go/commit/9f4f37c3759e781e74a3c901417e80b50796a63e) added for this issue in libhoney. Our new `DirectTransmit` didn't include this fix. This PR introduce the fix into `DirectTransmit`.
TLDR is `url.Path` is expected to be unescaped. `url.String()` does the escape by default. If you set url.Path to be foo%20bar, url.String() will return foo%2520bar
=> fix: dataset name should only be url encoded once

app/app_test.go, cmd/refinery/main.go, collect/collect.go, transmit/direct_transmit.go, transmit/direct_transmit_test.go
If Honeycomb API is taking longer than expected when receiving a batch, we want to try our best to send that data instead of bailing fast
- Allow upstreamTransmission and peerTransmission to have different timeout value for their http client
- set client timeout to be 30s for upstreamTransmission
=> fix: increase upstream tranmission timeout to 30s

config/file_config.go
- Starting up Refinery 3.0-beta without IncomingQueueSize or PeerQueueSize configured results in queue sizes set to `0`.
- The sizes of these queues [used to be computed from the CacheCapacity config option that has been removed](https://github.com/honeycombio/refinery/pull/1666). With that math gone, we need to declare defaults or these will be size 0 and then you're going to have a bad time.
=> fix: set default sizes for queues

app/app_test.go, go.mod, go.sum
To bring in the fix for https://github.com/honeycombio/husky/commit/afd2a202573d9c972e555aad40d4eee1a829a43e that fixes a nil pointer panic for converting otel attributes to honeycomb event attributes
- update husky in go.mod
=> maint: update husky to 0.39.1

.circleci/config.yml, app/app_test.go, config/config_test.go, config/metadata/configMeta.yaml, config/validate.go, config/validate_test.go
Before:
```
│ ERROR: Validation failed for config [/etc/refinery/config.yaml]:                                                                                                                                                │
│   config BufferSizes is deprecated since version v2.9.7
│   config LegacyMetrics is deprecated since version v2.9.7                      
```
After:
```
│
│ ERROR: Validation failed for config [/etc/refinery/config.yaml]:                                                                                                                                                │
│   LegacyMetrics was deprecated in v2.0.0. Replace with OTelMetrics. See documentation for more details. …
```
=> maint: provide more actionable deprecation text for LegacyMetrics and BufferSizes

go.mod, go.sum
Updates husky dependency which includes a bug fix for nil pointers when converting OTLP data into honeycomb events.
- Update husky to v0.39.2
=> maint: Bump husky to v0.39.2

CHANGELOG.md, RELEASE_NOTES.md
- The lack of 3.0.0 in the world.
=> rel: prepare v3.0.0
