honeycombio/refinery

- route/route.go
Currently we just return a list of integer status codes from our batch endpoint. Our API returns a list of objects like `{"status": 202, "error": ""}`. The effect right now is that our SDK cannot process responses correctly and this complicates debugging of individual events in a batch.
> [route] update batch response to be consistent with API

- route/route.go
We need structured logs. Until then, add dataset name log lines so we can at least isolate traffic to specific datasets
> Add more logging in route handler

- app/app.go
- collect/collect.go
- logger/honeycomb.go
- logger/logger.go
- logger/logrus.go
- logger/null.go
- route/route.go
- sample/deterministic.go
- sample/dynamic.go
- sample/sample.go
- sharder/deterministic.go
- sharder/single.go
- transmit/transmit.go
Swap out the logger for one that is compatible with structured logging, because unstructured logging is the pits.
> change logging interface to accept structured logs

- logger/honeycomb.go
- main.go
> re-enable block on send in upstream/peer clients

- .circleci/config.yml
This adds the root span so you can see full traces.
> add a step to finish the build's trace

- .circleci/config.yml
There seems to be an issue running the publish step. Lets see if updating these resolves it
> Update build deps

- .circleci/config.yml
This should resolve #60.
Have added the required secrets to circle so this should work 🤞
> Push to docker hub on tagged build

- collect/collect.go
- collect/collect_test.go
- config/config.go
- config/config_test.go
- config/fileconfig.go
- config/mock.go
- types/event.go
I think this is the most basic version that implements this change now. 
See #65 and #71 for the previous attempts.
> Send events with ticker

- .circleci/config.yml
Extracted this from my work on making the redis config process smoother, this will allow us to add tests that exercise the redis code
> Make redis available during tests

- .circleci/config.yml
Use AWS executor to publish to S3
> Use AWS executor to publish to S3

- logger/mock.go
This will allow you to assert that the correct things are logged in tests
> Add mock logger for use in tests

- .circleci/config.yml
This will simplify our chef automation setup
> Drop the v from the s3 artifacts url

- collect/collect_benchmark_test.go
- transmit/mock.go
I'd like a more comprehensive integration benchmark, but this is a good start.
> add simple collect benchmark

- app/app_test.go
- route/route.go
Adds a new benchmark with a 5-node cluster. Results are pretty much as you'd expect, but profiling this does show that we spend a lot of time locking metrics. Maybe not a chief concern at this time, but something to keep an eye on.
Also includes a shutdown code for Router.
> add distributed benchmark

- collect/collect.go
I found it hard to reason about the original 3-select logic; this is simpler and a bit faster. Always drain fromPeer first, then wait on any input.
> simplify collect() loop, always drain fromPeer channel first

- sample/deterministic.go
> Remove reload callback from deterministic sampler

- app/app_test.go
- cmd/samproxy/main.go
- collect/collect_test.go
- config/config_test.go
- config/file_config.go
- config/sampler_config.go
- sample/deterministic.go
- sample/dynamic.go
- sample/dynamic_ema.go
Validate sampling rules configuration on start and reload.
> validate sampling rules configuration

- config/sampler_config.go
- config_complete.toml
- rules.toml
- sample/sample.go
`DEBU[0028] created implementation for sampler type *config.DynamicSamplerConfig  dataset="API Calls"`
> add dataset as field when logging sampler type

- sample/rules.go
- sample/rules_test.go
Adds not equal rule support
Relies on #159
> Add not equal rule

- route/errors.go
- route/route.go
Part of the rename to refinery
> Update source to refinery

- README.md
Leaves urls etc in place for now
> Rename samproxy -> refinery

- app/app.go
- route/middleware.go
- sharder/deterministic.go
- sharder/sharder.go
- types/event.go
Did a sweep of code comment renames
> Rename code comments samproxy -> refinery

- README.md
> Readme rename samproxy -> refinery

- README.md
Also some tweaks to the wording to bring in line with the recent documentation updates.
> Update README with recommendation to use IPs when DNS is unreliable or slow

- route/route.go
Defensively guards against a nil pointer dereference on the [optional Status field of a span](https://github.com/open-telemetry/opentelemetry-proto/blob/abbf7b7b49a5342d0d6c0e86e91d713bbedb6580/opentelemetry/proto/trace/v1/trace.proto#L224-L226).
https://github.com/honeycombio/refinery/issues/224
Description is provided in issue https://github.com/honeycombio/refinery/issues/224.
The status field is accessed for two reasons:
* setting the `status_code` attribute on an [`Event`'s](https://github.com/honeycombio/refinery/blob/main/types/event.go#L21-L29) payload.
* optionally setting a `status_message` if such message is found within the status field.
For the former, the PR tries to adhere to the present convention which conveys an intention that [some default …
> guard against nil pointer dereference

- CHANGELOG.md
Adds changelog for v1.10 and v1.1.0
> Prepare v1.1.0 release

- CHANGELOG.md
Adds changelog entry for v1.4.0 release.
> Prepare v1.4.0 release

- CHANGELOG.md
- RELEASE.md
Adds change log entry and RELEASE.md.
> Prepare v1.3.1 release

- CHANGELOG.md
> prepare 1.5.0 release

- CHANGELOG.md
Prepares the v1.5.2 release.
- update CHANGELOG.md with changes
> Prepare v1.5.2 release

- CHANGELOG.md
Prepares v1.6.0 release
- adds changelog entry
> Prepares v1.6.0 release

- CHANGELOG.md
> Prepare v1.7.0

- go.mod
- go.sum
Bumps Husky to v0.5.0
- updates go.mod and go.sum to use husky v0.5.0
> Bump husky to v0.5.0

- CHANGELOG.md
- prep v1.8.0 release
- update changelog for v1.8.0
> prep v1.8.0 release

- CHANGELOG.md
Prepares the v1.8.1 release.
- Adds changelog entry.
> Prepare v1.8.1 release

- CHANGELOG.md
> prepare 1.10.0 release

- CHANGELOG.md
Prepares v1.11.0 release.
- Adds changelog entry
> Prepare v1.11.0 release

- CHANGELOG.md
- Prep v1.12.0
- updates changelog, including note that v1.12.0+ is required for E&S
> Prep v1.12.0

- CHANGELOG.md
> prepare 1.12.1 release

- go.mod
- go.sum
Updates Husky to latest.
- Updates Husky to v0.10.3
> Update husky to v0.10.3

- CHANGELOG.md
Prepares the v1.13.0 release.
- Adds changelog entry
> Prepare v1.13.0 release

- CHANGELOG.md
Prepares the v1.14.0 release.
- Adds changelog entry
> Prepare v1.14.0 release

- CHANGELOG.md
Prepares the v1.15.0 release.
- Adds a changelog entry
> Prepare 1.15.0 release

- CHANGELOG.md
- adds v1.17.0 release
- remove dup entry from previous release in changelog
- add entry for v1.17.0 to changelog
> prepare release v1.17.0

- CHANGELOG.md
> Prep v1.19.0

- go.mod
- go.sum
- dependency bump of grpc to replace a bad dependabot bump
> maint: bump grpc to 1.52.3

- CHANGELOG.md
- README.md
- RELEASE_NOTES.md
- config_complete.toml
- rules_complete.toml
Final doc tweaks for release of 1.20. 
Reviewers: should I add some subheadings to the summary?
> rel: Prep for release of v1.20

- app/app_test.go
- internal/peer/peers_test.go
> fix: tweak timeouts

- collect/collect.go
- collect/collect_test.go
Closes #641 
Add hostname to spans where stress relief mode is activated.
> fix: add hostname to span during stress relief mode

- go.mod
- go.sum
Updates all the dependabot things at once.
> maint: Update dependencies

- config/metadata/rulesMeta.yaml
This PR hopes to make the generated `rules.yaml` file and associated documentation the best that it can be.
> docs: Refinery Rules copyediting

- metrics/multi_metrics.go
- metrics/multi_metrics_test.go
- metrics/otel_metrics.go
- The same injection fix as #740 without the extra shenanigans.
- Implement Start() properly where needed
- Initialize some missing stuff from OTelMetrics
> fix: metrics injection, now at half price

- config_complete.yaml
- tools/convert/templates/configV2.tmpl
- tools/convert/templates/genfile.tmpl
- tools/convert/templates/gengroup.tmpl
- `config_complete.yaml` hadn't been regenerated in a while; this tweaks templates and brings it up to date.
> docs: Update config_complete.yaml

- CHANGELOG.md
- RELEASE_NOTES.md
> rel: Prep 2.0.2

- sample/rules.go
- #799 
- Change what metric records
- Change where it's recorded
Fixes #799
> fix: location and content of sample_rate metric

- config/config_test.go
- config/metadata/configMeta.yaml
- While testing the stuff in #917 I changed some default values incorrectly.
- Fix defaults
- Add extra conditions to the default testing
> fix: default values in new config parameters

- config.md
- config_complete.yaml
- refinery_config.md
- rules.md
- tools/convert/templates/configV2.tmpl
- Update documentation in preparation for 2.2 release 
- Generate docs
> maint: refresh docs

- config.md
- config/metadata/configMeta.yaml
- refinery_config.md
- tools/convert/templates/configV2.tmpl
- Respond to docs feedback on [this PR](https://github.com/honeycombio/docs/pull/2013)
- Update metadata
- Regenerate files
> maint: Respond to docs feedback.

- CHANGELOG.md
- RELEASE_NOTES.md
- Prepare release docs for v2.2
Update CHANGELOG and Release Notes
> maint: update release docs for v2.2

- config/sampler_config.go
- sample/rules.go
- sample/rules_test.go
- Adds deterministic sampler as an explicit fallback sampler. Closes #912
> test: add deterministic fallback test

- README.md
- #929 add stress relief to refinery docs
> chore: document stress relief in readme

- CHANGELOG.md
- RELEASE_NOTES.md
> rel: Prep for release 2.3

- config/metadata/rulesMeta.yaml
- rules_conditions.md
- sample/rules.go
- sample/rules_test.go
- Addresses #906, additional work for that issue outlined in comments 
- Allow specifying root span context to rules
> feat: allow user to sample on root span context

- config.md
- config/metadata/rulesMeta.yaml
- config_complete.yaml
- refinery_config.md
- refinery_rules.md
- rules.md
- tools/convert/templates/configV2.tmpl
- Update docs in prep for release
> docs: update refinery docs

- CHANGELOG.md
- LICENSES/github.com/grpc-ecosystem/grpc-gateway/v2/LICENSE
- LICENSES/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/LICENSE
- LICENSES/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/NOTICE
- RELEASE_NOTES.md
- tools/convert/configDataNames.txt
- tools/convert/minimal_config.yaml
- Prep release for Refinery 2.4
> chore: prep refinery 2.4 release

- centralstore/centralstore.go
- centralstore/localremotestore.go
- centralstore/redis_store.go
- centralstore/redis_store_test.go
- centralstore/smartwrapper.go
- centralstore/smartwrapper_test.go
- cmd/test_stores/main.go
- collect/cache/cuckooSentCache.go
- collect/cache/cuckooSentCache_test.go
I think this is now basically usable.
> feat: improve test_stores, rename some constants

- CHANGELOG.md
- RELEASE_NOTES.md
- Releasing #1010
- update CHANGELOG and RELEASE_NOTES
- no documentation updates
- no dependency license changes
> rel: prepare v2.4.2

- CHANGELOG.md
- RELEASE_NOTES.md
- Releasing #1019
- update CHANGELOG and RELEASE_NOTES
- no documentation updates
- no dependency license changes
> rel: prepare v2.4.3

- centralstore/localremotestore.go
- centralstore/smartwrapper.go
- cmd/test_stores/main.go
- collect/cache/cuckooSentCache.go
- collect/cache/traceSentCache.go
- Beginning to put some metrics stuff in
- Implement GetMetrics for a few things
> feat: Add metrics support to smartstore and cache and localremote

- config.md
- config/metadata/configMeta.yaml
- config_complete.yaml
- refinery_config.md
- refinery_rules.md
- rules.md
- tools/convert/configDataNames.txt
- tools/convert/minimal_config.yaml
- tools/convert/templates/configV2.tmpl
Draft of configuration update for dynamic scaling.
> feat: configuration metadata update

- app/app_test.go
- centralstore/redis_store_test.go
- centralstore/smartwrapper_test.go
- cmd/refinery/main.go
- cmd/test_stores/main.go
- collect/cache/cuckoo.go
- collect/cache/cuckooSentCache.go
- collect/cache/cuckooSentCache_test.go
- collect/cache/traceSentCache.go
- collect/collect.go
- collect/collect_test.go
- collect/stressRelief.go
- route/route_test.go
This does all the bits to inject the cache.CuckooSentCache in all the places, as preparation for being able to use the CentralStore, which requires that.
> feat: make decision cache injectable 

- centralstore/smartwrapper_test.go
- Tests were flaky in smartwrapper test
- Add assertion for `WriteSpan` to make sure it's written to the backing store
- Increase SpanChannelSize in test to make sure all test spans can be processed
> fix: flaky test in smartwrapper package

- centralstore/redis_store.go
- centralstore/smartwrapper_test.go
When multiple tests are running using the same redis instance, their cleanup call may delete test data created from another running test depends on timing. 
- Run tests in each individual database index
- only cleanup test data that's created from the running test
> fix: race condition in cleanup logic in smartwrapper tests

- config/metadata/configMeta.yaml
- Updates some markers for when hot reloading works for the new features
- Update reload flags
> fix: fix config reload flags

- internal/health/health.go
- internal/health/health_test.go
- Adds an internal health monitor package that will be used for health checks
- Add health object
- Add tests for it
> feat: add health package

- collect/stressRelief/stress_relief_redis.go
- collect/stressRelief/stress_relief_test.go
Make sure the stress relief service is ready before refinery starts to accept traffic
- mark stress relief ready when it's able to publish its stress level
> feat: add health check for stress relief

- cmd/refinery/main.go
- collect/stressRelief/stress_relief_test.go
We don't use peer in new refinery anymore
-
> fix: remove peer from injection graph

- rules_complete.yaml
- rules_conditions.md
Noted in pollinators: https://honeycombpollinators.slack.com/archives/C01BZ3J7RMJ/p1714601065818559
> fix: Clarify what has-root-span does

- app/app_test.go
- centralstore/local_store.go
- collect/central_collector.go
- config/mock.go
- config/sampler_config.go
- route/route.go
- sample/mock.go
- sample/sample.go
- types/event.go
- Trying to write a test to check sampler behavior and sampler keys
- Doing this with a new MockSampler and a test that uses it
- Create a MockSampler; it always returns true and adds the sampler key it calculated
- Create a MockSamplerConfig
- Teach the SamplerFactory about it
- Write a test that uses it -- but the test isn't working so it's not finished.
> feat: test sampler key stuff with mock sampler

- centralstore/redis_store.go
- centralstore/redis_store_test.go
On Refinery startup, state machine information is loaded into Redis. However, redis can lose that information during a restart while Refinery continues to run. In this scenario, Refinery is unable to process any incoming traces due to the state machine being broken.
- Before each state transition request, we now check if the valid-state-change-events table exist. If it doesn't exist, we will repopulate it before process a state transition request
> fix: make sure information for state machine is present before state changes

- metrics/otel_metrics.go
- Fixes #1156 
- Add an RLock in the callback 
- Unlock before calling Observe()
Should be cherry-picked to Refinery 3.
> fix: correct race condition in OTel metrics

- CHANGELOG.md
- RELEASE_NOTES.md
> rel: prep v2.5.2

- go.mod
- go.sum
- bump husky to latest version
- bump husky from 0.29.0 to 0.30.0
> maint: bump husky to 0.30.0

- metrics/otel_metrics.go
- Fixes race condition described in #1156, which was already fixed on the 2.x branch.
- Copy fix from that branch.
Fixes #1156.
> fix: fix metrics race condition

- CHANGELOG.md
- RELEASE_NOTES.md
Prepares the v2.6.0 release.
- Add changelog entry
> rel: Prepare v2.6.0 release

- app/app_test.go
- internal/peer/file.go
- internal/peer/peers_test.go
- internal/peer/pubsub_redis.go
- pubsub/pubsub_goredis.go
- pubsub/pubsub_local.go
- pubsub/pubsub_test.go
- sharder/deterministic_test.go
- Adds metrics to general pubsub
- Adds metrics to peer tracking
> feat: Add metrics to pubsub and peers

- config/metadata/configMeta.yaml
- Fixes the text around propagation of config changes
Requires regeneration of docs.
> docs: Tweak docs for reload

- test/config.yaml
- I checked in an API key by accident
- Remove the key from the file
- Deactivate the key on Honeycomb
> fix: remove personal api keys

- config/metadata/configMeta.yaml
- The docs for CacheCapacity were wrong, and have been for a while.
- Rewrite the docs for CacheCapacity
> docs: fix CacheCapacity documentation

- CHANGELOG.md
- RELEASE_NOTES.md
> rel: prepare v2.7.1

- CHANGELOG.md
> rel: Prep 2.8.1

- config.md
- config/metadata/configMeta.yaml
- config_complete.yaml
- refinery_config.md
- tools/convert/templates/configV2.tmpl
Add SendKey envvar to config metadata and generate docs
- docs
> feat: add SendKey envvar config metadata

- CHANGELOG.md
- RELEASE_NOTES.md
> rel: Prep v2.8.2

- CHANGELOG.md
- RELEASE_NOTES.md
Prepares the 2.8.3 release.
- Add change log entry
> rel: Prepare 2.8.3 release

- config/metadata/configMeta.yaml
Docs fixes for generated content.
This PR reflects capitalization corrections in the summary field, so content, such as https://github.com/honeycombio/docs/pull/2386/, can be generated as expected.
> docs: Update configMeta.yaml with capitalization fixes

- CHANGELOG.md
- RELEASE_NOTES.md
- collect/collect.go
- config.md
- config_complete.yaml
- metrics.md
- refinery_config.md
- rules.md
- tools/convert/configDataNames.txt
- tools/convert/metricsMeta.yaml
- tools/convert/minimal_config.yaml
- tools/convert/templates/configV2.tmpl
- Updates main branch to include documentation from 2.8.3 release
- update changelog
- update release notes
- run `make all`.
> maint: Update main documentation with 2.8.3 release

- go.mod
- go.sum
- update husky to v0.31.0
- update husky to v0.31.0
- run go mod tidy (this brought in the updated grpc)
> maint(deps): update husky to v0.31.0

- LICENSE
- I noticed that Refinery had a NOTICE file but not a LICENSE file. It should
- Add missing LICENSE file.
> maint: Add missing LICENSE file

- CHANGELOG.md
- RELEASE_NOTES.md
- config_complete.yaml
- metrics.md
Prepares the next Refinery release.
- Add changelog entry
- Regenerate docs
> rel: Prepare the 2.9.4 release

- config.md
- config/metadata/configMeta.yaml
- config/metadata/rulesMeta.yaml
- config_complete.yaml
- refinery_config.md
- refinery_rules.md
- rules.md
- tools/convert/templates/configV2.tmpl
- a few copyedits suggested from docs team that should've been updated in #1515
> docs: some copyedits from docs

- CHANGELOG.md
- RELEASE_NOTES.md
- prepare for 2.9.5 release
- update CHANGELOG.md and RELEASE_NOTES.md
> maint: prepare for release v2.9.5

- collect/collect_test.go
We would like to measure performance of different sampling configurations with various span count per trace to identify bottlenecks and optimize the collector's performance.
- Added `BenchmarkCollectorWithSamplers` to test the performance of different sampler configurations:
- Deterministic sampler
- Dynamic sampler
- EMA dynamic sampler
- Rules-based sampler
- Implemented matrix testing across three workload scenarios:
- Small traces (100 spans per trace)
- Medium traces (10,000 spans per trace)
- Large traces (1,000,000 spans per trace)
> test: add benchmark test for collect loop

- collect/collect.go
- collect/collect_test.go
Previously, both collector_incoming_queue and collector_peer_queue lengths were being recorded inside the collect loop. Since these are channels, we can safely move the length recording logic out of the loop. This change frees up the collect loop to focus more on ingesting and processing span data, improving performance.
Additionally, this PR reduces the frequency of metric recording for these queues. These metrics are currently recorded using histograms, which are relatively expensive in terms of allocations. Prior to this change, they were being recorded at least once per ingested span or every `SendTicker` — a frequency that’s unnecessarily high and likely contributing to excessive memory usage.
By moving the metric recording to a separate goroutine and throttling updates to once per …
> perf: move collector queue metrics to be outside of the collect loop

- app/app_test.go
- route/route.go
fix: #1616 
- return 400 for empty event payload for libhoney endpoints
> fix: send http status code 400 for empty event payload

- app/app_test.go
- collect/collect_test.go
Our GRPC server setup code at the App level was never being tested, and our app-level integration test didn't include OTLP at all.
Adds OTLP in both GRPC and HTTP forms to our app integration test, to ensure we're actually setting up GRPC correctly. This will be important since I'm about to change that. Lightly refactors the non-distributed trace benchmarks to make them more efficient, and drops the single-value benchmark because it's not an optimization target.
Also attempts to fix the flaky TestOriginalSampleRateIsNotedInMetaField test.
> test: add OTLP to app test and benchmark

- transmit/direct_transmit.go
- transmit/direct_transmit_test.go
When sending a batch of events to a peer or any downstream services, if we encounter a timeout error or status code 429 or 503 with Retry-After, we should retry the request again. This matches with the libhoney-go existing behavior.
- implement retry for http timeout errors
- implement retry for 429 and 503
- Make sure number of retry is recorded in metrics
- add tests
> feat: implement retry for direct transmit

- transmit/direct_transmit.go
Since we are reseting the reader on each retry loop iteration, we don't need to get a new reader from the readerPool in each iteration. This will make the code simpler.
- Get a reader from the `readerPool` once in `sendBatch`
> maint: only use one reader per sendBatch in DirectTransmit
